// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui_door.h"
#include "../../sort.h"
#include "ui.h"

// void ui_ScreenMain_screen_init(void)
panel_with_type create_door(uint8_t index, lv_obj_t *parent)
{
    ui_PanelSensorDoor = lv_obj_create(parent);//ui_PanelContainer
    lv_obj_set_width(ui_PanelSensorDoor, 156);
    lv_obj_set_height(ui_PanelSensorDoor, 160);
    lv_obj_set_x(ui_PanelSensorDoor, -85);
    lv_obj_set_y(ui_PanelSensorDoor, -90);
    lv_obj_set_align(ui_PanelSensorDoor, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSensorDoor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSensorDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSensorDoor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSensorDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSensorDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSensorNodeDoor = lv_obj_create(ui_PanelSensorDoor);
    lv_obj_set_width(ui_PanelSensorNodeDoor, 156);
    lv_obj_set_height(ui_PanelSensorNodeDoor, 160);
    lv_obj_set_align(ui_PanelSensorNodeDoor, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSensorNodeDoor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSensorNodeDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSensorNodeDoor, lv_color_hex(0x162137), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSensorNodeDoor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSensorNodeDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelChartDoor = lv_obj_create(ui_PanelSensorNodeDoor);
    lv_obj_set_width(ui_PanelChartDoor, 156);
    lv_obj_set_height(ui_PanelChartDoor, 50);
    lv_obj_set_x(ui_PanelChartDoor, 0);
    lv_obj_set_y(ui_PanelChartDoor, -56);
    lv_obj_set_align(ui_PanelChartDoor, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelChartDoor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelChartDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelChartDoor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelChartDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelChartDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChartDisplayDoor = lv_chart_create(ui_PanelChartDoor);
    lv_obj_set_width(ui_ChartDisplayDoor, 156);
    lv_obj_set_height(ui_ChartDisplayDoor, 50);
    lv_obj_set_align(ui_ChartDisplayDoor, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ChartDisplayDoor, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_chart_set_type(ui_ChartDisplayDoor, LV_CHART_TYPE_NONE);
    lv_chart_set_range(ui_ChartDisplayDoor, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_chart_set_div_line_count(ui_ChartDisplayDoor, 0, 0);
    lv_chart_set_axis_tick(ui_ChartDisplayDoor, LV_CHART_AXIS_PRIMARY_X, 0, 0, 0, 0, false, 50);
    lv_chart_set_axis_tick(ui_ChartDisplayDoor, LV_CHART_AXIS_PRIMARY_Y, 0, 0, 0, 0, false, 100);
    lv_chart_set_axis_tick(ui_ChartDisplayDoor, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);
    lv_chart_series_t * ui_ChartDisplayDoor_series_1 = lv_chart_add_series(ui_ChartDisplayDoor, lv_color_hex(0xFFFFFF),
                                                                           LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_ChartDisplayDoor_series_1_array[] = { 0, 10, 20, 50, 80, 90, 40, 20, 40, 0 };
    lv_chart_set_ext_y_array(ui_ChartDisplayDoor, ui_ChartDisplayDoor_series_1, ui_ChartDisplayDoor_series_1_array);
    lv_obj_set_style_radius(ui_ChartDisplayDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ChartDisplayDoor, lv_color_hex(0x3DA496), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChartDisplayDoor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ChartDisplayDoor, lv_color_hex(0x141D1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_ChartDisplayDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_ChartDisplayDoor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ChartDisplayDoor, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_ChartDisplayDoor, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ChartDisplayDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_line_color(ui_ChartDisplayDoor, lv_color_hex(0x2121E2), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_ChartDisplayDoor, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(ui_ChartDisplayDoor, 2, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_set_style_line_width(ui_ChartDisplayDoor, 2, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_LabelTypeDoor = lv_label_create(ui_ChartDisplayDoor);
    lv_obj_set_width(ui_LabelTypeDoor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTypeDoor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTypeDoor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTypeDoor, "Door");
    lv_obj_set_style_text_color(ui_LabelTypeDoor, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTypeDoor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTypeDoor, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDevEUIDoor = lv_label_create(ui_PanelSensorNodeDoor);
    lv_obj_set_width(ui_LabelDevEUIDoor, 80);   /// 1 LV_SIZE_CONTENT
    lv_obj_set_height(ui_LabelDevEUIDoor, 16);    /// 1 LV_SIZE_CONTENT
    lv_obj_set_x(ui_LabelDevEUIDoor, -35);
    lv_obj_set_y(ui_LabelDevEUIDoor, -20);
    lv_obj_set_align(ui_LabelDevEUIDoor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDevEUIDoor, "ABCDEF");
    lv_obj_set_style_text_color(ui_LabelDevEUIDoor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDevEUIDoor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDevEUIDoor, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelDevEUIDoor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelDevEUIDoor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LabelDevEUIDoor, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_LabelDevEUIDoor, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelDevEUIDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelDevEUIDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelDevEUIDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelDevEUIDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_LabelDevEUIDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_LabelDevEUIDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNameDoor = lv_label_create(ui_PanelSensorNodeDoor);
    lv_obj_set_width(ui_LabelNameDoor, 71);
    lv_obj_set_height(ui_LabelNameDoor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNameDoor, -16);
    lv_obj_set_y(ui_LabelNameDoor, 51);
    lv_label_set_long_mode(ui_LabelNameDoor, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_LabelNameDoor, "0123456789ABCDEF");
    lv_obj_set_style_text_color(ui_LabelNameDoor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelNameDoor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNameDoor, &ui_font_Font12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelNameDoor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelNameDoor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LabelNameDoor, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_LabelNameDoor, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSignalStrengthDoor = lv_obj_create(ui_PanelSensorNodeDoor);
    lv_obj_set_width(ui_PanelSignalStrengthDoor, 72);
    lv_obj_set_height(ui_PanelSignalStrengthDoor, 16);
    lv_obj_set_x(ui_PanelSignalStrengthDoor, 40);
    lv_obj_set_y(ui_PanelSignalStrengthDoor, -22);
    lv_obj_set_align(ui_PanelSignalStrengthDoor, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelSignalStrengthDoor, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_PanelSignalStrengthDoor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSignalStrengthDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSignalStrengthDoor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSignalStrengthDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSignalStrengthDoor, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelSignalStrengthDoor, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelSignalStrengthDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelSignalStrengthDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelSignalStrengthDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelSignalStrengthDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelSignalStrengthDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelSignalStrengthDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageSignalStrengthDoor = lv_img_create(ui_PanelSignalStrengthDoor);
    lv_img_set_src(ui_ImageSignalStrengthDoor, &ui_img_signal_empty_png);
    lv_obj_set_width(ui_ImageSignalStrengthDoor, 25);
    lv_obj_set_height(ui_ImageSignalStrengthDoor, 16);
    lv_obj_set_x(ui_ImageSignalStrengthDoor, -23);
    lv_obj_set_y(ui_ImageSignalStrengthDoor, 0);
    lv_obj_set_align(ui_ImageSignalStrengthDoor, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageSignalStrengthDoor, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageSignalStrengthDoor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_ImageSignalStrengthDoor, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ImageSignalStrengthDoor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderSignalStrengthDoor = lv_slider_create(ui_PanelSignalStrengthDoor);
    lv_slider_set_range(ui_SliderSignalStrengthDoor, -128, 16);
    lv_slider_set_value(ui_SliderSignalStrengthDoor, -60, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderSignalStrengthDoor) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_SliderSignalStrengthDoor, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderSignalStrengthDoor, 25);
    lv_obj_set_height(ui_SliderSignalStrengthDoor, 16);
    lv_obj_set_x(ui_SliderSignalStrengthDoor, -23);
    lv_obj_set_y(ui_SliderSignalStrengthDoor, 0);
    lv_obj_set_align(ui_SliderSignalStrengthDoor, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SliderSignalStrengthDoor, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_radius(ui_SliderSignalStrengthDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderSignalStrengthDoor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSignalStrengthDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderSignalStrengthDoor, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderSignalStrengthDoor, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSignalStrengthDoor, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SliderSignalStrengthDoor, &ui_img_signal_full_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderSignalStrengthDoor, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderSignalStrengthDoor, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSignalStrengthDoor, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelSignalStrengthValueDoor = lv_label_create(ui_PanelSignalStrengthDoor);
    lv_obj_set_width(ui_LabelSignalStrengthValueDoor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSignalStrengthValueDoor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSignalStrengthValueDoor, 13);
    lv_obj_set_y(ui_LabelSignalStrengthValueDoor, 0);
    lv_obj_set_align(ui_LabelSignalStrengthValueDoor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSignalStrengthValueDoor, "Rssi: -80");
    lv_obj_set_style_text_color(ui_LabelSignalStrengthValueDoor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSignalStrengthValueDoor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSignalStrengthValueDoor, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelBatteryDoor = lv_obj_create(ui_PanelSensorNodeDoor);
    lv_obj_set_width(ui_PanelBatteryDoor, 74);
    lv_obj_set_height(ui_PanelBatteryDoor, 16);
    lv_obj_set_x(ui_PanelBatteryDoor, 40);
    lv_obj_set_y(ui_PanelBatteryDoor, -3);
    lv_obj_set_align(ui_PanelBatteryDoor, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelBatteryDoor, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_PanelBatteryDoor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelBatteryDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelBatteryDoor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelBatteryDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelBatteryDoor, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelBatteryDoor, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelBatteryDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelBatteryDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelBatteryDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelBatteryDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelBatteryDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelBatteryDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageBatteryDoor = lv_img_create(ui_PanelBatteryDoor);
    lv_img_set_src(ui_ImageBatteryDoor, &ui_img_battery_empty_png);
    lv_obj_set_width(ui_ImageBatteryDoor, 25);
    lv_obj_set_height(ui_ImageBatteryDoor, 15);
    lv_obj_set_x(ui_ImageBatteryDoor, -25);
    lv_obj_set_y(ui_ImageBatteryDoor, 0);
    lv_obj_set_align(ui_ImageBatteryDoor, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageBatteryDoor, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageBatteryDoor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SliderBatteryDoor = lv_slider_create(ui_PanelBatteryDoor);
    lv_slider_set_range(ui_SliderBatteryDoor, 2000, 4200);
    lv_slider_set_value(ui_SliderBatteryDoor, 3700, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderBatteryDoor) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderBatteryDoor, 0,
                                                                                                      LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderBatteryDoor, 25);
    lv_obj_set_height(ui_SliderBatteryDoor, 15);
    lv_obj_set_x(ui_SliderBatteryDoor, -25);
    lv_obj_set_y(ui_SliderBatteryDoor, 0);
    lv_obj_set_align(ui_SliderBatteryDoor, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SliderBatteryDoor, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_radius(ui_SliderBatteryDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderBatteryDoor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderBatteryDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderBatteryDoor, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderBatteryDoor, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderBatteryDoor, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SliderBatteryDoor, &ui_img_battery_full_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderBatteryDoor, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderBatteryDoor, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderBatteryDoor, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelBatteryDoor = lv_label_create(ui_PanelBatteryDoor);
    lv_obj_set_width(ui_LabelBatteryDoor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBatteryDoor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBatteryDoor, 14);
    lv_obj_set_y(ui_LabelBatteryDoor, 0);
    lv_obj_set_align(ui_LabelBatteryDoor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBatteryDoor, "3700mV");
    lv_obj_set_style_text_color(ui_LabelBatteryDoor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBatteryDoor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBatteryDoor, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCurrentStatusOpenDoor = lv_obj_create(ui_PanelSensorNodeDoor);
    lv_obj_set_width(ui_PanelCurrentStatusOpenDoor, 68);
    lv_obj_set_height(ui_PanelCurrentStatusOpenDoor, 38);
    lv_obj_set_x(ui_PanelCurrentStatusOpenDoor, -30);
    lv_obj_set_y(ui_PanelCurrentStatusOpenDoor, 44);
    lv_obj_set_align(ui_PanelCurrentStatusOpenDoor, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelCurrentStatusOpenDoor, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_PanelCurrentStatusOpenDoor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelCurrentStatusOpenDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelCurrentStatusOpenDoor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCurrentStatusOpenDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelCurrentStatusOpenDoor, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelCurrentStatusOpenDoor, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelCurrentStatusOpenDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelCurrentStatusOpenDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelCurrentStatusOpenDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelCurrentStatusOpenDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCurrentStatusOpenDoor = lv_label_create(ui_PanelCurrentStatusOpenDoor);
    lv_obj_set_width(ui_LabelCurrentStatusOpenDoor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCurrentStatusOpenDoor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCurrentStatusOpenDoor, -16);
    lv_obj_set_y(ui_LabelCurrentStatusOpenDoor, 0);
    lv_obj_set_align(ui_LabelCurrentStatusOpenDoor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCurrentStatusOpenDoor, "Open");
    lv_obj_set_style_text_color(ui_LabelCurrentStatusOpenDoor, lv_color_hex(0xEA2319), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCurrentStatusOpenDoor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCurrentStatusOpenDoor, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageCurrentStatusOpenDoor = lv_img_create(ui_PanelCurrentStatusOpenDoor);
    lv_img_set_src(ui_ImageCurrentStatusOpenDoor, &ui_img_door_open_png);
    lv_obj_set_width(ui_ImageCurrentStatusOpenDoor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageCurrentStatusOpenDoor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageCurrentStatusOpenDoor, 17);
    lv_obj_set_y(ui_ImageCurrentStatusOpenDoor, 0);
    lv_obj_set_align(ui_ImageCurrentStatusOpenDoor, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageCurrentStatusOpenDoor, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageCurrentStatusOpenDoor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_ImageCurrentStatusOpenDoor, lv_color_hex(0xB51111), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ImageCurrentStatusOpenDoor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCurrentStatusCloseDoor = lv_obj_create(ui_PanelSensorNodeDoor);
    lv_obj_set_width(ui_PanelCurrentStatusCloseDoor, 68);
    lv_obj_set_height(ui_PanelCurrentStatusCloseDoor, 38);
    lv_obj_set_x(ui_PanelCurrentStatusCloseDoor, -30);
    lv_obj_set_y(ui_PanelCurrentStatusCloseDoor, 44);
    lv_obj_set_align(ui_PanelCurrentStatusCloseDoor, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelCurrentStatusCloseDoor, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_PanelCurrentStatusCloseDoor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelCurrentStatusCloseDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelCurrentStatusCloseDoor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCurrentStatusCloseDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelCurrentStatusCloseDoor, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelCurrentStatusCloseDoor, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelCurrentStatusCloseDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelCurrentStatusCloseDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelCurrentStatusCloseDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelCurrentStatusCloseDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCurrentStatusCloseDoor = lv_label_create(ui_PanelCurrentStatusCloseDoor);
    lv_obj_set_width(ui_LabelCurrentStatusCloseDoor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCurrentStatusCloseDoor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCurrentStatusCloseDoor, -16);
    lv_obj_set_y(ui_LabelCurrentStatusCloseDoor, 0);
    lv_obj_set_align(ui_LabelCurrentStatusCloseDoor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCurrentStatusCloseDoor, "Close");
    lv_obj_set_style_text_color(ui_LabelCurrentStatusCloseDoor, lv_color_hex(0x11C947), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCurrentStatusCloseDoor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCurrentStatusCloseDoor, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageCurrentStatusCloseDoor = lv_img_create(ui_PanelCurrentStatusCloseDoor);
    lv_img_set_src(ui_ImageCurrentStatusCloseDoor, &ui_img_door_close_png);
    lv_obj_set_width(ui_ImageCurrentStatusCloseDoor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageCurrentStatusCloseDoor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageCurrentStatusCloseDoor, 18);
    lv_obj_set_y(ui_ImageCurrentStatusCloseDoor, 0);
    lv_obj_set_align(ui_ImageCurrentStatusCloseDoor, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageCurrentStatusCloseDoor, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageCurrentStatusCloseDoor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_ImageCurrentStatusCloseDoor, lv_color_hex(0x269A0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ImageCurrentStatusCloseDoor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelLastDoor = lv_obj_create(ui_PanelSensorNodeDoor);
    lv_obj_set_width(ui_PanelLastDoor, 68);
    lv_obj_set_height(ui_PanelLastDoor, 27);
    lv_obj_set_x(ui_PanelLastDoor, 42);
    lv_obj_set_y(ui_PanelLastDoor, 25);
    lv_obj_set_align(ui_PanelLastDoor, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelLastDoor, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_PanelLastDoor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelLastDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelLastDoor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelLastDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelLastDoor, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelLastDoor, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelLastDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelLastDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelLastDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelLastDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelLastDoor = lv_label_create(ui_PanelLastDoor);
    lv_obj_set_width(ui_LabelLastDoor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLastDoor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLastDoor, 0);
    lv_obj_set_y(ui_LabelLastDoor, -10);
    lv_obj_set_align(ui_LabelLastDoor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLastDoor, "Last Duration");
    lv_obj_set_style_text_color(ui_LabelLastDoor, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelLastDoor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelLastDoor, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelLastValueDoor = lv_label_create(ui_PanelLastDoor);
    lv_obj_set_width(ui_LabelLastValueDoor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLastValueDoor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLastValueDoor, 1);
    lv_obj_set_y(ui_LabelLastValueDoor, 4);
    lv_obj_set_align(ui_LabelLastValueDoor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLastValueDoor, "0min");
    lv_obj_set_style_text_color(ui_LabelLastValueDoor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelLastValueDoor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelLastValueDoor, &ui_font_Font12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTimesDoor = lv_obj_create(ui_PanelSensorNodeDoor);
    lv_obj_set_width(ui_PanelTimesDoor, 49);
    lv_obj_set_height(ui_PanelTimesDoor, 20);
    lv_obj_set_x(ui_PanelTimesDoor, 27);
    lv_obj_set_y(ui_PanelTimesDoor, 51);
    lv_obj_set_align(ui_PanelTimesDoor, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelTimesDoor, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_PanelTimesDoor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelTimesDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelTimesDoor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTimesDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelTimesDoor, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelTimesDoor, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTimesDoor = lv_label_create(ui_PanelTimesDoor);
    lv_obj_set_width(ui_LabelTimesDoor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTimesDoor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTimesDoor, 0);
    lv_obj_set_y(ui_LabelTimesDoor, -7);
    lv_obj_set_align(ui_LabelTimesDoor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTimesDoor, "Times");
    lv_obj_set_style_text_color(ui_LabelTimesDoor, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTimesDoor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTimesDoor, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTimesValueDoor = lv_label_create(ui_PanelTimesDoor);
    lv_obj_set_width(ui_LabelTimesValueDoor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTimesValueDoor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTimesValueDoor, 0);
    lv_obj_set_y(ui_LabelTimesValueDoor, 5);
    lv_obj_set_align(ui_LabelTimesValueDoor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTimesValueDoor, "0");
    lv_obj_set_style_text_color(ui_LabelTimesValueDoor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTimesValueDoor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTimesValueDoor, &ui_font_Font12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTimePassedDoor = lv_obj_create(ui_PanelSensorNodeDoor);
    lv_obj_set_width(ui_PanelTimePassedDoor, 128);
    lv_obj_set_height(ui_PanelTimePassedDoor, 20);
    lv_obj_set_x(ui_PanelTimePassedDoor, -14);
    lv_obj_set_y(ui_PanelTimePassedDoor, 70);
    lv_obj_set_align(ui_PanelTimePassedDoor, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelTimePassedDoor, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_PanelTimePassedDoor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelTimePassedDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelTimePassedDoor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTimePassedDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelTimePassedDoor, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelTimePassedDoor, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelTimePassedDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelTimePassedDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelTimePassedDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelTimePassedDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageTimePassedDoor = lv_img_create(ui_PanelTimePassedDoor);
    lv_img_set_src(ui_ImageTimePassedDoor, &ui_img_last_seen_png);
    lv_obj_set_width(ui_ImageTimePassedDoor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageTimePassedDoor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageTimePassedDoor, 1);
    lv_obj_set_y(ui_ImageTimePassedDoor, 0);
    lv_obj_add_flag(ui_ImageTimePassedDoor, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageTimePassedDoor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ImageTimePassedDoor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ImageTimePassedDoor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ImageTimePassedDoor, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ImageTimePassedDoor, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTimePassedValueDoor = lv_label_create(ui_PanelTimePassedDoor);
    lv_obj_set_width(ui_LabelTimePassedValueDoor, 103);
    lv_obj_set_height(ui_LabelTimePassedValueDoor, 16);
    lv_obj_set_x(ui_LabelTimePassedValueDoor, 22);
    lv_obj_set_y(ui_LabelTimePassedValueDoor, 1);
    lv_label_set_text(ui_LabelTimePassedValueDoor, "00: 00: 00: 00");//1331: 11: 23: 35
    lv_obj_set_style_text_color(ui_LabelTimePassedValueDoor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTimePassedValueDoor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTimePassedValueDoor, &ui_font_Font12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelTimePassedValueDoor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelTimePassedValueDoor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LabelTimePassedValueDoor, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_LabelTimePassedValueDoor, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTopDoor = lv_obj_create(ui_PanelSensorNodeDoor);
    lv_obj_set_width(ui_PanelTopDoor, LV_SIZE_CONTENT);   /// 27
    lv_obj_set_height(ui_PanelTopDoor, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_PanelTopDoor, 65);
    lv_obj_set_y(ui_PanelTopDoor, 67);
    lv_obj_set_align(ui_PanelTopDoor, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelTopDoor, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelTopDoor, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelTopDoor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelTopDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelTopDoor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTopDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelTopDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelTopDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelTopDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelTopDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelTopDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelTopDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelTopDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageButtonTopDoor = lv_imgbtn_create(ui_PanelTopDoor);
    lv_imgbtn_set_src(ui_ImageButtonTopDoor, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_set_top_png, NULL);
    lv_imgbtn_set_src(ui_ImageButtonTopDoor, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_cancel_set_top_png, NULL);
    lv_imgbtn_set_src(ui_ImageButtonTopDoor, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImageButtonTopDoor, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_set_top_png, NULL);
    lv_imgbtn_set_src(ui_ImageButtonTopDoor, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_cancel_set_top_png, NULL);
    lv_imgbtn_set_src(ui_ImageButtonTopDoor, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImageButtonTopDoor, 25);
    lv_obj_set_height(ui_ImageButtonTopDoor, 25);
    lv_obj_set_x(ui_ImageButtonTopDoor, 0);
    lv_obj_set_y(ui_ImageButtonTopDoor, 1);
    lv_obj_add_flag(ui_ImageButtonTopDoor, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_border_color(ui_ImageButtonTopDoor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ImageButtonTopDoor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ImageButtonTopDoor, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ImageButtonTopDoor, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_ImageButtonTopDoor, lv_color_hex(0x4BD5CB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ImageButtonTopDoor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSensorNodeDeleteDoor = lv_obj_create(ui_PanelSensorDoor);
    lv_obj_set_width(ui_PanelSensorNodeDeleteDoor, 156);
    lv_obj_set_height(ui_PanelSensorNodeDeleteDoor, 160);
    lv_obj_set_align(ui_PanelSensorNodeDeleteDoor, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelSensorNodeDeleteDoor, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelSensorNodeDeleteDoor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSensorNodeDeleteDoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSensorNodeDeleteDoor, lv_color_hex(0x162137), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSensorNodeDeleteDoor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSensorNodeDeleteDoor, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelSensorNodeDeleteDoor, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageDeleteDoor = lv_img_create(ui_PanelSensorNodeDeleteDoor);
    lv_img_set_src(ui_ImageDeleteDoor, &ui_img_delete_png);
    lv_obj_set_width(ui_ImageDeleteDoor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageDeleteDoor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageDeleteDoor, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageDeleteDoor, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageDeleteDoor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_transform_zoom(ui_ImageDeleteDoor, 288, LV_PART_MAIN | LV_STATE_PRESSED);
    // lv_obj_set_style_transform_pivot_x(ui_ImageDeleteDoor, 16, LV_PART_MAIN | LV_STATE_PRESSED);
    // lv_obj_set_style_transform_pivot_y(ui_ImageDeleteDoor, 16, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_add_event_cb(ui_SliderSignalStrengthDoor, ui_event_SliderSignalStrengthDoor, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderBatteryDoor, ui_event_SliderBatteryDoor, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImageButtonTopDoor, ui_event_ImageButtonTopDoor, LV_EVENT_ALL, ui_PanelSensorDoor);
    lv_obj_add_event_cb(ui_PanelSensorNodeDoor, ui_event_PanelSensorNodeDoor_1, LV_EVENT_ALL, ui_PanelSensorNodeDoor);
    lv_obj_add_event_cb(ui_PanelSensorNodeDoor, ui_event_PanelSensorNodeDoor_2, LV_EVENT_ALL, ui_PanelSensorNodeDeleteDoor);
    lv_obj_add_event_cb(ui_ImageDeleteDoor, ui_event_ImageDeleteDoor, LV_EVENT_ALL, ui_PanelSensorDoor);
    lv_obj_add_event_cb(ui_PanelSensorNodeDeleteDoor, ui_event_PanelSensorNodeDeleteDoor_1, LV_EVENT_ALL, ui_PanelSensorNodeDoor);
    lv_obj_add_event_cb(ui_PanelSensorNodeDeleteDoor, ui_event_PanelSensorNodeDeleteDoor_2, LV_EVENT_ALL, ui_PanelSensorNodeDeleteDoor);

    panel_with_type union_sensor;

    union_sensor.panel_union.door.ui_PanelSensorDoor = ui_PanelSensorDoor;
    union_sensor.panel_union.door.ui_PanelSensorNodeDoor = ui_PanelSensorNodeDoor;
    union_sensor.panel_union.door.ui_PanelChartDoor = ui_PanelChartDoor;
    union_sensor.panel_union.door.ui_ChartDisplayDoor = ui_ChartDisplayDoor;
    union_sensor.panel_union.door.ui_LabelTypeDoor = ui_LabelTypeDoor;
    union_sensor.panel_union.door.ui_LabelDevEUIDoor = ui_LabelDevEUIDoor;
    union_sensor.panel_union.door.ui_LabelNameDoor = ui_LabelNameDoor;
    union_sensor.panel_union.door.ui_PanelSignalStrengthDoor = ui_PanelSignalStrengthDoor;
    union_sensor.panel_union.door.ui_ImageSignalStrengthDoor = ui_ImageSignalStrengthDoor;
    union_sensor.panel_union.door.ui_SliderSignalStrengthDoor = ui_SliderSignalStrengthDoor;
    union_sensor.panel_union.door.ui_LabelSignalStrengthValueDoor = ui_LabelSignalStrengthValueDoor;
    union_sensor.panel_union.door.ui_PanelBatteryDoor = ui_PanelBatteryDoor;
    union_sensor.panel_union.door.ui_ImageBatteryDoor = ui_ImageBatteryDoor;
    union_sensor.panel_union.door.ui_SliderBatteryDoor = ui_SliderBatteryDoor;
    union_sensor.panel_union.door.ui_LabelBatteryDoor = ui_LabelBatteryDoor;
    union_sensor.panel_union.door.ui_PanelCurrentStatusOpenDoor = ui_PanelCurrentStatusOpenDoor;
    union_sensor.panel_union.door.ui_LabelCurrentStatusOpenDoor = ui_LabelCurrentStatusOpenDoor;
    union_sensor.panel_union.door.ui_ImageCurrentStatusOpenDoor = ui_ImageCurrentStatusOpenDoor;
    union_sensor.panel_union.door.ui_PanelCurrentStatusCloseDoor = ui_PanelCurrentStatusCloseDoor;
    union_sensor.panel_union.door.ui_LabelCurrentStatusCloseDoor = ui_LabelCurrentStatusCloseDoor;
    union_sensor.panel_union.door.ui_ImageCurrentStatusCloseDoor = ui_ImageCurrentStatusCloseDoor;
    union_sensor.panel_union.door.ui_PanelLastDoor = ui_PanelLastDoor;
    union_sensor.panel_union.door.ui_LabelLastDoor = ui_LabelLastDoor;
    union_sensor.panel_union.door.ui_LabelLastValueDoor = ui_LabelLastValueDoor;
    union_sensor.panel_union.door.ui_PanelTimesDoor = ui_PanelTimesDoor;
    union_sensor.panel_union.door.ui_LabelTimesDoor = ui_LabelTimesDoor;
    union_sensor.panel_union.door.ui_LabelTimesValueDoor = ui_LabelTimesValueDoor;
    union_sensor.panel_union.door.ui_PanelTimePassedDoor = ui_PanelTimePassedDoor;
    union_sensor.panel_union.door.ui_ImageTimePassedDoor = ui_ImageTimePassedDoor;
    union_sensor.panel_union.door.ui_LabelTimePassedValueDoor = ui_LabelTimePassedValueDoor;
    union_sensor.panel_union.door.ui_PanelTopDoor = ui_PanelTopDoor;
    union_sensor.panel_union.door.ui_ImageButtonTopDoor = ui_ImageButtonTopDoor;
    union_sensor.panel_union.door.ui_PanelSensorNodeDeleteDoor = ui_PanelSensorNodeDeleteDoor;
    union_sensor.panel_union.door.ui_ImageDeleteDoor = ui_ImageDeleteDoor;

    union_sensor.panel_type = 2;

    lv_obj_set_x(union_sensor.panel_union.door.ui_PanelSensorDoor, x_by_index(index));
    lv_obj_set_y(union_sensor.panel_union.door.ui_PanelSensorDoor, y_by_index(index));
    
    return union_sensor;
}
