// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenBoot_screen_init(void)
{
    ui_ScreenBoot = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenBoot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenBoot, lv_color_hex(0x303A4F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenBoot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageProduct1 = lv_img_create(ui_ScreenBoot);
    lv_img_set_src(ui_ImageProduct1, &ui_img_product_1_png);
    lv_obj_set_width(ui_ImageProduct1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageProduct1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageProduct1, -334);
    lv_obj_set_y(ui_ImageProduct1, -320);
    lv_obj_set_align(ui_ImageProduct1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageProduct1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageProduct1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageProduct2 = lv_img_create(ui_ScreenBoot);
    lv_img_set_src(ui_ImageProduct2, &ui_img_product_2_png);
    lv_obj_set_width(ui_ImageProduct2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageProduct2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageProduct2, -76);
    lv_obj_set_y(ui_ImageProduct2, -295);
    lv_obj_set_align(ui_ImageProduct2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageProduct2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageProduct2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageProduct3 = lv_img_create(ui_ScreenBoot);
    lv_img_set_src(ui_ImageProduct3, &ui_img_product_3_png);
    lv_obj_set_width(ui_ImageProduct3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageProduct3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageProduct3, 355);
    lv_obj_set_y(ui_ImageProduct3, -302);
    lv_obj_set_align(ui_ImageProduct3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageProduct3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageProduct3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageProduct4 = lv_img_create(ui_ScreenBoot);
    lv_img_set_src(ui_ImageProduct4, &ui_img_product_4_png);
    lv_obj_set_width(ui_ImageProduct4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageProduct4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageProduct4, 72);
    lv_obj_set_y(ui_ImageProduct4, -308);
    lv_obj_set_align(ui_ImageProduct4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageProduct4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageProduct4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageProduct5 = lv_img_create(ui_ScreenBoot);
    lv_img_set_src(ui_ImageProduct5, &ui_img_product_5_png);
    lv_obj_set_width(ui_ImageProduct5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageProduct5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageProduct5, 210);
    lv_obj_set_y(ui_ImageProduct5, -295);
    lv_obj_set_align(ui_ImageProduct5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageProduct5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageProduct5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageProduct6 = lv_img_create(ui_ScreenBoot);
    lv_img_set_src(ui_ImageProduct6, &ui_img_product_6_png);
    lv_obj_set_width(ui_ImageProduct6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageProduct6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageProduct6, -217);
    lv_obj_set_y(ui_ImageProduct6, -297);
    lv_obj_set_align(ui_ImageProduct6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageProduct6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageProduct6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageBootLogo1 = lv_img_create(ui_ScreenBoot);
    lv_img_set_src(ui_ImageBootLogo1, &ui_img_boot_logo_png);
    lv_obj_set_width(ui_ImageBootLogo1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageBootLogo1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageBootLogo1, -14);
    lv_obj_set_y(ui_ImageBootLogo1, 280);
    lv_obj_set_align(ui_ImageBootLogo1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageBootLogo1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageBootLogo1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageBootLogo1, 384);
    lv_obj_set_style_img_recolor(ui_ImageBootLogo1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ImageBootLogo1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageBootLogo2 = lv_img_create(ui_ScreenBoot);
    lv_img_set_src(ui_ImageBootLogo2, &ui_img_boot_logo_png);
    lv_obj_set_width(ui_ImageBootLogo2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageBootLogo2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageBootLogo2, -12);
    lv_obj_set_y(ui_ImageBootLogo2, 281);
    lv_obj_set_align(ui_ImageBootLogo2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageBootLogo2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageBootLogo2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageBootLogo2, 384);
    lv_obj_set_style_img_recolor(ui_ImageBootLogo2, lv_color_hex(0x0087B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ImageBootLogo2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_add_event_cb(ui_ScreenBoot, ui_event_ScreenBoot, LV_EVENT_ALL, NULL);

}
