// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenLoRaParams_screen_init(void)
{
    ui_ScreenLoRaParams = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenLoRaParams, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenLoRaParams, lv_color_hex(0x303A4F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenLoRaParams, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerLeftLoRaParams = lv_obj_create(ui_ScreenLoRaParams);
    lv_obj_remove_style_all(ui_ContainerLeftLoRaParams);
    lv_obj_set_width(ui_ContainerLeftLoRaParams, 121);
    lv_obj_set_height(ui_ContainerLeftLoRaParams, 480);
    lv_obj_set_x(ui_ContainerLeftLoRaParams, -340);
    lv_obj_set_y(ui_ContainerLeftLoRaParams, 0);
    lv_obj_set_align(ui_ContainerLeftLoRaParams, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerLeftLoRaParams, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContainerLeftLoRaParams, lv_color_hex(0x0F1225), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerLeftLoRaParams, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerHomePageLoRaParams = lv_obj_create(ui_ContainerLeftLoRaParams);
    lv_obj_remove_style_all(ui_ContainerHomePageLoRaParams);
    lv_obj_set_width(ui_ContainerHomePageLoRaParams, 122);
    lv_obj_set_height(ui_ContainerHomePageLoRaParams, 50);
    lv_obj_set_x(ui_ContainerHomePageLoRaParams, 0);
    lv_obj_set_y(ui_ContainerHomePageLoRaParams, -150);
    lv_obj_set_align(ui_ContainerHomePageLoRaParams, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerHomePageLoRaParams, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ContainerHomePageLoRaParams, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerHomePageLoRaParams, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContainerHomePageLoRaParams, lv_color_hex(0x0F1225), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerHomePageLoRaParams, 128, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ContainerHomePageLoRaParams, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContainerHomePageLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContainerHomePageLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContainerHomePageLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ContainerHomePageLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ContainerHomePageLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageHomePageLoRaParams = lv_img_create(ui_ContainerHomePageLoRaParams);
    lv_img_set_src(ui_ImageHomePageLoRaParams, &ui_img_home_page_png);
    lv_obj_set_width(ui_ImageHomePageLoRaParams, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageHomePageLoRaParams, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageHomePageLoRaParams, -40);
    lv_obj_set_y(ui_ImageHomePageLoRaParams, 0);
    lv_obj_set_align(ui_ImageHomePageLoRaParams, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageHomePageLoRaParams, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageHomePageLoRaParams, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageHomePageLoRaParams, 224);

    ui_LabelHomePageLoRaParams = lv_label_create(ui_ContainerHomePageLoRaParams);
    lv_obj_set_width(ui_LabelHomePageLoRaParams, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHomePageLoRaParams, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHomePageLoRaParams, 17);
    lv_obj_set_y(ui_LabelHomePageLoRaParams, 0);
    lv_obj_set_align(ui_LabelHomePageLoRaParams, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHomePageLoRaParams, "HOME");
    lv_obj_set_style_text_color(ui_LabelHomePageLoRaParams, lv_color_hex(0x303A4F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHomePageLoRaParams, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHomePageLoRaParams, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_color(ui_LabelHomePageLoRaParams, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_opa(ui_LabelHomePageLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerSettingPageLoRaParams = lv_obj_create(ui_ContainerLeftLoRaParams);
    lv_obj_remove_style_all(ui_ContainerSettingPageLoRaParams);
    lv_obj_set_width(ui_ContainerSettingPageLoRaParams, 122);
    lv_obj_set_height(ui_ContainerSettingPageLoRaParams, 50);
    lv_obj_set_x(ui_ContainerSettingPageLoRaParams, 0);
    lv_obj_set_y(ui_ContainerSettingPageLoRaParams, -100);
    lv_obj_set_align(ui_ContainerSettingPageLoRaParams, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerSettingPageLoRaParams, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ContainerSettingPageLoRaParams, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerSettingPageLoRaParams, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContainerSettingPageLoRaParams, lv_color_hex(0x0F1225), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerSettingPageLoRaParams, 128, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ContainerSettingPageLoRaParams, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContainerSettingPageLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContainerSettingPageLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContainerSettingPageLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ContainerSettingPageLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ContainerSettingPageLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageSettingPageLoRaParams = lv_img_create(ui_ContainerSettingPageLoRaParams);
    lv_img_set_src(ui_ImageSettingPageLoRaParams, &ui_img_setting_png);
    lv_obj_set_width(ui_ImageSettingPageLoRaParams, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageSettingPageLoRaParams, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageSettingPageLoRaParams, -42);
    lv_obj_set_y(ui_ImageSettingPageLoRaParams, 0);
    lv_obj_set_align(ui_ImageSettingPageLoRaParams, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageSettingPageLoRaParams, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageSettingPageLoRaParams, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageSettingPageLoRaParams, 240);

    ui_LabelSettingPageLoRaParams = lv_label_create(ui_ContainerSettingPageLoRaParams);
    lv_obj_set_width(ui_LabelSettingPageLoRaParams, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSettingPageLoRaParams, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSettingPageLoRaParams, 18);
    lv_obj_set_y(ui_LabelSettingPageLoRaParams, 0);
    lv_obj_set_align(ui_LabelSettingPageLoRaParams, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSettingPageLoRaParams, "SETTING");
    lv_obj_set_style_text_color(ui_LabelSettingPageLoRaParams, lv_color_hex(0x303A4F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSettingPageLoRaParams, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSettingPageLoRaParams, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerLoRaPageLoRaParams = lv_obj_create(ui_ContainerLeftLoRaParams);
    lv_obj_remove_style_all(ui_ContainerLoRaPageLoRaParams);
    lv_obj_set_width(ui_ContainerLoRaPageLoRaParams, 122);
    lv_obj_set_height(ui_ContainerLoRaPageLoRaParams, 50);
    lv_obj_set_x(ui_ContainerLoRaPageLoRaParams, 0);
    lv_obj_set_y(ui_ContainerLoRaPageLoRaParams, -50);
    lv_obj_set_align(ui_ContainerLoRaPageLoRaParams, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerLoRaPageLoRaParams, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ContainerLoRaPageLoRaParams, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerLoRaPageLoRaParams, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContainerLoRaPageLoRaParams, lv_color_hex(0x0F1225), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerLoRaPageLoRaParams, 128, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ContainerLoRaPageLoRaParams, lv_color_hex(0x0BA8EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ContainerLoRaPageLoRaParams, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContainerLoRaPageLoRaParams, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ContainerLoRaPageLoRaParams, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ContainerLoRaPageLoRaParams, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContainerLoRaPageLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContainerLoRaPageLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContainerLoRaPageLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ContainerLoRaPageLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ContainerLoRaPageLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageLoRaPageLoRaParams = lv_img_create(ui_ContainerLoRaPageLoRaParams);
    lv_img_set_src(ui_ImageLoRaPageLoRaParams, &ui_img_lora_module_png);
    lv_obj_set_width(ui_ImageLoRaPageLoRaParams, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageLoRaPageLoRaParams, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageLoRaPageLoRaParams, -46);
    lv_obj_set_y(ui_ImageLoRaPageLoRaParams, 0);
    lv_obj_set_align(ui_ImageLoRaPageLoRaParams, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageLoRaPageLoRaParams, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageLoRaPageLoRaParams, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageLoRaPageLoRaParams, 208);
    lv_obj_set_style_img_recolor(ui_ImageLoRaPageLoRaParams, lv_color_hex(0x0BA8EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ImageLoRaPageLoRaParams, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelLoRaPageLoRaParams = lv_label_create(ui_ContainerLoRaPageLoRaParams);
    lv_obj_set_width(ui_LabelLoRaPageLoRaParams, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLoRaPageLoRaParams, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLoRaPageLoRaParams, 17);
    lv_obj_set_y(ui_LabelLoRaPageLoRaParams, 0);
    lv_obj_set_align(ui_LabelLoRaPageLoRaParams, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLoRaPageLoRaParams, "LoRa");
    lv_obj_set_style_text_color(ui_LabelLoRaPageLoRaParams, lv_color_hex(0x0BA8EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelLoRaPageLoRaParams, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelLoRaPageLoRaParams, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_color(ui_LabelLoRaPageLoRaParams, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_opa(ui_LabelLoRaPageLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageLogoLoRaParams = lv_img_create(ui_ContainerLeftLoRaParams);
    lv_img_set_src(ui_ImageLogoLoRaParams, &ui_img_logo_png);
    lv_obj_set_width(ui_ImageLogoLoRaParams, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageLogoLoRaParams, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageLogoLoRaParams, 0);
    lv_obj_set_y(ui_ImageLogoLoRaParams, -220);
    lv_obj_set_align(ui_ImageLogoLoRaParams, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageLogoLoRaParams, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageLogoLoRaParams, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelSeparateTableScreenLoRaParams = lv_obj_create(ui_ContainerLeftLoRaParams);
    lv_obj_set_width(ui_PanelSeparateTableScreenLoRaParams, 100);
    lv_obj_set_height(ui_PanelSeparateTableScreenLoRaParams, 1);
    lv_obj_set_x(ui_PanelSeparateTableScreenLoRaParams, 0);
    lv_obj_set_y(ui_PanelSeparateTableScreenLoRaParams, -195);
    lv_obj_set_align(ui_PanelSeparateTableScreenLoRaParams, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSeparateTableScreenLoRaParams, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelSeparateTableScreenLoRaParams, lv_color_hex(0x3A3F4B),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSeparateTableScreenLoRaParams, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_PanelSeparateTableScreenLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_PanelSeparateTableScreenLoRaParams, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSeparateTableScreenLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerMessageNoticeLoRaParams = lv_obj_create(ui_ScreenLoRaParams);
    lv_obj_remove_style_all(ui_ContainerMessageNoticeLoRaParams);
    lv_obj_set_width(ui_ContainerMessageNoticeLoRaParams, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_ContainerMessageNoticeLoRaParams, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_ContainerMessageNoticeLoRaParams, 60);
    lv_obj_set_y(ui_ContainerMessageNoticeLoRaParams, -270);
    lv_obj_set_align(ui_ContainerMessageNoticeLoRaParams, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerMessageNoticeLoRaParams, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelMessageNoticeLoRaParams = lv_label_create(ui_ContainerMessageNoticeLoRaParams);
    lv_obj_set_width(ui_LabelMessageNoticeLoRaParams, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMessageNoticeLoRaParams, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelMessageNoticeLoRaParams, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMessageNoticeLoRaParams, "");
    lv_obj_set_style_text_color(ui_LabelMessageNoticeLoRaParams, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMessageNoticeLoRaParams, 128, LV_PART_MAIN | LV_STATE_DEFAULT);//255
    lv_obj_set_style_text_font(ui_LabelMessageNoticeLoRaParams, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);//&lv_font_montserrat_16  &lv_font_montserrat_12

    ui_PanelPanelLoRaParams = lv_obj_create(ui_ScreenLoRaParams);
    lv_obj_set_width(ui_PanelPanelLoRaParams, 679);
    lv_obj_set_height(ui_PanelPanelLoRaParams, 480);
    lv_obj_set_x(ui_PanelPanelLoRaParams, 60);
    lv_obj_set_y(ui_PanelPanelLoRaParams, 0);
    lv_obj_set_align(ui_PanelPanelLoRaParams, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelPanelLoRaParams, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelPanelLoRaParams, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPanelLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelPanelLoRaParams, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelPanelLoRaParams, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelPanelLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelLA66FwLoRaParams = lv_obj_create(ui_PanelPanelLoRaParams);
    lv_obj_set_width(ui_PanelLA66FwLoRaParams, 520);
    lv_obj_set_height(ui_PanelLA66FwLoRaParams, 40);
    lv_obj_set_x(ui_PanelLA66FwLoRaParams, -76);
    lv_obj_set_y(ui_PanelLA66FwLoRaParams, -215 + 6);
    lv_obj_set_align(ui_PanelLA66FwLoRaParams, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelLA66FwLoRaParams, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelLA66FwLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelLA66FwLoRaParams, lv_color_hex(0x5378C1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelLA66FwLoRaParams, 64, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelLA66FwLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PanelLA66FwLoRaParams, lv_color_hex(0x2DAE52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_PanelLA66FwLoRaParams, 32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelLA66FwLoRaParams, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PanelLA66FwLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelLA66FwLoRaParams, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelLA66FwLoRaParams, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelLA66FwLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelLA66FwLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DropdownCurrentFwLoRaParams = lv_dropdown_create(ui_PanelLA66FwLoRaParams);
    lv_dropdown_set_options(ui_DropdownCurrentFwLoRaParams,
                            "LA66 Firmware: unrecognized\nLA66 Firmware: P2P\nLA66 Firmware: CLASS C\nLA66 Firmware: Detecting...");
    lv_obj_set_width(ui_DropdownCurrentFwLoRaParams, 276);
    lv_obj_set_height(ui_DropdownCurrentFwLoRaParams, 28);
    lv_obj_set_align(ui_DropdownCurrentFwLoRaParams, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_DropdownCurrentFwLoRaParams, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DropdownCurrentFwLoRaParams, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_text_color(ui_DropdownCurrentFwLoRaParams, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DropdownCurrentFwLoRaParams, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DropdownCurrentFwLoRaParams, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_DropdownCurrentFwLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DropdownCurrentFwLoRaParams, lv_color_hex(0xC5CED5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DropdownCurrentFwLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DropdownCurrentFwLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_DropdownCurrentFwLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DropdownCurrentFwLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DropdownCurrentFwLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DropdownCurrentFwLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_DropdownCurrentFwLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_DropdownCurrentFwLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_DropdownCurrentFwLoRaParams, lv_color_hex(0x808080),
                                LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DropdownCurrentFwLoRaParams, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DropdownCurrentFwLoRaParams, &lv_font_montserrat_16,
                               LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_DropdownCurrentFwLoRaParams), &lv_font_montserrat_16,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(lv_dropdown_get_list(ui_DropdownCurrentFwLoRaParams), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_DropdownCurrentFwLoRaParams), lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_DropdownCurrentFwLoRaParams), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(lv_dropdown_get_list(ui_DropdownCurrentFwLoRaParams), 0,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(lv_dropdown_get_list(ui_DropdownCurrentFwLoRaParams), 2,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(lv_dropdown_get_list(ui_DropdownCurrentFwLoRaParams), 2,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(lv_dropdown_get_list(ui_DropdownCurrentFwLoRaParams), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(lv_dropdown_get_list(ui_DropdownCurrentFwLoRaParams), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(lv_dropdown_get_list(ui_DropdownCurrentFwLoRaParams), 2,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(lv_dropdown_get_list(ui_DropdownCurrentFwLoRaParams), 2,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_DropdownCurrentFwLoRaParams), &lv_font_montserrat_16,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(lv_dropdown_get_list(ui_DropdownCurrentFwLoRaParams), 0,
                                  LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_LabelFwVersionLoRaParams = lv_label_create(ui_PanelLA66FwLoRaParams);
    lv_obj_set_width(ui_LabelFwVersionLoRaParams, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFwVersionLoRaParams, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFwVersionLoRaParams, 0);
    lv_obj_set_y(ui_LabelFwVersionLoRaParams, 0);
    lv_obj_set_align(ui_LabelFwVersionLoRaParams, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelFwVersionLoRaParams, "");//Version: 
    lv_obj_set_style_text_color(ui_LabelFwVersionLoRaParams, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelFwVersionLoRaParams, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelFwVersionLoRaParams, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonFwDetectLoRaParams = lv_btn_create(ui_PanelLA66FwLoRaParams);
    lv_obj_set_width(ui_ButtonFwDetectLoRaParams, LV_SIZE_CONTENT);   /// 160
    lv_obj_set_height(ui_ButtonFwDetectLoRaParams, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_ButtonFwDetectLoRaParams, 0);//-120 -60 -180
    lv_obj_set_y(ui_ButtonFwDetectLoRaParams, 0);
    lv_obj_set_align(ui_ButtonFwDetectLoRaParams, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_ButtonFwDetectLoRaParams, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonFwDetectLoRaParams, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonFwDetectLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonFwDetectLoRaParams, lv_color_hex(0x00EDFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonFwDetectLoRaParams, 128, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ButtonFwDetectLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ButtonFwDetectLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ButtonFwDetectLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ButtonFwDetectLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ButtonFwDetectLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ButtonFwDetectLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ButtonFwDetectLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ButtonFwDetectLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFwDetectLoRaParams = lv_label_create(ui_ButtonFwDetectLoRaParams);
    lv_obj_set_width(ui_LabelFwDetectLoRaParams, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFwDetectLoRaParams, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelFwDetectLoRaParams, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelFwDetectLoRaParams, "Fw Detect");
    lv_obj_set_style_text_color(ui_LabelFwDetectLoRaParams, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelFwDetectLoRaParams, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelFwDetectLoRaParams, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ui_ButtonGetLA66ConfigLoRaParams = lv_btn_create(ui_PanelLA66FwLoRaParams);
    // lv_obj_set_width(ui_ButtonGetLA66ConfigLoRaParams, LV_SIZE_CONTENT);   /// 160
    // lv_obj_set_height(ui_ButtonGetLA66ConfigLoRaParams, LV_SIZE_CONTENT);    /// 24
    // lv_obj_set_align(ui_ButtonGetLA66ConfigLoRaParams, LV_ALIGN_RIGHT_MID);
    // lv_obj_add_flag(ui_ButtonGetLA66ConfigLoRaParams, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    // lv_obj_clear_flag(ui_ButtonGetLA66ConfigLoRaParams, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    // lv_obj_set_style_radius(ui_ButtonGetLA66ConfigLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_color(ui_ButtonGetLA66ConfigLoRaParams, lv_color_hex(0x00FF8C), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_opa(ui_ButtonGetLA66ConfigLoRaParams, 128, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_shadow_width(ui_ButtonGetLA66ConfigLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_shadow_spread(ui_ButtonGetLA66ConfigLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_pad_left(ui_ButtonGetLA66ConfigLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_pad_right(ui_ButtonGetLA66ConfigLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_pad_top(ui_ButtonGetLA66ConfigLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_pad_bottom(ui_ButtonGetLA66ConfigLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_pad_row(ui_ButtonGetLA66ConfigLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_pad_column(ui_ButtonGetLA66ConfigLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ui_LabelGetLA66ConfigLoRaParams = lv_label_create(ui_ButtonGetLA66ConfigLoRaParams);
    // lv_obj_set_width(ui_LabelGetLA66ConfigLoRaParams, LV_SIZE_CONTENT);   /// 1
    // lv_obj_set_height(ui_LabelGetLA66ConfigLoRaParams, LV_SIZE_CONTENT);    /// 1
    // lv_obj_set_align(ui_LabelGetLA66ConfigLoRaParams, LV_ALIGN_CENTER);
    // lv_label_set_text(ui_LabelGetLA66ConfigLoRaParams, "Data Update");
    // lv_obj_set_style_text_color(ui_LabelGetLA66ConfigLoRaParams, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_opa(ui_LabelGetLA66ConfigLoRaParams, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_font(ui_LabelGetLA66ConfigLoRaParams, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelFontSizeLoRaParams = lv_obj_create(ui_PanelPanelLoRaParams);
    lv_obj_set_width(ui_PanelFontSizeLoRaParams, 146);
    lv_obj_set_height(ui_PanelFontSizeLoRaParams, 40);
    lv_obj_set_x(ui_PanelFontSizeLoRaParams, 263);
    lv_obj_set_y(ui_PanelFontSizeLoRaParams, -215 + 6);
    lv_obj_set_align(ui_PanelFontSizeLoRaParams, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelFontSizeLoRaParams, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_PanelFontSizeLoRaParams, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelFontSizeLoRaParams, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelFontSizeLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelFontSizeLoRaParams, lv_color_hex(0x5378C1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelFontSizeLoRaParams, 64, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelFontSizeLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PanelFontSizeLoRaParams, lv_color_hex(0x2DAE52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_PanelFontSizeLoRaParams, 32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelFontSizeLoRaParams, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PanelFontSizeLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelFontSizeLoRaParams, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelFontSizeLoRaParams, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelFontSizeLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelFontSizeLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelFontSizeLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelFontSizeLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFontSizeLoRaParams = lv_label_create(ui_PanelFontSizeLoRaParams);
    lv_obj_set_width(ui_LabelFontSizeLoRaParams, 80);
    lv_obj_set_height(ui_LabelFontSizeLoRaParams, 25);
    lv_obj_set_align(ui_LabelFontSizeLoRaParams, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelFontSizeLoRaParams, "Font Size:");
    lv_obj_set_style_text_color(ui_LabelFontSizeLoRaParams, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelFontSizeLoRaParams, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelFontSizeLoRaParams, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelFontSizeLoRaParams, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelFontSizeLoRaParams, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelFontSizeLoRaParams, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelFontSizeLoRaParams, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DropdownFontSizeLoRaParams = lv_dropdown_create(ui_PanelFontSizeLoRaParams);
    lv_dropdown_set_options(ui_DropdownFontSizeLoRaParams, "12\n14\n16\n18\n20\n22\n24\n26\n28\n30\n32\n34\n36");
    lv_obj_set_width(ui_DropdownFontSizeLoRaParams, 48);
    lv_obj_set_height(ui_DropdownFontSizeLoRaParams, 28);
    lv_obj_set_x(ui_DropdownFontSizeLoRaParams, 80);
    lv_obj_set_y(ui_DropdownFontSizeLoRaParams, 0);
    lv_obj_set_align(ui_DropdownFontSizeLoRaParams, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_DropdownFontSizeLoRaParams, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_DropdownFontSizeLoRaParams, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DropdownFontSizeLoRaParams, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DropdownFontSizeLoRaParams, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_DropdownFontSizeLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DropdownFontSizeLoRaParams, lv_color_hex(0xC5CED5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DropdownFontSizeLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DropdownFontSizeLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_DropdownFontSizeLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DropdownFontSizeLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DropdownFontSizeLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DropdownFontSizeLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_DropdownFontSizeLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_DropdownFontSizeLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_DropdownFontSizeLoRaParams, &lv_font_montserrat_16, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_DropdownFontSizeLoRaParams), &lv_font_montserrat_16,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(lv_dropdown_get_list(ui_DropdownFontSizeLoRaParams), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_DropdownFontSizeLoRaParams), lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_DropdownFontSizeLoRaParams), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(lv_dropdown_get_list(ui_DropdownFontSizeLoRaParams), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(lv_dropdown_get_list(ui_DropdownFontSizeLoRaParams), 2,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(lv_dropdown_get_list(ui_DropdownFontSizeLoRaParams), 2,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(lv_dropdown_get_list(ui_DropdownFontSizeLoRaParams), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(lv_dropdown_get_list(ui_DropdownFontSizeLoRaParams), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(lv_dropdown_get_list(ui_DropdownFontSizeLoRaParams), 2,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(lv_dropdown_get_list(ui_DropdownFontSizeLoRaParams), 2,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_DropdownFontSizeLoRaParams), &lv_font_montserrat_16,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(lv_dropdown_get_list(ui_DropdownFontSizeLoRaParams), 0,
                                  LV_PART_SELECTED | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_right(lv_dropdown_get_list(ui_DropdownFontSizeLoRaParams), 1,  LV_PART_SCROLLBAR | LV_STATE_DEFAULT);//2 0

    ui_PanelLoRaWANNetworkStatusLoRaParams = lv_obj_create(ui_PanelPanelLoRaParams);
    lv_obj_set_width(ui_PanelLoRaWANNetworkStatusLoRaParams, 539);
    lv_obj_set_height(ui_PanelLoRaWANNetworkStatusLoRaParams, 40);
    lv_obj_set_x(ui_PanelLoRaWANNetworkStatusLoRaParams, -67);
    lv_obj_set_y(ui_PanelLoRaWANNetworkStatusLoRaParams, -170 + 6);
    lv_obj_set_align(ui_PanelLoRaWANNetworkStatusLoRaParams, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelLoRaWANNetworkStatusLoRaParams, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelLoRaWANNetworkStatusLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelLoRaWANNetworkStatusLoRaParams, lv_color_hex(0x5378C1),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelLoRaWANNetworkStatusLoRaParams, 64, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelLoRaWANNetworkStatusLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PanelLoRaWANNetworkStatusLoRaParams, lv_color_hex(0x2DAE52),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_PanelLoRaWANNetworkStatusLoRaParams, 32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelLoRaWANNetworkStatusLoRaParams, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PanelLoRaWANNetworkStatusLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelLoRaWANNetworkStatusLoRaParams, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelLoRaWANNetworkStatusLoRaParams, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelLoRaWANNetworkStatusLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelLoRaWANNetworkStatusLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DropdownLoRaWANNetworkStatusLoRaParams = lv_dropdown_create(ui_PanelLoRaWANNetworkStatusLoRaParams);
    lv_dropdown_set_options(ui_DropdownLoRaWANNetworkStatusLoRaParams,
                            "LoRaWAN Network Activation Status: not activated\nLoRaWAN Network Activation Status: activated\nLoRaWAN Network Activation Status: activating...");
    lv_obj_set_width(ui_DropdownLoRaWANNetworkStatusLoRaParams, 440);
    lv_obj_set_height(ui_DropdownLoRaWANNetworkStatusLoRaParams, 28);
    lv_obj_set_align(ui_DropdownLoRaWANNetworkStatusLoRaParams, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_DropdownLoRaWANNetworkStatusLoRaParams, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DropdownLoRaWANNetworkStatusLoRaParams, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_text_color(ui_DropdownLoRaWANNetworkStatusLoRaParams, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DropdownLoRaWANNetworkStatusLoRaParams, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DropdownLoRaWANNetworkStatusLoRaParams, &lv_font_montserrat_16,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_DropdownLoRaWANNetworkStatusLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DropdownLoRaWANNetworkStatusLoRaParams, lv_color_hex(0xC5CED5),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DropdownLoRaWANNetworkStatusLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DropdownLoRaWANNetworkStatusLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_DropdownLoRaWANNetworkStatusLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DropdownLoRaWANNetworkStatusLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DropdownLoRaWANNetworkStatusLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DropdownLoRaWANNetworkStatusLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_DropdownLoRaWANNetworkStatusLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_DropdownLoRaWANNetworkStatusLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_DropdownLoRaWANNetworkStatusLoRaParams, lv_color_hex(0x808080),
                                LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DropdownLoRaWANNetworkStatusLoRaParams, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DropdownLoRaWANNetworkStatusLoRaParams, &lv_font_montserrat_16,
                               LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_DropdownLoRaWANNetworkStatusLoRaParams), &lv_font_montserrat_16,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(lv_dropdown_get_list(ui_DropdownLoRaWANNetworkStatusLoRaParams), 0,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_DropdownLoRaWANNetworkStatusLoRaParams), lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_DropdownLoRaWANNetworkStatusLoRaParams), 255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(lv_dropdown_get_list(ui_DropdownLoRaWANNetworkStatusLoRaParams), 0,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(lv_dropdown_get_list(ui_DropdownLoRaWANNetworkStatusLoRaParams), 2,
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(lv_dropdown_get_list(ui_DropdownLoRaWANNetworkStatusLoRaParams), 2,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(lv_dropdown_get_list(ui_DropdownLoRaWANNetworkStatusLoRaParams), 0,
                             LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(lv_dropdown_get_list(ui_DropdownLoRaWANNetworkStatusLoRaParams), 0,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(lv_dropdown_get_list(ui_DropdownLoRaWANNetworkStatusLoRaParams), 2,
                             LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(lv_dropdown_get_list(ui_DropdownLoRaWANNetworkStatusLoRaParams), 2,
                                LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_DropdownLoRaWANNetworkStatusLoRaParams), &lv_font_montserrat_16,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(lv_dropdown_get_list(ui_DropdownLoRaWANNetworkStatusLoRaParams), 0,
                                  LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_ButtonLoRaWANNetworkActivateLoRaParams = lv_btn_create(ui_PanelLoRaWANNetworkStatusLoRaParams);
    lv_obj_set_width(ui_ButtonLoRaWANNetworkActivateLoRaParams, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonLoRaWANNetworkActivateLoRaParams, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ButtonLoRaWANNetworkActivateLoRaParams, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_ButtonLoRaWANNetworkActivateLoRaParams, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonLoRaWANNetworkActivateLoRaParams, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_clear_flag(ui_ButtonLoRaWANNetworkActivateLoRaParams, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonLoRaWANNetworkActivateLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonLoRaWANNetworkActivateLoRaParams, lv_color_hex(0xB3DF3A),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonLoRaWANNetworkActivateLoRaParams, 128, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ButtonLoRaWANNetworkActivateLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ButtonLoRaWANNetworkActivateLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ButtonLoRaWANNetworkActivateLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ButtonLoRaWANNetworkActivateLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ButtonLoRaWANNetworkActivateLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ButtonLoRaWANNetworkActivateLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ButtonLoRaWANNetworkActivateLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ButtonLoRaWANNetworkActivateLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelLoRaWANNetworkActivateLoRaParams = lv_label_create(ui_ButtonLoRaWANNetworkActivateLoRaParams);
    lv_obj_set_width(ui_LabelLoRaWANNetworkActivateLoRaParams, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLoRaWANNetworkActivateLoRaParams, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelLoRaWANNetworkActivateLoRaParams, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLoRaWANNetworkActivateLoRaParams, "Activate");
    lv_obj_set_style_text_color(ui_LabelLoRaWANNetworkActivateLoRaParams, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelLoRaWANNetworkActivateLoRaParams, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelLoRaWANNetworkActivateLoRaParams, &lv_font_montserrat_16,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelLoRaWANNetworkStatusHideLoRaParams = lv_obj_create(ui_PanelPanelLoRaParams);
    lv_obj_set_width(ui_PanelLoRaWANNetworkStatusHideLoRaParams, 539);
    lv_obj_set_height(ui_PanelLoRaWANNetworkStatusHideLoRaParams, 40);
    lv_obj_set_x(ui_PanelLoRaWANNetworkStatusHideLoRaParams, -67);
    lv_obj_set_y(ui_PanelLoRaWANNetworkStatusHideLoRaParams, -170 + 6);
    lv_obj_set_align(ui_PanelLoRaWANNetworkStatusHideLoRaParams, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelLoRaWANNetworkStatusHideLoRaParams, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelLoRaWANNetworkStatusHideLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelLoRaWANNetworkStatusHideLoRaParams, lv_color_hex(0x05122A),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelLoRaWANNetworkStatusHideLoRaParams, 192, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelLoRaWANNetworkStatusHideLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PanelLoRaWANNetworkStatusHideLoRaParams, lv_color_hex(0x2DAE52),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_PanelLoRaWANNetworkStatusHideLoRaParams, 32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelLoRaWANNetworkStatusHideLoRaParams, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PanelLoRaWANNetworkStatusHideLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelLoRaWANNetworkStatusHideLoRaParams, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelLoRaWANNetworkStatusHideLoRaParams, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelLoRaWANNetworkStatusHideLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelLoRaWANNetworkStatusHideLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonFontSizeIncreaseLoRaParams = lv_btn_create(ui_PanelPanelLoRaParams);
    lv_obj_set_width(ui_ButtonFontSizeIncreaseLoRaParams, 48);
    lv_obj_set_height(ui_ButtonFontSizeIncreaseLoRaParams, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ButtonFontSizeIncreaseLoRaParams, -54);
    lv_obj_set_y(ui_ButtonFontSizeIncreaseLoRaParams, -170 + 6);
    lv_obj_set_align(ui_ButtonFontSizeIncreaseLoRaParams, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_ButtonFontSizeIncreaseLoRaParams, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonFontSizeIncreaseLoRaParams, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonFontSizeIncreaseLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonFontSizeIncreaseLoRaParams, lv_color_hex(0x5378C1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonFontSizeIncreaseLoRaParams, 164, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ButtonFontSizeIncreaseLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ButtonFontSizeIncreaseLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ButtonFontSizeIncreaseLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ButtonFontSizeIncreaseLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ButtonFontSizeIncreaseLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ButtonFontSizeIncreaseLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ButtonFontSizeIncreaseLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ButtonFontSizeIncreaseLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFontSizeIncreaseLoRaParams = lv_label_create(ui_ButtonFontSizeIncreaseLoRaParams);
    lv_obj_set_width(ui_LabelFontSizeIncreaseLoRaParams, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFontSizeIncreaseLoRaParams, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelFontSizeIncreaseLoRaParams, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelFontSizeIncreaseLoRaParams, "+");
    lv_obj_set_style_text_color(ui_LabelFontSizeIncreaseLoRaParams, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelFontSizeIncreaseLoRaParams, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelFontSizeIncreaseLoRaParams, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonFontSizeDecreaseLoRaParams = lv_btn_create(ui_PanelPanelLoRaParams);
    lv_obj_set_width(ui_ButtonFontSizeDecreaseLoRaParams, 48);
    lv_obj_set_height(ui_ButtonFontSizeDecreaseLoRaParams, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ButtonFontSizeDecreaseLoRaParams, 6);
    lv_obj_set_y(ui_ButtonFontSizeDecreaseLoRaParams, -170 + 6);
    lv_obj_set_align(ui_ButtonFontSizeDecreaseLoRaParams, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_ButtonFontSizeDecreaseLoRaParams, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonFontSizeDecreaseLoRaParams, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonFontSizeDecreaseLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonFontSizeDecreaseLoRaParams, lv_color_hex(0x5378C1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonFontSizeDecreaseLoRaParams, 164, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ButtonFontSizeDecreaseLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ButtonFontSizeDecreaseLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ButtonFontSizeDecreaseLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ButtonFontSizeDecreaseLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ButtonFontSizeDecreaseLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ButtonFontSizeDecreaseLoRaParams, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ButtonFontSizeDecreaseLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ButtonFontSizeDecreaseLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFontSizeDecreaseLoRaParams = lv_label_create(ui_ButtonFontSizeDecreaseLoRaParams);
    lv_obj_set_width(ui_LabelFontSizeDecreaseLoRaParams, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFontSizeDecreaseLoRaParams, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelFontSizeDecreaseLoRaParams, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelFontSizeDecreaseLoRaParams, "-");
    lv_obj_set_style_text_color(ui_LabelFontSizeDecreaseLoRaParams, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelFontSizeDecreaseLoRaParams, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelFontSizeDecreaseLoRaParams, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelDialogLoRaParams = lv_obj_create(ui_PanelPanelLoRaParams);
    lv_obj_set_width(ui_PanelDialogLoRaParams, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PanelDialogLoRaParams, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PanelDialogLoRaParams, 0);
    lv_obj_set_y(ui_PanelDialogLoRaParams, 46 + 6 / 2);
    lv_obj_set_align(ui_PanelDialogLoRaParams, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelDialogLoRaParams, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_PanelDialogLoRaParams, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_dir(ui_PanelDialogLoRaParams, LV_DIR_VER);
    lv_obj_set_style_radius(ui_PanelDialogLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelDialogLoRaParams, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelDialogLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelDialogLoRaParams, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelDialogLoRaParams, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelDialogLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelDialogLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelDialogLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelDialogLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelDialogLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelDialogLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_PanelDialogLoRaParams, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelDialogLoRaParams, 3, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelDialogLoRaParams, 10, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelDialogLoRaParams, 10, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_TextAreaDialogLoRaParams = lv_textarea_create(ui_PanelDialogLoRaParams);
    lv_obj_set_width(ui_TextAreaDialogLoRaParams, 672);
    lv_obj_set_height(ui_TextAreaDialogLoRaParams, 372 - 6);
    lv_obj_set_align(ui_TextAreaDialogLoRaParams, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextAreaDialogLoRaParams, "");
    lv_textarea_set_placeholder_text(ui_TextAreaDialogLoRaParams,
                                     "Waiting for firmware recognition to succeed");
    lv_obj_add_flag(ui_TextAreaDialogLoRaParams, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TextAreaDialogLoRaParams,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_set_scrollbar_mode(ui_TextAreaDialogLoRaParams, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_dir(ui_TextAreaDialogLoRaParams, LV_DIR_VER);
    lv_obj_set_style_text_color(ui_TextAreaDialogLoRaParams, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextAreaDialogLoRaParams, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextAreaDialogLoRaParams, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_TextAreaDialogLoRaParams, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextAreaDialogLoRaParams, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextAreaDialogLoRaParams, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_TextAreaDialogLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_TextAreaDialogLoRaParams, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_TextAreaDialogLoRaParams, LV_GRAD_DIR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TextAreaDialogLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_TextAreaDialogLoRaParams, lv_color_hex(0x7DFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_TextAreaDialogLoRaParams, 32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_TextAreaDialogLoRaParams, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_TextAreaDialogLoRaParams, 0, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_set_style_text_color(ui_TextAreaDialogLoRaParams, lv_color_hex(0x808080),
                                LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextAreaDialogLoRaParams, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_TextAreaDialogLoRaParams, 1, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_TextAreaDialogLoRaParams, 0, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TextAreaDialogLoRaParams, LV_TEXT_ALIGN_CENTER,
                                LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_TextAreaDialogLoRaParams, LV_TEXT_DECOR_NONE,
                                LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextAreaDialogLoRaParams, &lv_font_montserrat_14,
                               LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ContainerHomePageLoRaParams, ui_event_ContainerHomePageLoRaParams, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ContainerSettingPageLoRaParams, ui_event_ContainerSettingPageLoRaParams, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonFwDetectLoRaParams, ui_event_ButtonFwDetectLoRaParams, LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb(ui_ButtonGetLA66ConfigLoRaParams, ui_event_ButtonGetLA66ConfigLoRaParams, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DropdownFontSizeLoRaParams, ui_event_DropdownFontSizeLoRaParams, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonLoRaWANNetworkActivateLoRaParams, ui_event_ButtonLoRaWANNetworkActivateLoRaParams,
                        LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonFontSizeIncreaseLoRaParams, ui_event_ButtonFontSizeIncreaseLoRaParams, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonFontSizeDecreaseLoRaParams, ui_event_ButtonFontSizeDecreaseLoRaParams, LV_EVENT_ALL, NULL);

}
