// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_BUTTON_H
#define _UI_BUTTON_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_button_events.h"


extern lv_obj_t * ui_PanelSensorButton;
void ui_event_PanelSensorNodeButton_1(lv_event_t * e);
void ui_event_PanelSensorNodeButton_2(lv_event_t * e);
extern lv_obj_t * ui_PanelSensorNodeButton;
extern lv_obj_t * ui_PanelChartButton;
extern lv_obj_t * ui_ChartDisplayButton;
extern lv_obj_t * ui_LabelTypeButton;
extern lv_obj_t * ui_LabelDevEUIButton;
extern lv_obj_t * ui_LabelNameButton;
extern lv_obj_t * ui_PanelSignalStrengthButton;
extern lv_obj_t * ui_ImageSignalStrengthButton;
void ui_event_SliderSignalStrengthButton(lv_event_t * e);
extern lv_obj_t * ui_SliderSignalStrengthButton;
extern lv_obj_t * ui_LabelSignalStrengthValueButton;
extern lv_obj_t * ui_PanelBatteryButton;
extern lv_obj_t * ui_ImageBatteryButton;
void ui_event_SliderBatteryButton(lv_event_t * e);
extern lv_obj_t * ui_SliderBatteryButton;
extern lv_obj_t * ui_LabelBatteryButton;
extern lv_obj_t * ui_PanelButtonButton;
void ui_event_SwitchButtonButton(lv_event_t * e);
extern lv_obj_t * ui_SwitchButtonButton;
extern lv_obj_t * ui_LabelButtonONButton;
extern lv_obj_t * ui_LabelButtonOFFButton;
extern lv_obj_t * ui_PanelTimePassedButton;
extern lv_obj_t * ui_ImageTimePassedButton;
extern lv_obj_t * ui_LabelTimePassedValueButton;
extern lv_obj_t * ui_PanelTopButton;
void ui_event_ImageButtonTopButton(lv_event_t * e);
extern lv_obj_t * ui_ImageButtonTopButton;
void ui_event_PanelSensorNodeDeleteButton_1(lv_event_t * e);
void ui_event_PanelSensorNodeDeleteButton_2(lv_event_t * e);
extern lv_obj_t * ui_PanelSensorNodeDeleteButton;
void ui_event_ImageDeleteButton(lv_event_t * e);
extern lv_obj_t * ui_ImageDeleteButton;



LV_IMG_DECLARE(ui__temporary_image);
LV_IMG_DECLARE(ui_img_signal_empty_png);    // assets/Signal_Empty.png
LV_IMG_DECLARE(ui_img_signal_full_png);    // assets/Signal_Full.png
LV_IMG_DECLARE(ui_img_battery_empty_png);    // assets/Battery_Empty.png
LV_IMG_DECLARE(ui_img_battery_full_png);    // assets/Battery_Full.png
LV_IMG_DECLARE(ui_img_last_seen_png);    // assets/Last_Seen.png
LV_IMG_DECLARE(ui_img_set_top_png);    // assets/Set_Top.png
LV_IMG_DECLARE(ui_img_cancel_set_top_png);    // assets/Cancel_Set_top.png
LV_IMG_DECLARE(ui_img_delete_png);    // assets/Delete.png



LV_FONT_DECLARE(ui_font_Font12);
LV_FONT_DECLARE(ui_font_Font16);




#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
