// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void PinToTopButton(lv_event_t * e)
{
	// Your code here
}

void UnpinFromTopButton(lv_event_t * e)
{
	// Your code here
}

void DeleteObjectButton(lv_event_t * e)
{
	// Your code here
	panel_all * panel = find_upper_by_SensorPanel(arr_get(),((lv_obj_t *)(e->user_data)));
	size_t index = panel->panel_obj_index;
	deleteElement(arr_get(), index);
}

void ButtonChecked(lv_event_t * e)
{
	// Your code here
	panel_all * panel = find_upper_by_SensorPanel(arr_get(),((lv_obj_t *)(e->user_data)));
	panel->panel_obj.panel_union.button.button_press_flag = true;
	panel->panel_obj.panel_union.button.button_status = true;

	_ui_flag_modify(panel->panel_obj.panel_union.button.ui_LabelButtonONButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
	_ui_flag_modify(panel->panel_obj.panel_union.button.ui_LabelButtonOFFButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
}

void ButtonUnchecked(lv_event_t * e)
{
	// Your code here
	panel_all * panel = find_upper_by_SensorPanel(arr_get(),((lv_obj_t *)(e->user_data)));
	panel->panel_obj.panel_union.button.button_press_flag = true;
	panel->panel_obj.panel_union.button.button_status = false;

	_ui_flag_modify(panel->panel_obj.panel_union.button.ui_LabelButtonONButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
	_ui_flag_modify(panel->panel_obj.panel_union.button.ui_LabelButtonOFFButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
}
