// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

#include "ui_button.h"
#include "../sort.h"

///////////////////// VARIABLES ////////////////////


lv_obj_t * ui_PanelSensorButton;
void ui_event_PanelSensorNodeButton(lv_event_t * e);
lv_obj_t * ui_PanelSensorNodeButton;
lv_obj_t * ui_PanelChartButton;
lv_obj_t * ui_ChartDisplayButton;
lv_obj_t * ui_LabelTypeButton;
lv_obj_t * ui_LabelFportButton;
lv_obj_t * ui_LabelDevEUIButton;
lv_obj_t * ui_LabelNameButton;
lv_obj_t * ui_PanelSignalStrengthButton;
lv_obj_t * ui_ImageSignalStrengthButton;
void ui_event_SliderSignalStrengthButton(lv_event_t * e);
lv_obj_t * ui_SliderSignalStrengthButton;
lv_obj_t * ui_LabelSignalStrengthValueButton;
lv_obj_t * ui_PanelBatteryButton;
lv_obj_t * ui_ImageBatteryButton;
void ui_event_SliderBatteryButton(lv_event_t * e);
lv_obj_t * ui_SliderBatteryButton;
lv_obj_t * ui_LabelBatteryButton;
lv_obj_t * ui_PanelButtonButton;
void ui_event_SwitchButtonButton(lv_event_t * e);
lv_obj_t * ui_SwitchButtonButton;
lv_obj_t * ui_LabelButtonONButton;
lv_obj_t * ui_LabelButtonOFFButton;
lv_obj_t * ui_PanelTimePassedButton;
lv_obj_t * ui_ImageTimePassedButton;
lv_obj_t * ui_LabelTimePassedValueButton;
lv_obj_t * ui_PanelTopButton;
void ui_event_ImageButtonTopButton(lv_event_t * e);
lv_obj_t * ui_ImageButtonTopButton;
void ui_event_PanelSensorNodeDeleteButton(lv_event_t * e);
lv_obj_t * ui_PanelSensorNodeDeleteButton;
void ui_event_ImageDeleteButton(lv_event_t * e);
lv_obj_t * ui_ImageDeleteButton;


///////////////////// FUNCTIONS ////////////////////
void ui_event_PanelSensorNodeButton_1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        // _ui_flag_modify(ui_PanelSensorNodeDeleteButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        // _ui_flag_modify(ui_PanelSensorNodeButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify( ((lv_obj_t *)(e->user_data)), LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_PanelSensorNodeButton_2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {   
        _ui_flag_modify( ((lv_obj_t *)(e->user_data)), LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_SliderSignalStrengthButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_LabelSignalStrengthValueButton, target, "Rssi: ", "");
    }
}
void ui_event_SliderBatteryButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_LabelBatteryButton, target, "", "mV");
    }
}
void ui_event_SwitchButtonButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        ButtonChecked(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        ButtonUnchecked(e);
    }
}
void ui_event_ImageButtonTopButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        // PinToTopButton(e);
        reposArray1(arr_get(), ((lv_obj_t *)(e->user_data)));
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        // UnpinFromTopButton(e);
        reposArray2(arr_get(), ((lv_obj_t *)(e->user_data)));
    }
}
void ui_event_PanelSensorNodeDeleteButton_1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        // _ui_flag_modify(ui_PanelSensorNodeDeleteButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        // _ui_flag_modify(ui_PanelSensorNodeButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify( ((lv_obj_t *)(e->user_data)), LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_PanelSensorNodeDeleteButton_2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify( ((lv_obj_t *)(e->user_data)), LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_ImageDeleteButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        DeleteObjectButton(e);
    }
}
