// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_BUTTON_EVENTS_H
#define _UI_BUTTON_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void PinToTopButton(lv_event_t * e);
void UnpinFromTopButton(lv_event_t * e);
void DeleteObjectButton(lv_event_t * e);
void ButtonChecked(lv_event_t * e);
void ButtonUnchecked(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
