// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"
#include "ui_tem_hum.h"
#include "../sort.h"

lv_obj_t * ui_PanelSensorTemHum;
void ui_event_PanelSensorNodeTemHum_1(lv_event_t * e);
void ui_event_PanelSensorNodeTemHum_2(lv_event_t * e);
lv_obj_t * ui_PanelSensorNodeTemHum;
lv_obj_t * ui_PanelChartTemHum;
lv_obj_t * ui_ChartDisplayTemHum;
lv_obj_t * ui_LabelTypeTemHum;
lv_obj_t * ui_LabelDevEUITemHum;
lv_obj_t * ui_LabelNameTemHum;
lv_obj_t * ui_PanelSignalStrengthTemHum;
lv_obj_t * ui_ImageSignalStrengthTemHum;
void ui_event_SliderSignalStrengthTemHum(lv_event_t * e);
lv_obj_t * ui_SliderSignalStrengthTemHum;
lv_obj_t * ui_LabelSignalStrengthValueTemHum;
lv_obj_t * ui_PanelBatteryTemHum;
lv_obj_t * ui_ImageBatteryTemHum;
void ui_event_SliderBatteryTemHum(lv_event_t * e);
lv_obj_t * ui_SliderBatteryTemHum;
lv_obj_t * ui_LabelBatteryTemHum;
lv_obj_t * ui_PanelTemTemHum;
lv_obj_t * ui_LabelTemTemHum;
lv_obj_t * ui_LabelTemValueTemHum;
lv_obj_t * ui_PanelHumTemHum;
lv_obj_t * ui_LabelHumTemHum;
lv_obj_t * ui_LabelHumValueTemHum;
lv_obj_t * ui_PanelExtTemHum;
lv_obj_t * ui_LabelExtTemHum;
lv_obj_t * ui_LabelExtValueTemHum;
lv_obj_t * ui_PanelTimePassedTemHum;
lv_obj_t * ui_ImageTimePassedTemHum;
lv_obj_t * ui_LabelTimePassedValueTemHum;
lv_obj_t * ui_PanelTopTemHum;
void ui_event_ImageButtonTopTemHum(lv_event_t * e);
lv_obj_t * ui_ImageButtonTopTemHum;
void ui_event_PanelSensorNodeDeleteTemHum_1(lv_event_t * e);
void ui_event_PanelSensorNodeDeleteTemHum_2(lv_event_t * e);
lv_obj_t * ui_PanelSensorNodeDeleteTemHum;
void ui_event_ImageDeleteTemHum(lv_event_t * e);
lv_obj_t * ui_ImageDeleteTemHum;


///////////////////// FUNCTIONS ////////////////////
void ui_event_PanelSensorNodeTemHum_1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        // _ui_flag_modify(ui_PanelSensorNodeTemHum, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify( ((lv_obj_t *)(e->user_data)), LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        
    }
}
void ui_event_PanelSensorNodeTemHum_2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        // _ui_flag_modify(ui_PanelSensorNodeDeleteTemHum, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify( ((lv_obj_t *)(e->user_data)), LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_SliderSignalStrengthTemHum(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_LabelSignalStrengthValueTemHum, target, "Rssi: ", "");
    }
}
void ui_event_SliderBatteryTemHum(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_LabelBatteryTemHum, target, "", "mV");
    }
}
void ui_event_ImageButtonTopTemHum(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        // PinToTopTemHum(e);
        reposArray1(arr_get(), ((lv_obj_t *)(e->user_data)));
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        // UnpinFromTopTemHum(e);
        reposArray2(arr_get(), ((lv_obj_t *)(e->user_data)));
    }
}
void ui_event_PanelSensorNodeDeleteTemHum_1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        // _ui_flag_modify(ui_PanelSensorNodeDeleteTemHum, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        // _ui_flag_modify(ui_PanelSensorNodeTemHum, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify( ((lv_obj_t *)(e->user_data)), LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_PanelSensorNodeDeleteTemHum_2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify( ((lv_obj_t *)(e->user_data)), LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_ImageDeleteTemHum(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        DeleteObjectTemHum(e);
    }
}
