// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_TEM_HUM_H
#define _UI_TEM_HUM_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_tem_hum_events.h"


extern lv_obj_t * ui_PanelSensorTemHum;
void ui_event_PanelSensorNodeTemHum_1(lv_event_t * e);
void ui_event_PanelSensorNodeTemHum_2(lv_event_t * e);
extern lv_obj_t * ui_PanelSensorNodeTemHum;
extern lv_obj_t * ui_PanelChartTemHum;
extern lv_obj_t * ui_ChartDisplayTemHum;
extern lv_obj_t * ui_LabelTypeTemHum;
extern lv_obj_t * ui_LabelFportTemHum;
extern lv_obj_t * ui_LabelDevEUITemHum;
extern lv_obj_t * ui_LabelNameTemHum;
extern lv_obj_t * ui_PanelSignalStrengthTemHum;
extern lv_obj_t * ui_ImageSignalStrengthTemHum;
void ui_event_SliderSignalStrengthTemHum(lv_event_t * e);
extern lv_obj_t * ui_SliderSignalStrengthTemHum;
extern lv_obj_t * ui_LabelSignalStrengthValueTemHum;
extern lv_obj_t * ui_PanelBatteryTemHum;
extern lv_obj_t * ui_ImageBatteryTemHum;
void ui_event_SliderBatteryTemHum(lv_event_t * e);
extern lv_obj_t * ui_SliderBatteryTemHum;
extern lv_obj_t * ui_LabelBatteryTemHum;
extern lv_obj_t * ui_PanelTemTemHum;
extern lv_obj_t * ui_LabelTemTemHum;
extern lv_obj_t * ui_LabelTemValueTemHum;
extern lv_obj_t * ui_PanelHumTemHum;
extern lv_obj_t * ui_LabelHumTemHum;
extern lv_obj_t * ui_LabelHumValueTemHum;
extern lv_obj_t * ui_PanelExtTemHum;
extern lv_obj_t * ui_LabelExtTemHum;
extern lv_obj_t * ui_LabelExtValueTemHum;
extern lv_obj_t * ui_PanelTimePassedTemHum;
extern lv_obj_t * ui_ImageTimePassedTemHum;
extern lv_obj_t * ui_LabelTimePassedValueTemHum;
extern lv_obj_t * ui_PanelTopTemHum;
void ui_event_ImageButtonTopTemHum(lv_event_t * e);
extern lv_obj_t * ui_ImageButtonTopTemHum;
void ui_event_PanelSensorNodeDeleteTemHum_1(lv_event_t * e);
void ui_event_PanelSensorNodeDeleteTemHum_2(lv_event_t * e);
extern lv_obj_t * ui_PanelSensorNodeDeleteTemHum;
void ui_event_ImageDeleteTemHum(lv_event_t * e);
extern lv_obj_t * ui_ImageDeleteTemHum;


LV_IMG_DECLARE(ui__temporary_image);
LV_IMG_DECLARE(ui_img_signal_empty_png);    // assets/Signal_Empty.png
LV_IMG_DECLARE(ui_img_signal_full_png);    // assets/Signal_Full.png
LV_IMG_DECLARE(ui_img_battery_empty_png);    // assets/Battery_Empty.png
LV_IMG_DECLARE(ui_img_battery_full_png);    // assets/Battery_Full.png
LV_IMG_DECLARE(ui_img_last_seen_png);    // assets/Last_Seen.png
LV_IMG_DECLARE(ui_img_set_top_png);    // assets/Set_Top.png
LV_IMG_DECLARE(ui_img_cancel_set_top_png);    // assets/Cancel_Set_Top.png
LV_IMG_DECLARE(ui_img_delete_png);    // assets/Delete.png


LV_FONT_DECLARE(ui_font_Font12);
LV_FONT_DECLARE(ui_font_Font16);


#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
