// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_TEM_HUM_EVENTS_H
#define _UI_TEM_HUM_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void PinToTopTemHum(lv_event_t * e);
void UnpinFromTopTemHum(lv_event_t * e);
void DeleteObjectTemHum(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
