// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui_alarm.h"
#include "../../sort.h"
#include "ui.h"

panel_with_type create_alarm(uint8_t index, lv_obj_t *parent)
{
    ui_PanelSensorAlarm = lv_obj_create(parent);
    lv_obj_set_width(ui_PanelSensorAlarm, 156);
    lv_obj_set_height(ui_PanelSensorAlarm, 160);
    lv_obj_set_x(ui_PanelSensorAlarm, -85);
    lv_obj_set_y(ui_PanelSensorAlarm, -90);
    lv_obj_set_align(ui_PanelSensorAlarm, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSensorAlarm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSensorAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSensorAlarm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSensorAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSensorAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSensorNodeAlarm = lv_obj_create(ui_PanelSensorAlarm);
    lv_obj_set_width(ui_PanelSensorNodeAlarm, 156);
    lv_obj_set_height(ui_PanelSensorNodeAlarm, 160);
    lv_obj_set_align(ui_PanelSensorNodeAlarm, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSensorNodeAlarm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSensorNodeAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSensorNodeAlarm, lv_color_hex(0x162137), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSensorNodeAlarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSensorNodeAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelChartAlarm = lv_obj_create(ui_PanelSensorNodeAlarm);
    lv_obj_set_width(ui_PanelChartAlarm, 156);
    lv_obj_set_height(ui_PanelChartAlarm, 50);
    lv_obj_set_x(ui_PanelChartAlarm, 0);
    lv_obj_set_y(ui_PanelChartAlarm, -56);
    lv_obj_set_align(ui_PanelChartAlarm, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelChartAlarm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelChartAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelChartAlarm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelChartAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelChartAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChartDisplayAlarm = lv_chart_create(ui_PanelChartAlarm);
    lv_obj_set_width(ui_ChartDisplayAlarm, 156);
    lv_obj_set_height(ui_ChartDisplayAlarm, 50);
    lv_obj_set_align(ui_ChartDisplayAlarm, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ChartDisplayAlarm, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_chart_set_type(ui_ChartDisplayAlarm, LV_CHART_TYPE_NONE);
    lv_chart_set_range(ui_ChartDisplayAlarm, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_chart_set_div_line_count(ui_ChartDisplayAlarm, 0, 0);
    lv_chart_set_axis_tick(ui_ChartDisplayAlarm, LV_CHART_AXIS_PRIMARY_X, 0, 0, 0, 0, false, 50);
    lv_chart_set_axis_tick(ui_ChartDisplayAlarm, LV_CHART_AXIS_PRIMARY_Y, 0, 0, 0, 0, false, 100);
    lv_chart_set_axis_tick(ui_ChartDisplayAlarm, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);
    lv_chart_series_t * ui_ChartDisplayAlarm_series_1 = lv_chart_add_series(ui_ChartDisplayAlarm, lv_color_hex(0xFFFFFF),
                                                                            LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_ChartDisplayAlarm_series_1_array[] = { 0, 10, 20, 50, 80, 90, 40, 20, 40, 0 };
    lv_chart_set_ext_y_array(ui_ChartDisplayAlarm, ui_ChartDisplayAlarm_series_1, ui_ChartDisplayAlarm_series_1_array);
    lv_obj_set_style_radius(ui_ChartDisplayAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ChartDisplayAlarm, lv_color_hex(0xA53811), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChartDisplayAlarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ChartDisplayAlarm, lv_color_hex(0x090301), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_ChartDisplayAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_ChartDisplayAlarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ChartDisplayAlarm, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_ChartDisplayAlarm, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ChartDisplayAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_line_color(ui_ChartDisplayAlarm, lv_color_hex(0x2121E2), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_ChartDisplayAlarm, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(ui_ChartDisplayAlarm, 2, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_set_style_line_width(ui_ChartDisplayAlarm, 2, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_LabelTypeAlarm = lv_label_create(ui_ChartDisplayAlarm);
    lv_obj_set_width(ui_LabelTypeAlarm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTypeAlarm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTypeAlarm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTypeAlarm, "Alarm");
    lv_obj_set_style_text_color(ui_LabelTypeAlarm, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTypeAlarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTypeAlarm, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDevEUIAlarm = lv_label_create(ui_PanelSensorNodeAlarm);
    lv_obj_set_width(ui_LabelDevEUIAlarm, 80);   /// 1  LV_SIZE_CONTENT
    lv_obj_set_height(ui_LabelDevEUIAlarm, 16);    /// 1  LV_SIZE_CONTENT
    lv_obj_set_x(ui_LabelDevEUIAlarm, -35);
    lv_obj_set_y(ui_LabelDevEUIAlarm, -20);
    lv_obj_set_align(ui_LabelDevEUIAlarm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDevEUIAlarm, "ABCDEF");
    lv_obj_set_style_text_color(ui_LabelDevEUIAlarm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDevEUIAlarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDevEUIAlarm, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelDevEUIAlarm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelDevEUIAlarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LabelDevEUIAlarm, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_LabelDevEUIAlarm, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelDevEUIAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelDevEUIAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelDevEUIAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelDevEUIAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_LabelDevEUIAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_LabelDevEUIAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNameAlarm = lv_label_create(ui_PanelSensorNodeAlarm);
    lv_obj_set_width(ui_LabelNameAlarm, 65);
    lv_obj_set_height(ui_LabelNameAlarm, 32);
    lv_obj_set_x(ui_LabelNameAlarm, -16);
    lv_obj_set_y(ui_LabelNameAlarm, 57);
    lv_label_set_long_mode(ui_LabelNameAlarm, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_LabelNameAlarm, "0123456789ABCDEF");
    lv_obj_set_style_text_color(ui_LabelNameAlarm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelNameAlarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNameAlarm, &ui_font_Font12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelNameAlarm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelNameAlarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LabelNameAlarm, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_LabelNameAlarm, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSignalStrengthAlarm = lv_obj_create(ui_PanelSensorNodeAlarm);
    lv_obj_set_width(ui_PanelSignalStrengthAlarm, 72);
    lv_obj_set_height(ui_PanelSignalStrengthAlarm, 16);
    lv_obj_set_x(ui_PanelSignalStrengthAlarm, 39);
    lv_obj_set_y(ui_PanelSignalStrengthAlarm, -20);
    lv_obj_set_align(ui_PanelSignalStrengthAlarm, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelSignalStrengthAlarm, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_PanelSignalStrengthAlarm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSignalStrengthAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSignalStrengthAlarm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSignalStrengthAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSignalStrengthAlarm, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelSignalStrengthAlarm, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelSignalStrengthAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelSignalStrengthAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelSignalStrengthAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelSignalStrengthAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelSignalStrengthAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelSignalStrengthAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageSignalStrengthAlarm = lv_img_create(ui_PanelSignalStrengthAlarm);
    lv_img_set_src(ui_ImageSignalStrengthAlarm, &ui_img_signal_empty_png);
    lv_obj_set_width(ui_ImageSignalStrengthAlarm, 24);
    lv_obj_set_height(ui_ImageSignalStrengthAlarm, 16);
    lv_obj_set_x(ui_ImageSignalStrengthAlarm, -23);
    lv_obj_set_y(ui_ImageSignalStrengthAlarm, 0);
    lv_obj_set_align(ui_ImageSignalStrengthAlarm, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageSignalStrengthAlarm, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageSignalStrengthAlarm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_ImageSignalStrengthAlarm, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ImageSignalStrengthAlarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderSignalStrengthAlarm = lv_slider_create(ui_PanelSignalStrengthAlarm);
    lv_slider_set_range(ui_SliderSignalStrengthAlarm, -128, 16);
    lv_slider_set_value(ui_SliderSignalStrengthAlarm, -60, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderSignalStrengthAlarm) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_SliderSignalStrengthAlarm, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderSignalStrengthAlarm, 24);
    lv_obj_set_height(ui_SliderSignalStrengthAlarm, 16);
    lv_obj_set_x(ui_SliderSignalStrengthAlarm, -23);
    lv_obj_set_y(ui_SliderSignalStrengthAlarm, 0);
    lv_obj_set_align(ui_SliderSignalStrengthAlarm, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SliderSignalStrengthAlarm, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_radius(ui_SliderSignalStrengthAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderSignalStrengthAlarm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSignalStrengthAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderSignalStrengthAlarm, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderSignalStrengthAlarm, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSignalStrengthAlarm, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SliderSignalStrengthAlarm, &ui_img_signal_full_png,
                                LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderSignalStrengthAlarm, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderSignalStrengthAlarm, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSignalStrengthAlarm, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelSignalStrengthValueAlarm = lv_label_create(ui_PanelSignalStrengthAlarm);
    lv_obj_set_width(ui_LabelSignalStrengthValueAlarm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSignalStrengthValueAlarm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSignalStrengthValueAlarm, 13);
    lv_obj_set_y(ui_LabelSignalStrengthValueAlarm, 0);
    lv_obj_set_align(ui_LabelSignalStrengthValueAlarm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSignalStrengthValueAlarm, "Rssi: -80");
    lv_obj_set_style_text_color(ui_LabelSignalStrengthValueAlarm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSignalStrengthValueAlarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSignalStrengthValueAlarm, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelBatteryAlarm = lv_obj_create(ui_PanelSensorNodeAlarm);
    lv_obj_set_width(ui_PanelBatteryAlarm, 74);
    lv_obj_set_height(ui_PanelBatteryAlarm, 16);
    lv_obj_set_x(ui_PanelBatteryAlarm, 39);
    lv_obj_set_y(ui_PanelBatteryAlarm, 1);
    lv_obj_set_align(ui_PanelBatteryAlarm, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelBatteryAlarm, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_PanelBatteryAlarm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelBatteryAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelBatteryAlarm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelBatteryAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelBatteryAlarm, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelBatteryAlarm, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelBatteryAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelBatteryAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelBatteryAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelBatteryAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelBatteryAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelBatteryAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageBatteryAlarm = lv_img_create(ui_PanelBatteryAlarm);
    lv_img_set_src(ui_ImageBatteryAlarm, &ui_img_battery_empty_png);
    lv_obj_set_width(ui_ImageBatteryAlarm, 25);
    lv_obj_set_height(ui_ImageBatteryAlarm, 15);
    lv_obj_set_x(ui_ImageBatteryAlarm, -25);
    lv_obj_set_y(ui_ImageBatteryAlarm, 0);
    lv_obj_set_align(ui_ImageBatteryAlarm, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageBatteryAlarm, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageBatteryAlarm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SliderBatteryAlarm = lv_slider_create(ui_PanelBatteryAlarm);
    lv_slider_set_range(ui_SliderBatteryAlarm, 2000, 4200);
    lv_slider_set_value(ui_SliderBatteryAlarm, 3700, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderBatteryAlarm) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderBatteryAlarm, 0,
                                                                                                       LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderBatteryAlarm, 25);
    lv_obj_set_height(ui_SliderBatteryAlarm, 15);
    lv_obj_set_x(ui_SliderBatteryAlarm, -25);
    lv_obj_set_y(ui_SliderBatteryAlarm, 0);
    lv_obj_set_align(ui_SliderBatteryAlarm, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SliderBatteryAlarm, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_radius(ui_SliderBatteryAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderBatteryAlarm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderBatteryAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderBatteryAlarm, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderBatteryAlarm, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderBatteryAlarm, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SliderBatteryAlarm, &ui_img_battery_full_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderBatteryAlarm, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderBatteryAlarm, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderBatteryAlarm, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelBatteryAlarm = lv_label_create(ui_PanelBatteryAlarm);
    lv_obj_set_width(ui_LabelBatteryAlarm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBatteryAlarm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBatteryAlarm, 14);
    lv_obj_set_y(ui_LabelBatteryAlarm, 0);
    lv_obj_set_align(ui_LabelBatteryAlarm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBatteryAlarm, "3700mV");
    lv_obj_set_style_text_color(ui_LabelBatteryAlarm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBatteryAlarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBatteryAlarm, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelAlarmAlarm = lv_obj_create(ui_PanelSensorNodeAlarm);
    lv_obj_set_width(ui_PanelAlarmAlarm, 48);
    lv_obj_set_height(ui_PanelAlarmAlarm, 42);
    lv_obj_set_x(ui_PanelAlarmAlarm, 27);
    lv_obj_set_y(ui_PanelAlarmAlarm, 37);
    lv_obj_set_align(ui_PanelAlarmAlarm, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelAlarmAlarm, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_PanelAlarmAlarm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelAlarmAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelAlarmAlarm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelAlarmAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelAlarmAlarm, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelAlarmAlarm, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageAlarmAlarm = lv_img_create(ui_PanelAlarmAlarm);
    lv_img_set_src(ui_ImageAlarmAlarm, &ui_img_alarm_png);
    lv_obj_set_width(ui_ImageAlarmAlarm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageAlarmAlarm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageAlarmAlarm, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageAlarmAlarm, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageAlarmAlarm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_ImageAlarmAlarm, lv_color_hex(0x3C2626), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ImageAlarmAlarm, 128, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTimePassedAlarm = lv_obj_create(ui_PanelSensorNodeAlarm);
    lv_obj_set_width(ui_PanelTimePassedAlarm, 128);
    lv_obj_set_height(ui_PanelTimePassedAlarm, 20);
    lv_obj_set_x(ui_PanelTimePassedAlarm, -14);
    lv_obj_set_y(ui_PanelTimePassedAlarm, 70);
    lv_obj_set_align(ui_PanelTimePassedAlarm, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelTimePassedAlarm, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_PanelTimePassedAlarm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelTimePassedAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelTimePassedAlarm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTimePassedAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelTimePassedAlarm, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelTimePassedAlarm, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelTimePassedAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelTimePassedAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelTimePassedAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelTimePassedAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageTimePassedAlarm = lv_img_create(ui_PanelTimePassedAlarm);
    lv_img_set_src(ui_ImageTimePassedAlarm, &ui_img_last_seen_png);
    lv_obj_set_width(ui_ImageTimePassedAlarm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageTimePassedAlarm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageTimePassedAlarm, 1);
    lv_obj_set_y(ui_ImageTimePassedAlarm, 0);
    lv_obj_add_flag(ui_ImageTimePassedAlarm, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageTimePassedAlarm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ImageTimePassedAlarm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ImageTimePassedAlarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ImageTimePassedAlarm, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ImageTimePassedAlarm, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTimePassedValueAlarm = lv_label_create(ui_PanelTimePassedAlarm);
    lv_obj_set_width(ui_LabelTimePassedValueAlarm, 103);
    lv_obj_set_height(ui_LabelTimePassedValueAlarm, 16);
    lv_obj_set_x(ui_LabelTimePassedValueAlarm, 22);
    lv_obj_set_y(ui_LabelTimePassedValueAlarm, 1);
    lv_label_set_text(ui_LabelTimePassedValueAlarm, "00: 00: 00: 00");
    lv_obj_set_style_text_color(ui_LabelTimePassedValueAlarm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTimePassedValueAlarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTimePassedValueAlarm, &ui_font_Font12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelTimePassedValueAlarm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelTimePassedValueAlarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LabelTimePassedValueAlarm, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_LabelTimePassedValueAlarm, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTopAlarm = lv_obj_create(ui_PanelSensorNodeAlarm);
    lv_obj_set_width(ui_PanelTopAlarm, LV_SIZE_CONTENT);   /// 27
    lv_obj_set_height(ui_PanelTopAlarm, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_PanelTopAlarm, 65);
    lv_obj_set_y(ui_PanelTopAlarm, 67);
    lv_obj_set_align(ui_PanelTopAlarm, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelTopAlarm, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelTopAlarm, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelTopAlarm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelTopAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelTopAlarm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTopAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelTopAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelTopAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelTopAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelTopAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelTopAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelTopAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelTopAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageButtonTopAlarm = lv_imgbtn_create(ui_PanelTopAlarm);
    lv_imgbtn_set_src(ui_ImageButtonTopAlarm, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_set_top_png, NULL);
    lv_imgbtn_set_src(ui_ImageButtonTopAlarm, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_cancel_set_top_png, NULL);
    lv_imgbtn_set_src(ui_ImageButtonTopAlarm, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImageButtonTopAlarm, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_set_top_png, NULL);
    lv_imgbtn_set_src(ui_ImageButtonTopAlarm, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_cancel_set_top_png, NULL);
    lv_imgbtn_set_src(ui_ImageButtonTopAlarm, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImageButtonTopAlarm, 25);
    lv_obj_set_height(ui_ImageButtonTopAlarm, 25);
    lv_obj_set_x(ui_ImageButtonTopAlarm, 0);
    lv_obj_set_y(ui_ImageButtonTopAlarm, 1);
    lv_obj_add_flag(ui_ImageButtonTopAlarm, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_border_color(ui_ImageButtonTopAlarm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ImageButtonTopAlarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ImageButtonTopAlarm, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ImageButtonTopAlarm, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_ImageButtonTopAlarm, lv_color_hex(0x4BD5CB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ImageButtonTopAlarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSensorNodeDeleteAlarm = lv_obj_create(ui_PanelSensorAlarm);
    lv_obj_set_width(ui_PanelSensorNodeDeleteAlarm, 156);
    lv_obj_set_height(ui_PanelSensorNodeDeleteAlarm, 160);
    lv_obj_set_align(ui_PanelSensorNodeDeleteAlarm, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelSensorNodeDeleteAlarm, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelSensorNodeDeleteAlarm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSensorNodeDeleteAlarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSensorNodeDeleteAlarm, lv_color_hex(0x162137), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSensorNodeDeleteAlarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSensorNodeDeleteAlarm, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelSensorNodeDeleteAlarm, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageDeleteAlarm = lv_img_create(ui_PanelSensorNodeDeleteAlarm);
    lv_img_set_src(ui_ImageDeleteAlarm, &ui_img_delete_png);
    lv_obj_set_width(ui_ImageDeleteAlarm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageDeleteAlarm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageDeleteAlarm, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageDeleteAlarm, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageDeleteAlarm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_transform_zoom(ui_ImageDeleteAlarm, 288, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_add_event_cb(ui_SliderSignalStrengthAlarm, ui_event_SliderSignalStrengthAlarm, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderBatteryAlarm, ui_event_SliderBatteryAlarm, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImageButtonTopAlarm, ui_event_ImageButtonTopAlarm, LV_EVENT_ALL, ui_PanelSensorAlarm);
    lv_obj_add_event_cb(ui_PanelSensorNodeAlarm, ui_event_PanelSensorNodeAlarm_1, LV_EVENT_ALL, ui_PanelSensorNodeAlarm);
    lv_obj_add_event_cb(ui_PanelSensorNodeAlarm, ui_event_PanelSensorNodeAlarm_2, LV_EVENT_ALL, ui_PanelSensorNodeDeleteAlarm);
    lv_obj_add_event_cb(ui_ImageDeleteAlarm, ui_event_ImageDeleteAlarm, LV_EVENT_ALL, ui_PanelSensorAlarm);
    lv_obj_add_event_cb(ui_PanelSensorNodeDeleteAlarm, ui_event_PanelSensorNodeDeleteAlarm_1, LV_EVENT_ALL, ui_PanelSensorNodeAlarm);
    lv_obj_add_event_cb(ui_PanelSensorNodeDeleteAlarm, ui_event_PanelSensorNodeDeleteAlarm_2, LV_EVENT_ALL, ui_PanelSensorNodeDeleteAlarm);

    panel_with_type union_sensor;

    union_sensor.panel_union.alarm.ui_PanelSensorAlarm = ui_PanelSensorAlarm;
    union_sensor.panel_union.alarm.ui_PanelSensorNodeAlarm = ui_PanelSensorNodeAlarm;
    union_sensor.panel_union.alarm.ui_PanelChartAlarm = ui_PanelChartAlarm;
    union_sensor.panel_union.alarm.ui_ChartDisplayAlarm = ui_ChartDisplayAlarm;
    union_sensor.panel_union.alarm.ui_LabelTypeAlarm = ui_LabelTypeAlarm;
    union_sensor.panel_union.alarm.ui_LabelDevEUIAlarm = ui_LabelDevEUIAlarm;
    union_sensor.panel_union.alarm.ui_LabelNameAlarm = ui_LabelNameAlarm;
    union_sensor.panel_union.alarm.ui_PanelSignalStrengthAlarm = ui_PanelSignalStrengthAlarm;
    union_sensor.panel_union.alarm.ui_ImageSignalStrengthAlarm = ui_ImageSignalStrengthAlarm;
    union_sensor.panel_union.alarm.ui_SliderSignalStrengthAlarm = ui_SliderSignalStrengthAlarm;
    union_sensor.panel_union.alarm.ui_LabelSignalStrengthValueAlarm = ui_LabelSignalStrengthValueAlarm;
    union_sensor.panel_union.alarm.ui_PanelBatteryAlarm = ui_PanelBatteryAlarm;
    union_sensor.panel_union.alarm.ui_ImageBatteryAlarm = ui_ImageBatteryAlarm;
    union_sensor.panel_union.alarm.ui_SliderBatteryAlarm = ui_SliderBatteryAlarm;
    union_sensor.panel_union.alarm.ui_LabelBatteryAlarm = ui_LabelBatteryAlarm;
    union_sensor.panel_union.alarm.ui_PanelAlarmAlarm = ui_PanelAlarmAlarm;
    union_sensor.panel_union.alarm.ui_ImageAlarmAlarm = ui_ImageAlarmAlarm;
    union_sensor.panel_union.alarm.ui_PanelTimePassedAlarm = ui_PanelTimePassedAlarm;
    union_sensor.panel_union.alarm.ui_ImageTimePassedAlarm = ui_ImageTimePassedAlarm;
    union_sensor.panel_union.alarm.ui_LabelTimePassedValueAlarm = ui_LabelTimePassedValueAlarm;
    union_sensor.panel_union.alarm.ui_PanelTopAlarm = ui_PanelTopAlarm;
    union_sensor.panel_union.alarm.ui_ImageButtonTopAlarm = ui_ImageButtonTopAlarm;
    union_sensor.panel_union.alarm.ui_PanelSensorNodeDeleteAlarm = ui_PanelSensorNodeDeleteAlarm;
    union_sensor.panel_union.alarm.ui_ImageDeleteAlarm = ui_ImageDeleteAlarm;

    union_sensor.panel_union.alarm.timer_alarm_en_flag = ALARM_TIMER_ENABLE;
    union_sensor.panel_union.alarm.timer_exec_status = ALARM_TIMER_STATUS_OFF;

    union_sensor.panel_type = ALARM_TYPE;

    lv_obj_set_x(union_sensor.panel_union.alarm.ui_PanelSensorAlarm, x_by_index(index));
    lv_obj_set_y(union_sensor.panel_union.alarm.ui_PanelSensorAlarm, y_by_index(index));
    
    return union_sensor;
}
