// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui_button.h"
#include "../../sort.h"
#include "ui.h"

panel_with_type create_button(uint8_t index, lv_obj_t *parent)
{
    ui_PanelSensorButton = lv_obj_create(parent);
    lv_obj_set_width(ui_PanelSensorButton, 156);
    lv_obj_set_height(ui_PanelSensorButton, 160);
    lv_obj_set_x(ui_PanelSensorButton, -85);
    lv_obj_set_y(ui_PanelSensorButton, -90);
    lv_obj_set_align(ui_PanelSensorButton, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSensorButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSensorButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSensorButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSensorButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSensorButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSensorNodeButton = lv_obj_create(ui_PanelSensorButton);
    lv_obj_set_width(ui_PanelSensorNodeButton, 156);
    lv_obj_set_height(ui_PanelSensorNodeButton, 160);
    lv_obj_set_align(ui_PanelSensorNodeButton, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSensorNodeButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSensorNodeButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSensorNodeButton, lv_color_hex(0x162137), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSensorNodeButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSensorNodeButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelChartButton = lv_obj_create(ui_PanelSensorNodeButton);
    lv_obj_set_width(ui_PanelChartButton, 156);
    lv_obj_set_height(ui_PanelChartButton, 50);
    lv_obj_set_x(ui_PanelChartButton, 0);
    lv_obj_set_y(ui_PanelChartButton, -56);
    lv_obj_set_align(ui_PanelChartButton, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelChartButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelChartButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelChartButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelChartButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelChartButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChartDisplayButton = lv_chart_create(ui_PanelChartButton);
    lv_obj_set_width(ui_ChartDisplayButton, 156);
    lv_obj_set_height(ui_ChartDisplayButton, 50);
    lv_obj_clear_flag(ui_ChartDisplayButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_align(ui_ChartDisplayButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ChartDisplayButton, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_chart_set_type(ui_ChartDisplayButton, LV_CHART_TYPE_NONE);
    lv_chart_set_range(ui_ChartDisplayButton, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_chart_set_div_line_count(ui_ChartDisplayButton, 0, 0);
    lv_chart_set_axis_tick(ui_ChartDisplayButton, LV_CHART_AXIS_PRIMARY_X, 0, 0, 0, 0, false, 50);
    lv_chart_set_axis_tick(ui_ChartDisplayButton, LV_CHART_AXIS_PRIMARY_Y, 0, 0, 0, 0, false, 100);
    lv_chart_set_axis_tick(ui_ChartDisplayButton, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);
    lv_chart_series_t * ui_ChartDisplayButton_series_1 = lv_chart_add_series(ui_ChartDisplayButton, lv_color_hex(0xFFFFFF),
                                                                             LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_ChartDisplayButton_series_1_array[] = { 0, 10, 20, 50, 80, 90, 40, 20, 40, 0 };
    lv_chart_set_ext_y_array(ui_ChartDisplayButton, ui_ChartDisplayButton_series_1, ui_ChartDisplayButton_series_1_array);
    lv_obj_set_style_radius(ui_ChartDisplayButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ChartDisplayButton, lv_color_hex(0x86ACD4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChartDisplayButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ChartDisplayButton, lv_color_hex(0x1B221D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_ChartDisplayButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_ChartDisplayButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ChartDisplayButton, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_ChartDisplayButton, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ChartDisplayButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_line_color(ui_ChartDisplayButton, lv_color_hex(0x2121E2), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_ChartDisplayButton, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(ui_ChartDisplayButton, 1, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_set_style_line_width(ui_ChartDisplayButton, 1, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_LabelTypeButton = lv_label_create(ui_ChartDisplayButton);
    lv_obj_set_width(ui_LabelTypeButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTypeButton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTypeButton, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTypeButton, "Button");
    lv_obj_set_style_text_color(ui_LabelTypeButton, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTypeButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTypeButton, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFportButton = lv_label_create(ui_ChartDisplayButton);
    lv_obj_set_width(ui_LabelFportButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFportButton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFportButton, 10);//  5  0  1
    lv_obj_set_y(ui_LabelFportButton, -10);// -5 -7  -12
    lv_obj_set_align(ui_LabelFportButton, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_LabelFportButton, "Fport\n100");//   100   Fport: 100
    lv_obj_set_style_text_align(ui_LabelFportButton, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_LabelFportButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);//0x94AEB4  0x84BE84  0x9370DB  0xE6A8D7 0xFF6B6B
    lv_obj_set_style_text_opa(ui_LabelFportButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);  //192
    lv_obj_set_style_text_font(ui_LabelFportButton, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);//   &lv_font_montserrat_8

    ui_LabelDevEUIButton = lv_label_create(ui_PanelSensorNodeButton);
    lv_obj_set_width(ui_LabelDevEUIButton, 80);   /// 1  LV_SIZE_CONTENT
    lv_obj_set_height(ui_LabelDevEUIButton, 16);    /// 1  LV_SIZE_CONTENT
    lv_obj_set_x(ui_LabelDevEUIButton, -35);
    lv_obj_set_y(ui_LabelDevEUIButton, -16);
    lv_obj_set_align(ui_LabelDevEUIButton, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDevEUIButton, "ABCDEF");
    lv_obj_set_style_text_color(ui_LabelDevEUIButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDevEUIButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDevEUIButton, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelDevEUIButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelDevEUIButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LabelDevEUIButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_LabelDevEUIButton, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelDevEUIButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelDevEUIButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelDevEUIButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelDevEUIButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_LabelDevEUIButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_LabelDevEUIButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNameButton = lv_label_create(ui_PanelSensorNodeButton);
    lv_obj_set_width(ui_LabelNameButton, 66);
    lv_obj_set_height(ui_LabelNameButton, 34);
    lv_obj_set_x(ui_LabelNameButton, -16);
    lv_obj_set_y(ui_LabelNameButton, 56);
    lv_label_set_long_mode(ui_LabelNameButton, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_LabelNameButton, "0123456789ABCDEF");
    lv_obj_set_style_text_color(ui_LabelNameButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelNameButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNameButton, &ui_font_Font12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelNameButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelNameButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LabelNameButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_LabelNameButton, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSignalStrengthButton = lv_obj_create(ui_PanelSensorNodeButton);
    lv_obj_set_width(ui_PanelSignalStrengthButton, 72);
    lv_obj_set_height(ui_PanelSignalStrengthButton, 16);
    lv_obj_set_x(ui_PanelSignalStrengthButton, 40);
    lv_obj_set_y(ui_PanelSignalStrengthButton, -18);
    lv_obj_set_align(ui_PanelSignalStrengthButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelSignalStrengthButton, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_PanelSignalStrengthButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSignalStrengthButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSignalStrengthButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSignalStrengthButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSignalStrengthButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelSignalStrengthButton, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelSignalStrengthButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelSignalStrengthButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelSignalStrengthButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelSignalStrengthButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelSignalStrengthButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelSignalStrengthButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageSignalStrengthButton = lv_img_create(ui_PanelSignalStrengthButton);
    lv_img_set_src(ui_ImageSignalStrengthButton, &ui_img_signal_empty_png);
    lv_obj_set_width(ui_ImageSignalStrengthButton, 24);
    lv_obj_set_height(ui_ImageSignalStrengthButton, 16);
    lv_obj_set_x(ui_ImageSignalStrengthButton, -23);
    lv_obj_set_y(ui_ImageSignalStrengthButton, 0);
    lv_obj_set_align(ui_ImageSignalStrengthButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageSignalStrengthButton, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageSignalStrengthButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_ImageSignalStrengthButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ImageSignalStrengthButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderSignalStrengthButton = lv_slider_create(ui_PanelSignalStrengthButton);
    lv_slider_set_range(ui_SliderSignalStrengthButton, -128, 16);
    lv_slider_set_value(ui_SliderSignalStrengthButton, -60, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderSignalStrengthButton) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_SliderSignalStrengthButton, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderSignalStrengthButton, 24);
    lv_obj_set_height(ui_SliderSignalStrengthButton, 16);
    lv_obj_set_x(ui_SliderSignalStrengthButton, -23);
    lv_obj_set_y(ui_SliderSignalStrengthButton, 0);
    lv_obj_set_align(ui_SliderSignalStrengthButton, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SliderSignalStrengthButton, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_radius(ui_SliderSignalStrengthButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderSignalStrengthButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSignalStrengthButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderSignalStrengthButton, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderSignalStrengthButton, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSignalStrengthButton, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SliderSignalStrengthButton, &ui_img_signal_full_png,
                                LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderSignalStrengthButton, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderSignalStrengthButton, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSignalStrengthButton, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelSignalStrengthValueButton = lv_label_create(ui_PanelSignalStrengthButton);
    lv_obj_set_width(ui_LabelSignalStrengthValueButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSignalStrengthValueButton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSignalStrengthValueButton, 11);
    lv_obj_set_y(ui_LabelSignalStrengthValueButton, 0);
    lv_obj_set_align(ui_LabelSignalStrengthValueButton, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSignalStrengthValueButton, "Rssi: -80");
    lv_obj_set_style_text_color(ui_LabelSignalStrengthValueButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSignalStrengthValueButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSignalStrengthValueButton, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelBatteryButton = lv_obj_create(ui_PanelSensorNodeButton);
    lv_obj_set_width(ui_PanelBatteryButton, 74);
    lv_obj_set_height(ui_PanelBatteryButton, 16);
    lv_obj_set_x(ui_PanelBatteryButton, 38);
    lv_obj_set_y(ui_PanelBatteryButton, 7);
    lv_obj_set_align(ui_PanelBatteryButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelBatteryButton, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_PanelBatteryButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelBatteryButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelBatteryButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelBatteryButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelBatteryButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelBatteryButton, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelBatteryButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelBatteryButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelBatteryButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelBatteryButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelBatteryButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelBatteryButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageBatteryButton = lv_img_create(ui_PanelBatteryButton);
    lv_img_set_src(ui_ImageBatteryButton, &ui_img_battery_empty_png);
    lv_obj_set_width(ui_ImageBatteryButton, 25);
    lv_obj_set_height(ui_ImageBatteryButton, 15);
    lv_obj_set_x(ui_ImageBatteryButton, -23);
    lv_obj_set_y(ui_ImageBatteryButton, 0);
    lv_obj_set_align(ui_ImageBatteryButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageBatteryButton, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageBatteryButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SliderBatteryButton = lv_slider_create(ui_PanelBatteryButton);
    lv_slider_set_range(ui_SliderBatteryButton, 2000, 4200);
    lv_slider_set_value(ui_SliderBatteryButton, 3700, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderBatteryButton) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderBatteryButton,
                                                                                                        0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderBatteryButton, 25);
    lv_obj_set_height(ui_SliderBatteryButton, 15);
    lv_obj_set_x(ui_SliderBatteryButton, -23);
    lv_obj_set_y(ui_SliderBatteryButton, 0);
    lv_obj_set_align(ui_SliderBatteryButton, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SliderBatteryButton, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_radius(ui_SliderBatteryButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderBatteryButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderBatteryButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderBatteryButton, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderBatteryButton, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderBatteryButton, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SliderBatteryButton, &ui_img_battery_full_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderBatteryButton, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderBatteryButton, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderBatteryButton, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelBatteryButton = lv_label_create(ui_PanelBatteryButton);
    lv_obj_set_width(ui_LabelBatteryButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBatteryButton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBatteryButton, 14);
    lv_obj_set_y(ui_LabelBatteryButton, 0);
    lv_obj_set_align(ui_LabelBatteryButton, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBatteryButton, "3700mV");
    lv_obj_set_style_text_color(ui_LabelBatteryButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBatteryButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBatteryButton, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelButtonButton = lv_obj_create(ui_PanelSensorNodeButton);
    lv_obj_set_width(ui_PanelButtonButton, 118);
    lv_obj_set_height(ui_PanelButtonButton, 29);
    lv_obj_set_x(ui_PanelButtonButton, 0);
    lv_obj_set_y(ui_PanelButtonButton, 43);
    lv_obj_set_align(ui_PanelButtonButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelButtonButton, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_PanelButtonButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelButtonButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelButtonButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelButtonButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelButtonButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelButtonButton, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchButtonButton = lv_switch_create(ui_PanelButtonButton);
    lv_obj_set_width(ui_SwitchButtonButton, 41);
    lv_obj_set_height(ui_SwitchButtonButton, 18);
    lv_obj_set_x(ui_SwitchButtonButton, -28);
    lv_obj_set_y(ui_SwitchButtonButton, 0);
    lv_obj_set_align(ui_SwitchButtonButton, LV_ALIGN_CENTER);
    // lv_obj_clear_flag(ui_SwitchButtonButton, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SwitchButtonButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchButtonButton, 128, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SwitchButtonButton, lv_color_hex(0x048C10), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_SwitchButtonButton, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_LabelButtonONButton = lv_label_create(ui_PanelButtonButton);
    lv_obj_set_width(ui_LabelButtonONButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelButtonONButton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelButtonONButton, 36);
    lv_obj_set_y(ui_LabelButtonONButton, 0);
    lv_obj_set_align(ui_LabelButtonONButton, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelButtonONButton, "ON");
    lv_obj_add_flag(ui_LabelButtonONButton, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelButtonONButton, lv_color_hex(0x0AC657), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelButtonONButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelButtonONButton, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelButtonOFFButton = lv_label_create(ui_PanelButtonButton);
    lv_obj_set_width(ui_LabelButtonOFFButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelButtonOFFButton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelButtonOFFButton, 36);
    lv_obj_set_y(ui_LabelButtonOFFButton, 0);
    lv_obj_set_align(ui_LabelButtonOFFButton, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelButtonOFFButton, "OFF");
    lv_obj_set_style_text_color(ui_LabelButtonOFFButton, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelButtonOFFButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelButtonOFFButton, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTimePassedButton = lv_obj_create(ui_PanelSensorNodeButton);
    lv_obj_set_width(ui_PanelTimePassedButton, 128);
    lv_obj_set_height(ui_PanelTimePassedButton, 20);
    lv_obj_set_x(ui_PanelTimePassedButton, -14);
    lv_obj_set_y(ui_PanelTimePassedButton, 70);
    lv_obj_set_align(ui_PanelTimePassedButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelTimePassedButton, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_PanelTimePassedButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelTimePassedButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelTimePassedButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTimePassedButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelTimePassedButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelTimePassedButton, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelTimePassedButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelTimePassedButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelTimePassedButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelTimePassedButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageTimePassedButton = lv_img_create(ui_PanelTimePassedButton);
    lv_img_set_src(ui_ImageTimePassedButton, &ui_img_last_seen_png);
    lv_obj_set_width(ui_ImageTimePassedButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageTimePassedButton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageTimePassedButton, 1);
    lv_obj_set_y(ui_ImageTimePassedButton, 0);
    lv_obj_add_flag(ui_ImageTimePassedButton, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageTimePassedButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ImageTimePassedButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ImageTimePassedButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ImageTimePassedButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ImageTimePassedButton, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTimePassedValueButton = lv_label_create(ui_PanelTimePassedButton);
    lv_obj_set_width(ui_LabelTimePassedValueButton, 103);
    lv_obj_set_height(ui_LabelTimePassedValueButton, 16);
    lv_obj_set_x(ui_LabelTimePassedValueButton, 22);
    lv_obj_set_y(ui_LabelTimePassedValueButton, 1);
    lv_label_set_text(ui_LabelTimePassedValueButton, "00: 00: 00: 00");
    lv_obj_set_style_text_color(ui_LabelTimePassedValueButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTimePassedValueButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTimePassedValueButton, &ui_font_Font12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelTimePassedValueButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelTimePassedValueButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LabelTimePassedValueButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_LabelTimePassedValueButton, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTopButton = lv_obj_create(ui_PanelSensorNodeButton);
    lv_obj_set_width(ui_PanelTopButton, LV_SIZE_CONTENT);   /// 27
    lv_obj_set_height(ui_PanelTopButton, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_PanelTopButton, 65);
    lv_obj_set_y(ui_PanelTopButton, 67);
    lv_obj_set_align(ui_PanelTopButton, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelTopButton, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelTopButton, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelTopButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelTopButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelTopButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTopButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelTopButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelTopButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelTopButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelTopButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelTopButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelTopButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelTopButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageButtonTopButton = lv_imgbtn_create(ui_PanelTopButton);
    lv_imgbtn_set_src(ui_ImageButtonTopButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_set_top_png, NULL);
    lv_imgbtn_set_src(ui_ImageButtonTopButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_cancel_set_top_png, NULL);
    lv_imgbtn_set_src(ui_ImageButtonTopButton, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImageButtonTopButton, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_set_top_png, NULL);
    lv_imgbtn_set_src(ui_ImageButtonTopButton, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_cancel_set_top_png, NULL);
    lv_imgbtn_set_src(ui_ImageButtonTopButton, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImageButtonTopButton, 25);
    lv_obj_set_height(ui_ImageButtonTopButton, 25);
    lv_obj_set_x(ui_ImageButtonTopButton, 0);
    lv_obj_set_y(ui_ImageButtonTopButton, 1);
    lv_obj_add_flag(ui_ImageButtonTopButton, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_border_color(ui_ImageButtonTopButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ImageButtonTopButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ImageButtonTopButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ImageButtonTopButton, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_ImageButtonTopButton, lv_color_hex(0x4BD5CB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ImageButtonTopButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSensorNodeDeleteButton = lv_obj_create(ui_PanelSensorButton);
    lv_obj_set_width(ui_PanelSensorNodeDeleteButton, 156);
    lv_obj_set_height(ui_PanelSensorNodeDeleteButton, 160);
    lv_obj_set_align(ui_PanelSensorNodeDeleteButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelSensorNodeDeleteButton, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelSensorNodeDeleteButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSensorNodeDeleteButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSensorNodeDeleteButton, lv_color_hex(0x162137), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSensorNodeDeleteButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSensorNodeDeleteButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelSensorNodeDeleteButton, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageDeleteButton = lv_img_create(ui_PanelSensorNodeDeleteButton);
    lv_img_set_src(ui_ImageDeleteButton, &ui_img_delete_png);
    lv_obj_set_width(ui_ImageDeleteButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageDeleteButton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageDeleteButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageDeleteButton, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageDeleteButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_transform_zoom(ui_ImageDeleteButton, 288, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_add_event_cb(ui_SliderSignalStrengthButton, ui_event_SliderSignalStrengthButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderBatteryButton, ui_event_SliderBatteryButton, LV_EVENT_ALL, NULL);
    
    lv_obj_add_event_cb(ui_SwitchButtonButton, ui_event_SwitchButtonButton, LV_EVENT_ALL, ui_PanelSensorButton);
    
    lv_obj_add_event_cb(ui_ImageButtonTopButton, ui_event_ImageButtonTopButton, LV_EVENT_ALL, ui_PanelSensorButton);
    lv_obj_add_event_cb(ui_PanelSensorNodeButton, ui_event_PanelSensorNodeButton_1, LV_EVENT_ALL, ui_PanelSensorNodeButton);
    lv_obj_add_event_cb(ui_PanelSensorNodeButton, ui_event_PanelSensorNodeButton_2, LV_EVENT_ALL, ui_PanelSensorNodeDeleteButton);
    lv_obj_add_event_cb(ui_ImageDeleteButton, ui_event_ImageDeleteButton, LV_EVENT_ALL, ui_PanelSensorButton);
    lv_obj_add_event_cb(ui_PanelSensorNodeDeleteButton, ui_event_PanelSensorNodeDeleteButton_1, LV_EVENT_ALL, ui_PanelSensorNodeButton);
    lv_obj_add_event_cb(ui_PanelSensorNodeDeleteButton, ui_event_PanelSensorNodeDeleteButton_2, LV_EVENT_ALL, ui_PanelSensorNodeDeleteButton);

    panel_with_type union_sensor;

    union_sensor.panel_union.button.ui_PanelSensorButton = ui_PanelSensorButton;
    union_sensor.panel_union.button.ui_PanelSensorNodeButton = ui_PanelSensorNodeButton;
    union_sensor.panel_union.button.ui_PanelChartButton = ui_PanelChartButton;
    union_sensor.panel_union.button.ui_ChartDisplayButton = ui_ChartDisplayButton;
    union_sensor.panel_union.button.ui_LabelTypeButton = ui_LabelTypeButton;
    union_sensor.panel_union.button.ui_LabelFportButton = ui_LabelFportButton;
    union_sensor.panel_union.button.ui_LabelDevEUIButton = ui_LabelDevEUIButton;
    union_sensor.panel_union.button.ui_LabelNameButton = ui_LabelNameButton;
    union_sensor.panel_union.button.ui_PanelSignalStrengthButton = ui_PanelSignalStrengthButton;
    union_sensor.panel_union.button.ui_ImageSignalStrengthButton = ui_ImageSignalStrengthButton;
    union_sensor.panel_union.button.ui_SliderSignalStrengthButton = ui_SliderSignalStrengthButton;
    union_sensor.panel_union.button.ui_LabelSignalStrengthValueButton = ui_LabelSignalStrengthValueButton;
    union_sensor.panel_union.button.ui_PanelBatteryButton = ui_PanelBatteryButton;
    union_sensor.panel_union.button.ui_ImageBatteryButton = ui_ImageBatteryButton;
    union_sensor.panel_union.button.ui_SliderBatteryButton = ui_SliderBatteryButton;
    union_sensor.panel_union.button.ui_LabelBatteryButton = ui_LabelBatteryButton;
    union_sensor.panel_union.button.ui_PanelButtonButton = ui_PanelButtonButton;
    union_sensor.panel_union.button.ui_SwitchButtonButton = ui_SwitchButtonButton;
    union_sensor.panel_union.button.ui_LabelButtonONButton = ui_LabelButtonONButton;
    union_sensor.panel_union.button.ui_LabelButtonOFFButton = ui_LabelButtonOFFButton;
    union_sensor.panel_union.button.ui_PanelTimePassedButton = ui_PanelTimePassedButton;
    union_sensor.panel_union.button.ui_ImageTimePassedButton = ui_ImageTimePassedButton;
    union_sensor.panel_union.button.ui_LabelTimePassedValueButton = ui_LabelTimePassedValueButton;
    union_sensor.panel_union.button.ui_PanelTopButton = ui_PanelTopButton;
    union_sensor.panel_union.button.ui_ImageButtonTopButton = ui_ImageButtonTopButton;
    union_sensor.panel_union.button.ui_PanelSensorNodeDeleteButton = ui_PanelSensorNodeDeleteButton;
    union_sensor.panel_union.button.ui_ImageDeleteButton = ui_ImageDeleteButton;

    union_sensor.panel_union.button.button_press_flag = false;
    union_sensor.panel_union.button.button_status = false;

    union_sensor.panel_type = BUTTON_TYPE;

    lv_obj_set_x(union_sensor.panel_union.button.ui_PanelSensorButton, x_by_index(index));
    lv_obj_set_y(union_sensor.panel_union.button.ui_PanelSensorButton, y_by_index(index));
    
    return union_sensor;

}
