// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

#include "sort.h"

extern lv_obj_t * ui_ButtonSaveConfig;
extern lv_obj_t * ui_LabelSaveConfig;

// extern lv_obj_t * ui_ButtonSendActivate_TTN_connect;
// extern lv_obj_t * ui_LabelSendActivate_TTN_connect;

void ui_event_ConfigSave(lv_event_t * e);

// void ui_event_SendActivate_TTN_connect(lv_event_t * e);

void Boot_Animation(lv_obj_t * TargetObject, int delay);
// void StarMove3_Animation(lv_obj_t * TargetObject, int delay);
void ProductMove1_Animation(lv_obj_t * TargetObject, int delay);
void ProductMove2_Animation(lv_obj_t * TargetObject, int delay);
void ProductMove3_Animation(lv_obj_t * TargetObject, int delay);
void ProductMove4_Animation(lv_obj_t * TargetObject, int delay);
void ProductMove5_Animation(lv_obj_t * TargetObject, int delay);
void ProductMove6_Animation(lv_obj_t * TargetObject, int delay);
void LogoMove1_Animation(lv_obj_t * TargetObject, int delay);
// void StarMove2_Animation(lv_obj_t * TargetObject, int delay);
// void StarMove1_Animation(lv_obj_t * TargetObject, int delay);
void LogoMove2_Animation(lv_obj_t * TargetObject, int delay);
// void LabelMove1_Animation(lv_obj_t * TargetObject, int delay);
// void LabelMove2_Animation(lv_obj_t * TargetObject, int delay);
void NewPanelArrive_Animation(lv_obj_t * TargetObject, int delay);
void LoRaParams_Page_Notice_Message_Animation(lv_obj_t * TargetObject, int delay, int leave_time_ms);

// SCREEN: ui_ScreenBoot
void ui_ScreenBoot_screen_init(void);
void ui_event_ScreenBoot(lv_event_t * e);
extern lv_obj_t * ui_ScreenBoot;
extern lv_obj_t * ui_ContainerStar1;
extern lv_obj_t * ui_SliderStar1;
extern lv_obj_t * ui_SliderStar2;
extern lv_obj_t * ui_SliderStar3;
extern lv_obj_t * ui_SliderStar4;
extern lv_obj_t * ui_SliderStar5;
extern lv_obj_t * ui_SliderStar6;
extern lv_obj_t * ui_ContainerStar2;
extern lv_obj_t * ui_SliderStar7;
extern lv_obj_t * ui_SliderStar8;
extern lv_obj_t * ui_SliderStar9;
extern lv_obj_t * ui_SliderStar10;
extern lv_obj_t * ui_SliderStar11;
extern lv_obj_t * ui_SliderStar12;
extern lv_obj_t * ui_ImageProduct1;
extern lv_obj_t * ui_ImageProduct2;
extern lv_obj_t * ui_ImageProduct3;
extern lv_obj_t * ui_ImageProduct4;
extern lv_obj_t * ui_ImageProduct5;
extern lv_obj_t * ui_ImageProduct6;
extern lv_obj_t * ui_ImageBootLogo1;
extern lv_obj_t * ui_ImageBootLogo2;
extern lv_obj_t * ui_LabelPresentEverything1;
extern lv_obj_t * ui_LabelPresentEverything2;
extern lv_obj_t * ui_SliderStarMove1;
extern lv_obj_t * ui_SliderStarMove2;
extern lv_obj_t * ui_SliderStarMove3;

// SCREEN: ui_ScreenMain
void ui_ScreenMain_screen_init(void);
extern lv_obj_t * ui_ScreenMain;
extern lv_obj_t * ui_ContainerLeftMain;
extern lv_obj_t * ui_ContainerHomePageMain;
extern lv_obj_t * ui_ImageHomePageMain;
extern lv_obj_t * ui_LabelHomePageMain;
void ui_event_ContainerSettingMain(lv_event_t * e);
extern lv_obj_t * ui_ContainerSettingPageMain;
extern lv_obj_t * ui_ImageSettingPageMain;
extern lv_obj_t * ui_LabelSettingPageMain;
void ui_event_ContainerLoRaParamsMain(lv_event_t * e);
extern lv_obj_t * ui_ContainerLoRaPageMain;
extern lv_obj_t * ui_ImageLoRaPageMain;
extern lv_obj_t * ui_LabelLoRaPageMain;
extern lv_obj_t * ui_ImageLogoMain;
extern lv_obj_t * ui_PanelSeparateTableScreenMain;
extern lv_obj_t * ui_PanelBanner;
void ui_event_ImageProfile(lv_event_t * e);
extern lv_obj_t * ui_ImageProfile;
extern lv_obj_t * ui_ContainerNewMessageNotice;
extern lv_obj_t * ui_LabelNewMessageNotice;
extern lv_obj_t * ui_ContainerRefreshMessageNotice;
extern lv_obj_t * ui_LabelRefreshMessageNotice;
extern lv_obj_t * ui_ContainerMessageNoticeMain;
extern lv_obj_t * ui_LabelMessageNoticeMain;
extern lv_obj_t * ui_PanelPanel;
extern lv_obj_t * ui_PanelPanelFilter;
extern lv_obj_t * ui_LabelPanelNumber;
extern lv_obj_t * ui_LabelPanelNumberValue;
void ui_event_DropdownSelectTime(lv_event_t * e);
extern lv_obj_t * ui_DropdownSelectTime;
extern lv_obj_t * ui_ImageTimeSort;
void ui_event_DropdownSelectBatteryLevel(lv_event_t * e);
extern lv_obj_t * ui_DropdownSelectBatteryLevel;
extern lv_obj_t * ui_ImageBatteryLevelSort;
extern lv_obj_t * ui_PanelContainer;
extern lv_obj_t * ui_LabelNoPanelDataReceived;

// SCREEN: ui_ScreenSetting
void ui_ScreenSetting_screen_init(void);
extern lv_obj_t * ui_ScreenSetting;
extern lv_obj_t * ui_ContainerLeftSetting;
void ui_event_ContainerMainSetting(lv_event_t * e);
extern lv_obj_t * ui_ContainerHomePageSetting;
extern lv_obj_t * ui_ImageHomePageSetting;
extern lv_obj_t * ui_LabelHomePageSetting;
extern lv_obj_t * ui_ContainerSettingPageSetting;
extern lv_obj_t * ui_ImageSettingPageSetting;
extern lv_obj_t * ui_LabelSettingPageSetting;
void ui_event_ContainerLoRaParamsSetting(lv_event_t * e);
extern lv_obj_t * ui_ContainerLoRaPageSetting;
extern lv_obj_t * ui_ImageLoRaPageSetting;
extern lv_obj_t * ui_LabelLoRaPageSetting;
extern lv_obj_t * ui_ImageLogoSetting;
extern lv_obj_t * ui_PanelSeparateTableScreenSetting;
extern lv_obj_t * ui_PanelSystem;
extern lv_obj_t * ui_LabelSystemSetting;
extern lv_obj_t * ui_PanelBrightnessAdjustment;
extern lv_obj_t * ui_LabelBrightnessAdjustment;
void ui_event_SliderBrightnessAdjustment(lv_event_t * e);
extern lv_obj_t * ui_SliderBrightnessAdjustment;
extern lv_obj_t * ui_PanelTemUnit;
extern lv_obj_t * ui_LabelTemUnit;
void ui_event_DropdownTemUnit(lv_event_t * e);
extern lv_obj_t * ui_DropdownTemUnit;
extern lv_obj_t * ui_PanelBootAnimationSwitch;
extern lv_obj_t * ui_LabelBootAnimation;
// void ui_event_CheckboxBootAnimation(lv_event_t * e);
void ui_event_DropdownBootAnimationSwitch(lv_event_t * e);
// extern lv_obj_t * ui_CheckboxBootAnimation;
extern lv_obj_t * ui_DropdownBootAnimationSwitch;
extern lv_obj_t * ui_PanelFportDisplaySwitch;
extern lv_obj_t * ui_LabelFportDisplay;
void ui_event_DropdownFportDisplaySwitch(lv_event_t * e);
extern lv_obj_t * ui_DropdownFportDisplaySwitch;
extern lv_obj_t * ui_LabelSystemInformation;
extern lv_obj_t * ui_PanelModel;
extern lv_obj_t * ui_LabelModel;
extern lv_obj_t * ui_LabelModelValue;
extern lv_obj_t * ui_PanelVersion;
extern lv_obj_t * ui_LabelVersion;
extern lv_obj_t * ui_LabelVersionValue;
extern lv_obj_t * ui_PanelBootTime;
extern lv_obj_t * ui_LabelBootTime;
extern lv_obj_t * ui_LabelBootTimeValue;

// SCREEN: ui_ScreenLoRaParams
void ui_ScreenLoRaParams_screen_init(void);
extern lv_obj_t * ui_ScreenLoRaParams;
extern lv_obj_t * ui_ContainerLeftLoRaParams;
void ui_event_ContainerHomePageLoRaParams(lv_event_t * e);
extern lv_obj_t * ui_ContainerHomePageLoRaParams;
extern lv_obj_t * ui_ImageHomePageLoRaParams;
extern lv_obj_t * ui_LabelHomePageLoRaParams;
void ui_event_ContainerSettingPageLoRaParams(lv_event_t * e);
extern lv_obj_t * ui_ContainerSettingPageLoRaParams;
extern lv_obj_t * ui_ImageSettingPageLoRaParams;
extern lv_obj_t * ui_LabelSettingPageLoRaParams;
extern lv_obj_t * ui_ContainerLoRaPageLoRaParams;
extern lv_obj_t * ui_ImageLoRaPageLoRaParams;
extern lv_obj_t * ui_LabelLoRaPageLoRaParams;
extern lv_obj_t * ui_ImageLogoLoRaParams;
extern lv_obj_t * ui_PanelSeparateTableScreenLoRaParams;
extern lv_obj_t * ui_ContainerMessageNoticeLoRaParams;
extern lv_obj_t * ui_LabelMessageNoticeLoRaParams;
extern lv_obj_t * ui_PanelPanelLoRaParams;
extern lv_obj_t * ui_PanelLA66FwLoRaParams;
extern lv_obj_t * ui_DropdownCurrentFwLoRaParams;
extern lv_obj_t * ui_LabelFwVersionLoRaParams;
void ui_event_ButtonFwDetectLoRaParams(lv_event_t * e);
extern lv_obj_t * ui_ButtonFwDetectLoRaParams;
extern lv_obj_t * ui_LabelFwDetectLoRaParams;
// void ui_event_ButtonGetLA66ConfigLoRaParams(lv_event_t * e);
// extern lv_obj_t * ui_ButtonGetLA66ConfigLoRaParams;
// extern lv_obj_t * ui_LabelGetLA66ConfigLoRaParams;
extern lv_obj_t * ui_PanelFontSizeLoRaParams;
extern lv_obj_t * ui_LabelFontSizeLoRaParams;
void ui_event_DropdownFontSizeLoRaParams(lv_event_t * e);
extern lv_obj_t * ui_DropdownFontSizeLoRaParams;
extern lv_obj_t * ui_PanelLoRaWANNetworkStatusLoRaParams;
extern lv_obj_t * ui_DropdownLoRaWANNetworkStatusLoRaParams;
void ui_event_ButtonLoRaWANNetworkActivateLoRaParams(lv_event_t * e);
extern lv_obj_t * ui_ButtonLoRaWANNetworkActivateLoRaParams;
extern lv_obj_t * ui_LabelLoRaWANNetworkActivateLoRaParams;
extern lv_obj_t * ui_PanelLoRaWANNetworkStatusHideLoRaParams;
void ui_event_ButtonFontSizeIncreaseLoRaParams(lv_event_t * e);
extern lv_obj_t * ui_ButtonFontSizeIncreaseLoRaParams;
extern lv_obj_t * ui_LabelFontSizeIncreaseLoRaParams;
void ui_event_ButtonFontSizeDecreaseLoRaParams(lv_event_t * e);
extern lv_obj_t * ui_ButtonFontSizeDecreaseLoRaParams;
extern lv_obj_t * ui_LabelFontSizeDecreaseLoRaParams;
extern lv_obj_t * ui_PanelDialogLoRaParams;
extern lv_obj_t * ui_TextAreaDialogLoRaParams;
// CUSTOM VARIABLES


extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_product_1_png);    // assets/Product_1.png
LV_IMG_DECLARE(ui_img_product_2_png);    // assets/Product_2.png
LV_IMG_DECLARE(ui_img_product_3_png);    // assets/Product_3.png
LV_IMG_DECLARE(ui_img_product_4_png);    // assets/Product_4.png
LV_IMG_DECLARE(ui_img_product_5_png);    // assets/Product_5.png
LV_IMG_DECLARE(ui_img_product_6_png);    // assets/Product_6.png
LV_IMG_DECLARE(ui_img_boot_logo_png);    // assets/Boot_Logo.png
LV_IMG_DECLARE(ui_img_home_page_png);    // assets/Home_Page.png
LV_IMG_DECLARE(ui_img_setting_png);    // assets/Setting.png
LV_IMG_DECLARE(ui_img_logo_png);    // assets/Logo.png
LV_IMG_DECLARE(ui_img_profile_png);    // assets/Profile.png
LV_IMG_DECLARE(ui_img_last_seen_png);    // assets/Last_Seen.png
LV_IMG_DECLARE(ui_img_battery_png);    // assets/Battery.png


void ui_event_switch_display(lv_event_t * e);
void ui_event_switch_normal_func(lv_event_t * e);


LV_IMG_DECLARE(ui__temporary_image);
LV_IMG_DECLARE(ui_img_home_page_png);    // assets/Home_Page.png
LV_IMG_DECLARE(ui_img_setting_png);    // assets/Setting.png
LV_IMG_DECLARE(ui_img_gateway_png);    // assets/gateway.png
LV_IMG_DECLARE(ui_img_logo_png);    // assets/Logo.png
LV_IMG_DECLARE(ui_img_last_seen_png);    // assets/Last_Seen.png
LV_IMG_DECLARE(ui_img_battery_png);    // assets/Battery.png
LV_IMG_DECLARE(ui_img_like_96_png);    // assets/like_96.png
LV_IMG_DECLARE(ui_img_like_118_png);    // assets/like_118.png
LV_IMG_DECLARE(ui_img_like_108_png);    // assets/like_108.png
LV_IMG_DECLARE(ui_img_interesting_96_png);    // assets/interesting_96.png
LV_IMG_DECLARE(ui_img_interesting_118_png);    // assets/interesting_118.png
LV_IMG_DECLARE(ui_img_interesting_108_png);    // assets/interesting_108.png
LV_IMG_DECLARE(ui_img_common_96_png);    // assets/common_96.png
LV_IMG_DECLARE(ui_img_common_118_png);    // assets/common_118.png
LV_IMG_DECLARE(ui_img_common_108_png);    // assets/common_108.png
LV_IMG_DECLARE(ui_img_dislike_96_png);    // assets/dislike_96.png
LV_IMG_DECLARE(ui_img_dislike_118_png);    // assets/dislike_118.png
LV_IMG_DECLARE(ui_img_dislike_108_png);    // assets/dislike_108.png
LV_IMG_DECLARE(ui_img_one_channel_hub_case3_679_480_png);    // assets/one_channel_hub_case3_679_480.png
LV_IMG_DECLARE(ui_img_mark_level_1_png);    // assets/mark_level_1.png
LV_IMG_DECLARE(ui_img_mark_level_2_png);    // assets/mark_level_2.png
LV_IMG_DECLARE(ui_img_mark_level_2_2_png);    // assets/mark_level_2_2.png
LV_IMG_DECLARE(ui_img_mark_level_3_png);    // assets/mark_level_3.png
LV_IMG_DECLARE(ui_img_mark_level_4_png);    // assets/mark_level_4.png
LV_IMG_DECLARE(ui_img_product_1_png);    // assets/Product_1.png
LV_IMG_DECLARE(ui_img_product_2_png);    // assets/Product_2.png
LV_IMG_DECLARE(ui_img_product_3_png);    // assets/Product_3.png
LV_IMG_DECLARE(ui_img_product_4_png);    // assets/Product_4.png
LV_IMG_DECLARE(ui_img_product_5_png);    // assets/Product_5.png
LV_IMG_DECLARE(ui_img_product_6_png);    // assets/Product_6.png
LV_IMG_DECLARE(ui_img_lora_module_png);    // assets/LoRa_Module.png



LV_FONT_DECLARE(ui_font_Font12);
LV_FONT_DECLARE(ui_font_Font16);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
