// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

// extern const lv_font_t *font_size_address_table[];

void TimeSort(lv_event_t * e);
void BatteryLevelSort(lv_event_t * e);
void TemUnitSwitch(lv_event_t * e);
void BootScreenSwitch(lv_event_t * e);
void FportDisplaySwitch(lv_event_t * e);
void BrightnessAdjust(lv_event_t * e);
void AllConfigSave(lv_event_t * e);
// void SendJoin(lv_event_t * e);
void LA66FirmwareRecognize(lv_event_t * e);
// void LA66ConfigurationInformationUpdate(lv_event_t * e);
void ChangeFontSizeLoRaParams(lv_event_t * e);
void ActivateLoRaWANNetwork(lv_event_t * e);
void FontSizeIncreaseLoRaParams(lv_event_t * e);
void FontSizeDecreaseLoRaParams(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
