// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void TimeSort(lv_event_t * e)
{
	// Your code here

	uint16_t option_index = lv_dropdown_get_selected(ui_DropdownSelectTime);
	fprintf(stderr,"Time Sort option:%d\n", option_index);

	if(lv_dropdown_get_selected(ui_DropdownSelectBatteryLevel) != 0) {
		if(battery_sort_value_get() != 0) {
			battery_sort_value_set(0);
		}
		panel_index_restore(arr_get());
		
		lv_dropdown_set_selected(ui_DropdownSelectBatteryLevel, 0);
		vTaskDelay(100 /  portTICK_PERIOD_MS);
	}

	if(time_sort_value_get() == option_index) {
		return;
	}

	if (option_index == 0) {
		panel_index_restore(arr_get());
	}
	else if (option_index == 1) {
		reposArray_by_time(arr_get(), TIME_SORT_LASTEST);
	}
	else if (option_index == 2) {
		reposArray_by_time(arr_get(), TIME_SORT_EARLIEST);
	}

	time_sort_value_set(option_index);
}

void BatteryLevelSort(lv_event_t * e)
{
	// Your code here

	uint16_t option_index = lv_dropdown_get_selected(ui_DropdownSelectBatteryLevel);
	fprintf(stderr,"Battery Sort option:%d\n", option_index);

	if(lv_dropdown_get_selected(ui_DropdownSelectTime) != 0) {
		if(time_sort_value_get() != 0) {
			time_sort_value_set(0);
		}
		panel_index_restore(arr_get());

		lv_dropdown_set_selected(ui_DropdownSelectTime, 0);
		vTaskDelay(100 /  portTICK_PERIOD_MS);
	}

	if(battery_sort_value_get() == option_index) {
		return;
	}

	if (option_index == 0) {
		panel_index_restore(arr_get());
	}
	else if (option_index == 1) {
		reposArray_by_battery(arr_get(), BATTERY_LEVEL_SORT_HIGHEST);
	}
	else if (option_index == 2) {
		reposArray_by_battery(arr_get(), BATTERY_LEVEL_SORT_LOWEST);
	}

	battery_sort_value_set(option_index);
}

void TemUnitSwitch(lv_event_t * e)
{
	fprintf(stderr,"Tem Unit switch!\n");
}

void BootScreenSwitch(lv_event_t * e)
{

}

void AllConfigSave(lv_event_t * e)
{
	if(nvs_store_complete_flag_get() == true) {
		save_button_press_flag_set(true);
	}
}

void BrightnessAdjust(lv_event_t * e)
{
	// Your code here
	int32_t value = lv_slider_get_value(ui_SliderBrightnessAdjustment);
	
	ledc_set_duty(LEDC_LOW_SPEED_MODE, LEDC_CHANNEL_0, BRIGHTNESS_start + value * BRIGHTNESS_STEP);//20 250
	ledc_update_duty(LEDC_LOW_SPEED_MODE, LEDC_CHANNEL_0);
	fprintf(stderr,"Slider BL Brightness level change to: %ld\n", value);
}
