// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui_water_leak.h"
#include "../../sort.h"
#include "ui.h"

panel_with_type create_water_leak(uint8_t index, lv_obj_t *parent)
{
    ui_PanelSensorWaterLeak = lv_obj_create(parent);
    lv_obj_set_width(ui_PanelSensorWaterLeak, 156);
    lv_obj_set_height(ui_PanelSensorWaterLeak, 160);
    lv_obj_set_x(ui_PanelSensorWaterLeak, -85);
    lv_obj_set_y(ui_PanelSensorWaterLeak, -90);
    lv_obj_set_align(ui_PanelSensorWaterLeak, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSensorWaterLeak, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSensorWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSensorWaterLeak, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSensorWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSensorWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSensorNodeWaterLeak = lv_obj_create(ui_PanelSensorWaterLeak);
    lv_obj_set_width(ui_PanelSensorNodeWaterLeak, 156);
    lv_obj_set_height(ui_PanelSensorNodeWaterLeak, 160);
    lv_obj_set_align(ui_PanelSensorNodeWaterLeak, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSensorNodeWaterLeak, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSensorNodeWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSensorNodeWaterLeak, lv_color_hex(0x162137), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSensorNodeWaterLeak, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSensorNodeWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelChartWaterLeak = lv_obj_create(ui_PanelSensorNodeWaterLeak);
    lv_obj_set_width(ui_PanelChartWaterLeak, 156);
    lv_obj_set_height(ui_PanelChartWaterLeak, 50);
    lv_obj_set_x(ui_PanelChartWaterLeak, 0);
    lv_obj_set_y(ui_PanelChartWaterLeak, -56);
    lv_obj_set_align(ui_PanelChartWaterLeak, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelChartWaterLeak, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelChartWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelChartWaterLeak, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelChartWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelChartWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChartDisplayWaterLeak = lv_chart_create(ui_PanelChartWaterLeak);
    lv_obj_set_width(ui_ChartDisplayWaterLeak, 156);
    lv_obj_set_height(ui_ChartDisplayWaterLeak, 50);
    lv_obj_set_align(ui_ChartDisplayWaterLeak, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ChartDisplayWaterLeak, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_chart_set_type(ui_ChartDisplayWaterLeak, LV_CHART_TYPE_NONE);
    lv_chart_set_range(ui_ChartDisplayWaterLeak, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_chart_set_div_line_count(ui_ChartDisplayWaterLeak, 0, 0);
    lv_chart_set_axis_tick(ui_ChartDisplayWaterLeak, LV_CHART_AXIS_PRIMARY_X, 0, 0, 0, 0, false, 50);
    lv_chart_set_axis_tick(ui_ChartDisplayWaterLeak, LV_CHART_AXIS_PRIMARY_Y, 0, 0, 0, 0, false, 100);
    lv_chart_set_axis_tick(ui_ChartDisplayWaterLeak, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);
    lv_chart_series_t * ui_ChartDisplayWaterLeak_series_1 = lv_chart_add_series(ui_ChartDisplayWaterLeak,
                                                                                lv_color_hex(0xFFFFFF), LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_ChartDisplayWaterLeak_series_1_array[] = { 0, 10, 20, 50, 80, 90, 40, 20, 40, 0 };
    lv_chart_set_ext_y_array(ui_ChartDisplayWaterLeak, ui_ChartDisplayWaterLeak_series_1,
                             ui_ChartDisplayWaterLeak_series_1_array);
    lv_obj_set_style_radius(ui_ChartDisplayWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ChartDisplayWaterLeak, lv_color_hex(0x0BA8CD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChartDisplayWaterLeak, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ChartDisplayWaterLeak, lv_color_hex(0x162D33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_ChartDisplayWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_ChartDisplayWaterLeak, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ChartDisplayWaterLeak, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_ChartDisplayWaterLeak, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ChartDisplayWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_line_color(ui_ChartDisplayWaterLeak, lv_color_hex(0x2121E2), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_ChartDisplayWaterLeak, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(ui_ChartDisplayWaterLeak, 2, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_set_style_line_width(ui_ChartDisplayWaterLeak, 2, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_LabelTypeWaterLeak = lv_label_create(ui_ChartDisplayWaterLeak);
    lv_obj_set_width(ui_LabelTypeWaterLeak, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTypeWaterLeak, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTypeWaterLeak, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTypeWaterLeak, "Water Leak");
    lv_obj_set_style_text_color(ui_LabelTypeWaterLeak, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTypeWaterLeak, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTypeWaterLeak, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDevEUIWaterLeak = lv_label_create(ui_PanelSensorNodeWaterLeak);
    lv_obj_set_width(ui_LabelDevEUIWaterLeak, 80);   /// 1 
    lv_obj_set_height(ui_LabelDevEUIWaterLeak, 16);    /// 1 
    lv_obj_set_x(ui_LabelDevEUIWaterLeak, -35);
    lv_obj_set_y(ui_LabelDevEUIWaterLeak, -20);
    lv_obj_set_align(ui_LabelDevEUIWaterLeak, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDevEUIWaterLeak, "ABCDEF");
    lv_obj_set_style_text_color(ui_LabelDevEUIWaterLeak, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDevEUIWaterLeak, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDevEUIWaterLeak, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelDevEUIWaterLeak, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelDevEUIWaterLeak, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LabelDevEUIWaterLeak, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_LabelDevEUIWaterLeak, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelDevEUIWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelDevEUIWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelDevEUIWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelDevEUIWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_LabelDevEUIWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_LabelDevEUIWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNameWaterLeak = lv_label_create(ui_PanelSensorNodeWaterLeak);
    lv_obj_set_width(ui_LabelNameWaterLeak, 65);
    lv_obj_set_height(ui_LabelNameWaterLeak, 32);
    lv_obj_set_x(ui_LabelNameWaterLeak, -16);
    lv_obj_set_y(ui_LabelNameWaterLeak, 48);
    lv_label_set_long_mode(ui_LabelNameWaterLeak, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_LabelNameWaterLeak, "0123456789ABCDEF");
    lv_obj_set_style_text_color(ui_LabelNameWaterLeak, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelNameWaterLeak, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNameWaterLeak, &ui_font_Font12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelNameWaterLeak, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelNameWaterLeak, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LabelNameWaterLeak, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_LabelNameWaterLeak, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCurrentStatusLeakingWaterLeak = lv_obj_create(ui_PanelSensorNodeWaterLeak);
    lv_obj_set_width(ui_PanelCurrentStatusLeakingWaterLeak, 83);
    lv_obj_set_height(ui_PanelCurrentStatusLeakingWaterLeak, 40);
    lv_obj_set_x(ui_PanelCurrentStatusLeakingWaterLeak, -35);
    lv_obj_set_y(ui_PanelCurrentStatusLeakingWaterLeak, 41);
    lv_obj_set_align(ui_PanelCurrentStatusLeakingWaterLeak, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelCurrentStatusLeakingWaterLeak, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_PanelCurrentStatusLeakingWaterLeak, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelCurrentStatusLeakingWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelCurrentStatusLeakingWaterLeak, lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCurrentStatusLeakingWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelCurrentStatusLeakingWaterLeak, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelCurrentStatusLeakingWaterLeak, LV_BORDER_SIDE_NONE,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCurrentStatusLeakingWaterLeak = lv_label_create(ui_PanelCurrentStatusLeakingWaterLeak);
    lv_obj_set_width(ui_LabelCurrentStatusLeakingWaterLeak, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCurrentStatusLeakingWaterLeak, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCurrentStatusLeakingWaterLeak, 19);
    lv_obj_set_y(ui_LabelCurrentStatusLeakingWaterLeak, 0);
    lv_obj_set_align(ui_LabelCurrentStatusLeakingWaterLeak, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCurrentStatusLeakingWaterLeak, "Leaking");
    lv_obj_set_style_text_color(ui_LabelCurrentStatusLeakingWaterLeak, lv_color_hex(0xC42508),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCurrentStatusLeakingWaterLeak, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCurrentStatusLeakingWaterLeak, &lv_font_montserrat_12,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageCurrentStatusLeakingWaterLeak = lv_img_create(ui_PanelCurrentStatusLeakingWaterLeak);
    lv_img_set_src(ui_ImageCurrentStatusLeakingWaterLeak, &ui_img_leaking_png);
    lv_obj_set_width(ui_ImageCurrentStatusLeakingWaterLeak, 36);
    lv_obj_set_height(ui_ImageCurrentStatusLeakingWaterLeak, 40);
    lv_obj_set_x(ui_ImageCurrentStatusLeakingWaterLeak, -22);
    lv_obj_set_y(ui_ImageCurrentStatusLeakingWaterLeak, 0);
    lv_obj_set_align(ui_ImageCurrentStatusLeakingWaterLeak, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageCurrentStatusLeakingWaterLeak, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageCurrentStatusLeakingWaterLeak, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelCurrentStatusNormalWaterLeak = lv_obj_create(ui_PanelSensorNodeWaterLeak);
    lv_obj_set_width(ui_PanelCurrentStatusNormalWaterLeak, 83);
    lv_obj_set_height(ui_PanelCurrentStatusNormalWaterLeak, 40);
    lv_obj_set_x(ui_PanelCurrentStatusNormalWaterLeak, -35);
    lv_obj_set_y(ui_PanelCurrentStatusNormalWaterLeak, 41);
    lv_obj_set_align(ui_PanelCurrentStatusNormalWaterLeak, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelCurrentStatusNormalWaterLeak, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_PanelCurrentStatusNormalWaterLeak, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelCurrentStatusNormalWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelCurrentStatusNormalWaterLeak, lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCurrentStatusNormalWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelCurrentStatusNormalWaterLeak, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelCurrentStatusNormalWaterLeak, LV_BORDER_SIDE_NONE,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCurrentStatusNormalWaterLeak = lv_label_create(ui_PanelCurrentStatusNormalWaterLeak);
    lv_obj_set_width(ui_LabelCurrentStatusNormalWaterLeak, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCurrentStatusNormalWaterLeak, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCurrentStatusNormalWaterLeak, 19);
    lv_obj_set_y(ui_LabelCurrentStatusNormalWaterLeak, 0);
    lv_obj_set_align(ui_LabelCurrentStatusNormalWaterLeak, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCurrentStatusNormalWaterLeak, "Normal");
    lv_obj_set_style_text_color(ui_LabelCurrentStatusNormalWaterLeak, lv_color_hex(0x0E8E2E),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCurrentStatusNormalWaterLeak, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCurrentStatusNormalWaterLeak, &lv_font_montserrat_12,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageCurrentStatusNormalWaterLeak = lv_img_create(ui_PanelCurrentStatusNormalWaterLeak);
    lv_img_set_src(ui_ImageCurrentStatusNormalWaterLeak, &ui_img_normal_png);
    lv_obj_set_width(ui_ImageCurrentStatusNormalWaterLeak, 36);
    lv_obj_set_height(ui_ImageCurrentStatusNormalWaterLeak, 40);
    lv_obj_set_x(ui_ImageCurrentStatusNormalWaterLeak, -22);
    lv_obj_set_y(ui_ImageCurrentStatusNormalWaterLeak, 0);
    lv_obj_set_align(ui_ImageCurrentStatusNormalWaterLeak, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageCurrentStatusNormalWaterLeak, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageCurrentStatusNormalWaterLeak, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelSignalStrengthWaterLeak = lv_obj_create(ui_PanelSensorNodeWaterLeak);
    lv_obj_set_width(ui_PanelSignalStrengthWaterLeak, 72);
    lv_obj_set_height(ui_PanelSignalStrengthWaterLeak, 16);
    lv_obj_set_x(ui_PanelSignalStrengthWaterLeak, 40);
    lv_obj_set_y(ui_PanelSignalStrengthWaterLeak, -21);
    lv_obj_set_align(ui_PanelSignalStrengthWaterLeak, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelSignalStrengthWaterLeak, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_PanelSignalStrengthWaterLeak, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSignalStrengthWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSignalStrengthWaterLeak, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSignalStrengthWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSignalStrengthWaterLeak, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelSignalStrengthWaterLeak, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageSignalStrengthWaterLeak = lv_img_create(ui_PanelSignalStrengthWaterLeak);
    lv_img_set_src(ui_ImageSignalStrengthWaterLeak, &ui_img_signal_empty_png);
    lv_obj_set_width(ui_ImageSignalStrengthWaterLeak, 24);
    lv_obj_set_height(ui_ImageSignalStrengthWaterLeak, 16);
    lv_obj_set_x(ui_ImageSignalStrengthWaterLeak, -23);
    lv_obj_set_y(ui_ImageSignalStrengthWaterLeak, 0);
    lv_obj_set_align(ui_ImageSignalStrengthWaterLeak, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageSignalStrengthWaterLeak, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageSignalStrengthWaterLeak, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_ImageSignalStrengthWaterLeak, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ImageSignalStrengthWaterLeak, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderSignalStrengthWaterLeak = lv_slider_create(ui_PanelSignalStrengthWaterLeak);
    lv_slider_set_range(ui_SliderSignalStrengthWaterLeak, -128, 16);
    lv_slider_set_value(ui_SliderSignalStrengthWaterLeak, -60, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderSignalStrengthWaterLeak) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_SliderSignalStrengthWaterLeak, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderSignalStrengthWaterLeak, 24);
    lv_obj_set_height(ui_SliderSignalStrengthWaterLeak, 16);
    lv_obj_set_x(ui_SliderSignalStrengthWaterLeak, -23);
    lv_obj_set_y(ui_SliderSignalStrengthWaterLeak, 0);
    lv_obj_set_align(ui_SliderSignalStrengthWaterLeak, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SliderSignalStrengthWaterLeak, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_radius(ui_SliderSignalStrengthWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderSignalStrengthWaterLeak, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSignalStrengthWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderSignalStrengthWaterLeak, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderSignalStrengthWaterLeak, lv_color_hex(0xFFFFFF),
                              LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSignalStrengthWaterLeak, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SliderSignalStrengthWaterLeak, &ui_img_signal_full_png,
                                LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderSignalStrengthWaterLeak, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderSignalStrengthWaterLeak, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSignalStrengthWaterLeak, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelSignalStrengthValueWaterLeak = lv_label_create(ui_PanelSignalStrengthWaterLeak);
    lv_obj_set_width(ui_LabelSignalStrengthValueWaterLeak, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSignalStrengthValueWaterLeak, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSignalStrengthValueWaterLeak, 13);
    lv_obj_set_y(ui_LabelSignalStrengthValueWaterLeak, 0);
    lv_obj_set_align(ui_LabelSignalStrengthValueWaterLeak, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSignalStrengthValueWaterLeak, "Rssi: -80");
    lv_obj_set_style_text_color(ui_LabelSignalStrengthValueWaterLeak, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSignalStrengthValueWaterLeak, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelSignalStrengthValueWaterLeak, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSignalStrengthValueWaterLeak, &lv_font_montserrat_10,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelBatteryWaterLeak = lv_obj_create(ui_PanelSensorNodeWaterLeak);
    lv_obj_set_width(ui_PanelBatteryWaterLeak, 72);
    lv_obj_set_height(ui_PanelBatteryWaterLeak, 16);
    lv_obj_set_x(ui_PanelBatteryWaterLeak, 40);
    lv_obj_set_y(ui_PanelBatteryWaterLeak, -1);
    lv_obj_set_align(ui_PanelBatteryWaterLeak, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelBatteryWaterLeak, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_PanelBatteryWaterLeak, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelBatteryWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelBatteryWaterLeak, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelBatteryWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelBatteryWaterLeak, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelBatteryWaterLeak, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelBatteryWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelBatteryWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelBatteryWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelBatteryWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelBatteryWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelBatteryWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageBatteryWaterLeak = lv_img_create(ui_PanelBatteryWaterLeak);
    lv_img_set_src(ui_ImageBatteryWaterLeak, &ui_img_battery_empty_png);
    lv_obj_set_width(ui_ImageBatteryWaterLeak, 25);
    lv_obj_set_height(ui_ImageBatteryWaterLeak, 15);
    lv_obj_set_x(ui_ImageBatteryWaterLeak, -25);
    lv_obj_set_y(ui_ImageBatteryWaterLeak, -1);
    lv_obj_set_align(ui_ImageBatteryWaterLeak, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageBatteryWaterLeak, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageBatteryWaterLeak, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SliderBatteryWaterLeak = lv_slider_create(ui_PanelBatteryWaterLeak);
    lv_slider_set_range(ui_SliderBatteryWaterLeak, 2000, 4200);
    lv_slider_set_value(ui_SliderBatteryWaterLeak, 3700, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderBatteryWaterLeak) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_SliderBatteryWaterLeak, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderBatteryWaterLeak, 25);
    lv_obj_set_height(ui_SliderBatteryWaterLeak, 15);
    lv_obj_set_x(ui_SliderBatteryWaterLeak, -25);
    lv_obj_set_y(ui_SliderBatteryWaterLeak, -1);
    lv_obj_set_align(ui_SliderBatteryWaterLeak, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SliderBatteryWaterLeak, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_radius(ui_SliderBatteryWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderBatteryWaterLeak, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderBatteryWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderBatteryWaterLeak, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderBatteryWaterLeak, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderBatteryWaterLeak, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SliderBatteryWaterLeak, &ui_img_battery_full_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderBatteryWaterLeak, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderBatteryWaterLeak, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderBatteryWaterLeak, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelBatteryWaterLeak = lv_label_create(ui_PanelBatteryWaterLeak);
    lv_obj_set_width(ui_LabelBatteryWaterLeak, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBatteryWaterLeak, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBatteryWaterLeak, 13);
    lv_obj_set_y(ui_LabelBatteryWaterLeak, 0);
    lv_obj_set_align(ui_LabelBatteryWaterLeak, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBatteryWaterLeak, "3700mV");
    lv_obj_set_style_text_color(ui_LabelBatteryWaterLeak, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBatteryWaterLeak, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelBatteryWaterLeak, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBatteryWaterLeak, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelLastWaterLeak = lv_obj_create(ui_PanelSensorNodeWaterLeak);
    lv_obj_set_width(ui_PanelLastWaterLeak, 84);
    lv_obj_set_height(ui_PanelLastWaterLeak, 23);
    lv_obj_set_x(ui_PanelLastWaterLeak, 34);
    lv_obj_set_y(ui_PanelLastWaterLeak, 23);
    lv_obj_set_align(ui_PanelLastWaterLeak, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelLastWaterLeak, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_PanelLastWaterLeak, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelLastWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelLastWaterLeak, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelLastWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelLastWaterLeak, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelLastWaterLeak, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelLastWaterLeak = lv_label_create(ui_PanelLastWaterLeak);
    lv_obj_set_width(ui_LabelLastWaterLeak, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLastWaterLeak, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLastWaterLeak, 0);
    lv_obj_set_y(ui_LabelLastWaterLeak, -8);
    lv_obj_set_align(ui_LabelLastWaterLeak, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLastWaterLeak, "Last Duration");
    lv_obj_set_style_text_color(ui_LabelLastWaterLeak, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelLastWaterLeak, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelLastWaterLeak, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelLastValueWaterLeak = lv_label_create(ui_PanelLastWaterLeak);
    lv_obj_set_width(ui_LabelLastValueWaterLeak, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLastValueWaterLeak, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLastValueWaterLeak, 0);
    lv_obj_set_y(ui_LabelLastValueWaterLeak, 5);
    lv_obj_set_align(ui_LabelLastValueWaterLeak, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLastValueWaterLeak, "0min");
    lv_obj_set_style_text_color(ui_LabelLastValueWaterLeak, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelLastValueWaterLeak, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelLastValueWaterLeak, &ui_font_Font12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTimesWaterLeak = lv_obj_create(ui_PanelSensorNodeWaterLeak);
    lv_obj_set_width(ui_PanelTimesWaterLeak, 49);
    lv_obj_set_height(ui_PanelTimesWaterLeak, 31);
    lv_obj_set_x(ui_PanelTimesWaterLeak, 33);
    lv_obj_set_y(ui_PanelTimesWaterLeak, 49);
    lv_obj_set_align(ui_PanelTimesWaterLeak, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelTimesWaterLeak, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_PanelTimesWaterLeak, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelTimesWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelTimesWaterLeak, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTimesWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelTimesWaterLeak, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelTimesWaterLeak, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelTimesWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelTimesWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelTimesWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelTimesWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelTimesWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelTimesWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTimesWaterLeak = lv_label_create(ui_PanelTimesWaterLeak);
    lv_obj_set_width(ui_LabelTimesWaterLeak, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTimesWaterLeak, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTimesWaterLeak, -1);
    lv_obj_set_y(ui_LabelTimesWaterLeak, -6);
    lv_obj_set_align(ui_LabelTimesWaterLeak, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTimesWaterLeak, "Times");
    lv_obj_set_style_text_color(ui_LabelTimesWaterLeak, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTimesWaterLeak, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTimesWaterLeak, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTimesValueWaterLeak = lv_label_create(ui_PanelTimesWaterLeak);
    lv_obj_set_width(ui_LabelTimesValueWaterLeak, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTimesValueWaterLeak, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTimesValueWaterLeak, -1);
    lv_obj_set_y(ui_LabelTimesValueWaterLeak, 8);
    lv_obj_set_align(ui_LabelTimesValueWaterLeak, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTimesValueWaterLeak, "0");
    lv_obj_set_style_text_color(ui_LabelTimesValueWaterLeak, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTimesValueWaterLeak, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTimesValueWaterLeak, &ui_font_Font12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTimePassedWaterLeak = lv_obj_create(ui_PanelSensorNodeWaterLeak);
    lv_obj_set_width(ui_PanelTimePassedWaterLeak, 128);
    lv_obj_set_height(ui_PanelTimePassedWaterLeak, 20);
    lv_obj_set_x(ui_PanelTimePassedWaterLeak, -14);
    lv_obj_set_y(ui_PanelTimePassedWaterLeak, 70);
    lv_obj_set_align(ui_PanelTimePassedWaterLeak, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelTimePassedWaterLeak, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_PanelTimePassedWaterLeak, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelTimePassedWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelTimePassedWaterLeak, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTimePassedWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelTimePassedWaterLeak, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelTimePassedWaterLeak, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelTimePassedWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelTimePassedWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelTimePassedWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelTimePassedWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageTimePassedWaterLeak = lv_img_create(ui_PanelTimePassedWaterLeak);
    lv_img_set_src(ui_ImageTimePassedWaterLeak, &ui_img_last_seen_png);
    lv_obj_set_width(ui_ImageTimePassedWaterLeak, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageTimePassedWaterLeak, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageTimePassedWaterLeak, 1);
    lv_obj_set_y(ui_ImageTimePassedWaterLeak, 0);
    lv_obj_add_flag(ui_ImageTimePassedWaterLeak, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageTimePassedWaterLeak, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ImageTimePassedWaterLeak, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ImageTimePassedWaterLeak, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ImageTimePassedWaterLeak, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ImageTimePassedWaterLeak, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTimePassedValueWaterLeak = lv_label_create(ui_PanelTimePassedWaterLeak);
    lv_obj_set_width(ui_LabelTimePassedValueWaterLeak, 103);
    lv_obj_set_height(ui_LabelTimePassedValueWaterLeak, 16);
    lv_obj_set_x(ui_LabelTimePassedValueWaterLeak, 22);
    lv_obj_set_y(ui_LabelTimePassedValueWaterLeak, 1);
    lv_label_set_text(ui_LabelTimePassedValueWaterLeak, "00: 00: 00: 00");
    lv_obj_set_style_text_color(ui_LabelTimePassedValueWaterLeak, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTimePassedValueWaterLeak, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTimePassedValueWaterLeak, &ui_font_Font12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelTimePassedValueWaterLeak, lv_color_hex(0xFFFFFF),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelTimePassedValueWaterLeak, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LabelTimePassedValueWaterLeak, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_LabelTimePassedValueWaterLeak, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTopWaterLeak = lv_obj_create(ui_PanelSensorNodeWaterLeak);
    lv_obj_set_width(ui_PanelTopWaterLeak, LV_SIZE_CONTENT);   
    lv_obj_set_height(ui_PanelTopWaterLeak, LV_SIZE_CONTENT);    
    lv_obj_set_x(ui_PanelTopWaterLeak, 65);
    lv_obj_set_y(ui_PanelTopWaterLeak, 67);
    lv_obj_set_align(ui_PanelTopWaterLeak, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelTopWaterLeak, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelTopWaterLeak, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelTopWaterLeak, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelTopWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelTopWaterLeak, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTopWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelTopWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelTopWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelTopWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelTopWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelTopWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelTopWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelTopWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageButtonTopWaterLeak = lv_imgbtn_create(ui_PanelTopWaterLeak);
    lv_imgbtn_set_src(ui_ImageButtonTopWaterLeak, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_set_top_png, NULL);
    lv_imgbtn_set_src(ui_ImageButtonTopWaterLeak, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_cancel_set_top_png, NULL);
    lv_imgbtn_set_src(ui_ImageButtonTopWaterLeak, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImageButtonTopWaterLeak, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_set_top_png, NULL);
    lv_imgbtn_set_src(ui_ImageButtonTopWaterLeak, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_cancel_set_top_png, NULL);
    lv_imgbtn_set_src(ui_ImageButtonTopWaterLeak, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImageButtonTopWaterLeak, 25);
    lv_obj_set_height(ui_ImageButtonTopWaterLeak, 25);
    lv_obj_set_x(ui_ImageButtonTopWaterLeak, 0);
    lv_obj_set_y(ui_ImageButtonTopWaterLeak, 1);
    lv_obj_add_flag(ui_ImageButtonTopWaterLeak, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_border_color(ui_ImageButtonTopWaterLeak, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ImageButtonTopWaterLeak, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ImageButtonTopWaterLeak, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ImageButtonTopWaterLeak, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_ImageButtonTopWaterLeak, lv_color_hex(0x4BD5CB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ImageButtonTopWaterLeak, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSensorNodeDeleteWaterLeak = lv_obj_create(ui_PanelSensorWaterLeak);
    lv_obj_set_width(ui_PanelSensorNodeDeleteWaterLeak, 156);
    lv_obj_set_height(ui_PanelSensorNodeDeleteWaterLeak, 160);
    lv_obj_set_align(ui_PanelSensorNodeDeleteWaterLeak, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelSensorNodeDeleteWaterLeak, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelSensorNodeDeleteWaterLeak, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSensorNodeDeleteWaterLeak, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSensorNodeDeleteWaterLeak, lv_color_hex(0x162137), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSensorNodeDeleteWaterLeak, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSensorNodeDeleteWaterLeak, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelSensorNodeDeleteWaterLeak, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageDeleteWaterLeak = lv_img_create(ui_PanelSensorNodeDeleteWaterLeak);
    lv_img_set_src(ui_ImageDeleteWaterLeak, &ui_img_delete_png);
    lv_obj_set_width(ui_ImageDeleteWaterLeak, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageDeleteWaterLeak, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageDeleteWaterLeak, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageDeleteWaterLeak, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageDeleteWaterLeak, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_transform_zoom(ui_ImageDeleteWaterLeak, 288, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_add_event_cb(ui_SliderSignalStrengthWaterLeak, ui_event_SliderSignalStrengthWaterLeak, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderBatteryWaterLeak, ui_event_SliderBatteryWaterLeak, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImageButtonTopWaterLeak, ui_event_ImageButtonTopWaterLeak, LV_EVENT_ALL, ui_PanelSensorWaterLeak);
    lv_obj_add_event_cb(ui_PanelSensorNodeWaterLeak, ui_event_PanelSensorNodeWaterLeak_1, LV_EVENT_ALL, ui_PanelSensorNodeWaterLeak);
    lv_obj_add_event_cb(ui_PanelSensorNodeWaterLeak, ui_event_PanelSensorNodeWaterLeak_2, LV_EVENT_ALL, ui_PanelSensorNodeDeleteWaterLeak);
    lv_obj_add_event_cb(ui_ImageDeleteWaterLeak, ui_event_ImageDeleteWaterLeak, LV_EVENT_ALL, ui_PanelSensorWaterLeak);
    lv_obj_add_event_cb(ui_PanelSensorNodeDeleteWaterLeak, ui_event_PanelSensorNodeDeleteWaterLeak_1, LV_EVENT_ALL, ui_PanelSensorNodeWaterLeak);
    lv_obj_add_event_cb(ui_PanelSensorNodeDeleteWaterLeak, ui_event_PanelSensorNodeDeleteWaterLeak_2, LV_EVENT_ALL, ui_PanelSensorNodeDeleteWaterLeak);

    panel_with_type union_sensor;

    union_sensor.panel_union.water_leak.ui_PanelSensorWaterLeak = ui_PanelSensorWaterLeak;
    union_sensor.panel_union.water_leak.ui_PanelSensorNodeWaterLeak = ui_PanelSensorNodeWaterLeak;
    union_sensor.panel_union.water_leak.ui_PanelChartWaterLeak = ui_PanelChartWaterLeak;
    union_sensor.panel_union.water_leak.ui_ChartDisplayWaterLeak = ui_ChartDisplayWaterLeak;
    union_sensor.panel_union.water_leak.ui_LabelTypeWaterLeak = ui_LabelTypeWaterLeak;
    union_sensor.panel_union.water_leak.ui_LabelDevEUIWaterLeak = ui_LabelDevEUIWaterLeak;
    union_sensor.panel_union.water_leak.ui_LabelNameWaterLeak = ui_LabelNameWaterLeak;
    union_sensor.panel_union.water_leak.ui_PanelCurrentStatusLeakingWaterLeak = ui_PanelCurrentStatusLeakingWaterLeak;
    union_sensor.panel_union.water_leak.ui_LabelCurrentStatusLeakingWaterLeak = ui_LabelCurrentStatusLeakingWaterLeak;
    union_sensor.panel_union.water_leak.ui_ImageCurrentStatusLeakingWaterLeak = ui_ImageCurrentStatusLeakingWaterLeak;
    union_sensor.panel_union.water_leak.ui_PanelCurrentStatusNormalWaterLeak = ui_PanelCurrentStatusNormalWaterLeak;
    union_sensor.panel_union.water_leak.ui_LabelCurrentStatusNormalWaterLeak = ui_LabelCurrentStatusNormalWaterLeak;
    union_sensor.panel_union.water_leak.ui_ImageCurrentStatusNormalWaterLeak = ui_ImageCurrentStatusNormalWaterLeak;
    union_sensor.panel_union.water_leak.ui_PanelSignalStrengthWaterLeak = ui_PanelSignalStrengthWaterLeak;
    union_sensor.panel_union.water_leak.ui_ImageSignalStrengthWaterLeak = ui_ImageSignalStrengthWaterLeak;
    union_sensor.panel_union.water_leak.ui_SliderSignalStrengthWaterLeak = ui_SliderSignalStrengthWaterLeak;
    union_sensor.panel_union.water_leak.ui_LabelSignalStrengthValueWaterLeak = ui_LabelSignalStrengthValueWaterLeak;
    union_sensor.panel_union.water_leak.ui_PanelBatteryWaterLeak = ui_PanelBatteryWaterLeak;
    union_sensor.panel_union.water_leak.ui_ImageBatteryWaterLeak = ui_ImageBatteryWaterLeak;
    union_sensor.panel_union.water_leak.ui_SliderBatteryWaterLeak = ui_SliderBatteryWaterLeak;
    union_sensor.panel_union.water_leak.ui_LabelBatteryWaterLeak = ui_LabelBatteryWaterLeak;
    union_sensor.panel_union.water_leak.ui_PanelLastWaterLeak = ui_PanelLastWaterLeak;
    union_sensor.panel_union.water_leak.ui_LabelLastWaterLeak = ui_LabelLastWaterLeak;
    union_sensor.panel_union.water_leak.ui_LabelLastValueWaterLeak = ui_LabelLastValueWaterLeak;
    union_sensor.panel_union.water_leak.ui_PanelTimesWaterLeak = ui_PanelTimesWaterLeak;
    union_sensor.panel_union.water_leak.ui_LabelTimesWaterLeak = ui_LabelTimesWaterLeak;
    union_sensor.panel_union.water_leak.ui_LabelTimesValueWaterLeak = ui_LabelTimesValueWaterLeak;
    union_sensor.panel_union.water_leak.ui_PanelTimePassedWaterLeak = ui_PanelTimePassedWaterLeak;
    union_sensor.panel_union.water_leak.ui_ImageTimePassedWaterLeak = ui_ImageTimePassedWaterLeak;
    union_sensor.panel_union.water_leak.ui_LabelTimePassedValueWaterLeak = ui_LabelTimePassedValueWaterLeak;
    union_sensor.panel_union.water_leak.ui_PanelTopWaterLeak = ui_PanelTopWaterLeak;
    union_sensor.panel_union.water_leak.ui_ImageButtonTopWaterLeak = ui_ImageButtonTopWaterLeak;
    union_sensor.panel_union.water_leak.ui_PanelSensorNodeDeleteWaterLeak = ui_PanelSensorNodeDeleteWaterLeak;
    union_sensor.panel_union.water_leak.ui_ImageDeleteWaterLeak = ui_ImageDeleteWaterLeak;

    union_sensor.panel_type = WATER_LEAK_TYPE;

    lv_obj_set_x(union_sensor.panel_union.water_leak.ui_PanelSensorWaterLeak, x_by_index(index));
    lv_obj_set_y(union_sensor.panel_union.water_leak.ui_PanelSensorWaterLeak, y_by_index(index));
    
    return union_sensor;
}
