// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_ALARM_EVENTS_H
#define _UI_ALARM_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void PinToTopAlarm(lv_event_t * e);
void UnpinFromTopAlarm(lv_event_t * e);
void DeleteObjectAlarm(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
