// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui_occupied.h"

void PinToTopOccupied(lv_event_t * e)
{
	// Your code here
}

void UnpinFromTopOccupied(lv_event_t * e)
{
	// Your code here
}

void DeleteObjectOccupied(lv_event_t * e) // void delete_object_occupied(lv_event_t * e)
{
	// Your code here
	panel_all * panel = find_upper_by_SensorPanel(arr_get(),((lv_obj_t *)(e->user_data)));
	size_t index = panel->panel_obj_index;
	deleteElement(arr_get(), index);
}
