// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

#include "ui_occupied.h"
#include "../sort.h"

///////////////////// VARIABLES ////////////////////


lv_obj_t * ui_PanelSensorOccupied;
void ui_event_PanelSensorNodeOccupied_1(lv_event_t * e);
void ui_event_PanelSensorNodeOccupied_2(lv_event_t * e);
lv_obj_t * ui_PanelSensorNodeOccupied;
lv_obj_t * ui_PanelChartOccupied;
lv_obj_t * ui_ChartDisplayOccupied;
lv_obj_t * ui_LabelTypeOccupied;
lv_obj_t * ui_LabelFportOccupied;
lv_obj_t * ui_LabelDevEUIOccupied;
lv_obj_t * ui_LabelNameOccupied;
lv_obj_t * ui_PanelSignalStrengthOccupied;
lv_obj_t * ui_ImageSignalStrengthOccupied;
void ui_event_SliderSignalStrengthOccupied(lv_event_t * e);
lv_obj_t * ui_SliderSignalStrengthOccupied;
lv_obj_t * ui_LabelSignalStrengthValueOccupied;
lv_obj_t * ui_PanelBatteryOccupied;
lv_obj_t * ui_ImageBatteryOccupied;
void ui_event_SliderBatteryOccupied(lv_event_t * e);
lv_obj_t * ui_SliderBatteryOccupied;
lv_obj_t * ui_LabelBatteryOccupied;
lv_obj_t * ui_PanelLabelOccupied;
lv_obj_t * ui_LabelOccupiedOccupied;
lv_obj_t * ui_LabelFreeOccupied;
lv_obj_t * ui_PanelImageOccupied;
lv_obj_t * ui_ImageOccupiedOccupied;
lv_obj_t * ui_ImageFreeOccupied;
lv_obj_t * ui_PanelTimePassedOccupied;
lv_obj_t * ui_ImageTimePassedOccupied;
lv_obj_t * ui_LabelTimePassedValueOccupied;
lv_obj_t * ui_PanelTopOccupied;
void ui_event_ImageButtonTopOccupied(lv_event_t * e);
lv_obj_t * ui_ImageButtonTopOccupied;
void ui_event_PanelSensorNodeDeleteOccupied_1(lv_event_t * e);
void ui_event_PanelSensorNodeDeleteOccupied_2(lv_event_t * e);
lv_obj_t * ui_PanelSensorNodeDeleteOccupied;
void ui_event_ImageDeleteOccupied(lv_event_t * e);
lv_obj_t * ui_ImageDeleteOccupied;


///////////////////// FUNCTIONS ////////////////////
void ui_event_PanelSensorNodeOccupied_1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        // _ui_flag_modify(ui_PanelSensorNodeDeleteOccupied, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        // _ui_flag_modify(ui_PanelSensorNodeOccupied, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify( ((lv_obj_t *)(e->user_data)), LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_PanelSensorNodeOccupied_2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_flag_modify( ((lv_obj_t *)(e->user_data)), LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_SliderSignalStrengthOccupied(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_LabelSignalStrengthValueOccupied, target, "Rssi: ", "");
    }
}
void ui_event_SliderBatteryOccupied(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_LabelBatteryOccupied, target, "", "mV");
    }
}
void ui_event_ImageButtonTopOccupied(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        // PinToTopOccupied(e);
        reposArray1(arr_get(), ((lv_obj_t *)(e->user_data)));
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        // UnpinFromTopOccupied(e);
        reposArray2(arr_get(), ((lv_obj_t *)(e->user_data)));
    }
}
void ui_event_PanelSensorNodeDeleteOccupied_1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        // _ui_flag_modify(ui_PanelSensorNodeDeleteOccupied, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        // _ui_flag_modify(ui_PanelSensorNodeOccupied, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify( ((lv_obj_t *)(e->user_data)), LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_PanelSensorNodeDeleteOccupied_2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify( ((lv_obj_t *)(e->user_data)), LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_ImageDeleteOccupied(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        DeleteObjectOccupied(e); // delete_object_occupied(e);
    }
}
