// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_OCCUPIED_H
#define _UI_OCCUPIED_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_occupied_events.h"


extern lv_obj_t * ui_PanelSensorOccupied;
void ui_event_PanelSensorNodeOccupied_1(lv_event_t * e);
void ui_event_PanelSensorNodeOccupied_2(lv_event_t * e);
extern lv_obj_t * ui_PanelSensorNodeOccupied;
extern lv_obj_t * ui_PanelChartOccupied;
extern lv_obj_t * ui_ChartDisplayOccupied;
extern lv_obj_t * ui_LabelTypeOccupied;
extern lv_obj_t * ui_LabelDevEUIOccupied;
extern lv_obj_t * ui_LabelNameOccupied;
extern lv_obj_t * ui_PanelSignalStrengthOccupied;
extern lv_obj_t * ui_ImageSignalStrengthOccupied;
void ui_event_SliderSignalStrengthOccupied(lv_event_t * e);
extern lv_obj_t * ui_SliderSignalStrengthOccupied;
extern lv_obj_t * ui_LabelSignalStrengthValueOccupied;
extern lv_obj_t * ui_PanelBatteryOccupied;
extern lv_obj_t * ui_ImageBatteryOccupied;
void ui_event_SliderBatteryOccupied(lv_event_t * e);
extern lv_obj_t * ui_SliderBatteryOccupied;
extern lv_obj_t * ui_LabelBatteryOccupied;
extern lv_obj_t * ui_PanelLabelOccupied;
extern lv_obj_t * ui_LabelOccupiedOccupied;
extern lv_obj_t * ui_LabelFreeOccupied;
extern lv_obj_t * ui_PanelImageOccupied;
extern lv_obj_t * ui_ImageOccupiedOccupied;
extern lv_obj_t * ui_ImageFreeOccupied;
extern lv_obj_t * ui_PanelTimePassedOccupied;
extern lv_obj_t * ui_ImageTimePassedOccupied;
extern lv_obj_t * ui_LabelTimePassedValueOccupied;
extern lv_obj_t * ui_PanelTopOccupied;
void ui_event_ImageButtonTopOccupied(lv_event_t * e);
extern lv_obj_t * ui_ImageButtonTopOccupied;
void ui_event_PanelSensorNodeDeleteOccupied_1(lv_event_t * e);
void ui_event_PanelSensorNodeDeleteOccupied_2(lv_event_t * e);
extern lv_obj_t * ui_PanelSensorNodeDeleteOccupied;
void ui_event_ImageDeleteOccupied(lv_event_t * e);
extern lv_obj_t * ui_ImageDeleteOccupied;



LV_IMG_DECLARE(ui__temporary_image);
LV_IMG_DECLARE(ui_img_signal_empty_png);    // assets/Signal_Empty.png
LV_IMG_DECLARE(ui_img_signal_full_png);    // assets/Signal_Full.png
LV_IMG_DECLARE(ui_img_battery_empty_png);    // assets/Battery_Empty.png
LV_IMG_DECLARE(ui_img_battery_full_png);    // assets/Battery_Full.png
LV_IMG_DECLARE(ui_img_arc_red_png);    // assets/Arc_Red.png
LV_IMG_DECLARE(ui_img_arc_green_png);    // assets/Arc_Green.png
LV_IMG_DECLARE(ui_img_last_seen_png);    // assets/Last_Seen.png
LV_IMG_DECLARE(ui_img_set_top_png);    // assets/Set_Top.png
LV_IMG_DECLARE(ui_img_cancel_set_top_png);    // assets/Cancel_Set_Top.png
LV_IMG_DECLARE(ui_img_delete_png);    // assets/Delete.png



LV_FONT_DECLARE(ui_font_Font12);
LV_FONT_DECLARE(ui_font_Font16);




#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
