// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

#include "ui_door.h"
#include "../sort.h"

///////////////////// VARIABLES ////////////////////



lv_obj_t * ui_PanelSensorDoor;
void ui_event_PanelSensorNodeDoor_1(lv_event_t * e);
void ui_event_PanelSensorNodeDoor_2(lv_event_t * e);
lv_obj_t * ui_PanelSensorNodeDoor;
lv_obj_t * ui_PanelChartDoor;
lv_obj_t * ui_ChartDisplayDoor;
lv_obj_t * ui_LabelTypeDoor;
lv_obj_t * ui_LabelDevEUIDoor;
lv_obj_t * ui_LabelNameDoor;
lv_obj_t * ui_PanelSignalStrengthDoor;
lv_obj_t * ui_ImageSignalStrengthDoor;
void ui_event_SliderSignalStrengthDoor(lv_event_t * e);
lv_obj_t * ui_SliderSignalStrengthDoor;
lv_obj_t * ui_LabelSignalStrengthValueDoor;
lv_obj_t * ui_PanelBatteryDoor;
lv_obj_t * ui_ImageBatteryDoor;
void ui_event_SliderBatteryDoor(lv_event_t * e);
lv_obj_t * ui_SliderBatteryDoor;
lv_obj_t * ui_LabelBatteryDoor;
lv_obj_t * ui_PanelCurrentStatusOpenDoor;
lv_obj_t * ui_LabelCurrentStatusOpenDoor;
lv_obj_t * ui_ImageCurrentStatusOpenDoor;
lv_obj_t * ui_PanelCurrentStatusCloseDoor;
lv_obj_t * ui_LabelCurrentStatusCloseDoor;
lv_obj_t * ui_ImageCurrentStatusCloseDoor;
lv_obj_t * ui_PanelLastDoor;
lv_obj_t * ui_LabelLastDoor;
lv_obj_t * ui_LabelLastValueDoor;
lv_obj_t * ui_PanelTimesDoor;
lv_obj_t * ui_LabelTimesDoor;
lv_obj_t * ui_LabelTimesValueDoor;
lv_obj_t * ui_PanelTimePassedDoor;
lv_obj_t * ui_ImageTimePassedDoor;
lv_obj_t * ui_LabelTimePassedValueDoor;
lv_obj_t * ui_PanelTopDoor;
void ui_event_ImageButtonTopDoor(lv_event_t * e);
lv_obj_t * ui_ImageButtonTopDoor;
void ui_event_PanelSensorNodeDeleteDoor_1(lv_event_t * e);
void ui_event_PanelSensorNodeDeleteDoor_2(lv_event_t * e);
lv_obj_t * ui_PanelSensorNodeDeleteDoor;
void ui_event_ImageDeleteDoor(lv_event_t * e);
lv_obj_t * ui_ImageDeleteDoor;



///////////////////// FUNCTIONS ////////////////////
void ui_event_PanelSensorNodeDoor_1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        // _ui_flag_modify(ui_PanelSensorNodeDoor, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify( ((lv_obj_t *)(e->user_data)), LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        
    }
}
void ui_event_PanelSensorNodeDoor_2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        // _ui_flag_modify(ui_PanelSensorNodeDeleteDoor, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify( ((lv_obj_t *)(e->user_data)), LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_SliderSignalStrengthDoor(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_LabelSignalStrengthValueDoor, target, "Rssi: ", "");
    }
}
void ui_event_SliderBatteryDoor(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_LabelBatteryDoor, target, "", "mV");
    }
}
void ui_event_ImageButtonTopDoor(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        // PinToTopDoor(e);
        reposArray1(arr_get(), ((lv_obj_t *)(e->user_data)));
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        // UnpinFromTopDoor(e);
        reposArray2(arr_get(), ((lv_obj_t *)(e->user_data)));
    }
}
void ui_event_PanelSensorNodeDeleteDoor_1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        // _ui_flag_modify(ui_PanelSensorNodeDeleteDoor, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        // _ui_flag_modify(ui_PanelSensorNodeDoor, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify( ((lv_obj_t *)(e->user_data)), LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_PanelSensorNodeDeleteDoor_2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify( ((lv_obj_t *)(e->user_data)), LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_ImageDeleteDoor(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        DeleteObjectDoor(e);
    }
}
