// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_DOOR_H
#define _UI_DOOR_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_door_events.h"


extern lv_obj_t * ui_PanelSensorDoor;
void ui_event_PanelSensorNodeDoor_1(lv_event_t * e);
void ui_event_PanelSensorNodeDoor_2(lv_event_t * e);
extern lv_obj_t * ui_PanelSensorNodeDoor;
extern lv_obj_t * ui_PanelChartDoor;
extern lv_obj_t * ui_ChartDisplayDoor;
extern lv_obj_t * ui_LabelTypeDoor;
extern lv_obj_t * ui_LabelFportDoor;
extern lv_obj_t * ui_LabelDevEUIDoor;
extern lv_obj_t * ui_LabelNameDoor;
extern lv_obj_t * ui_PanelSignalStrengthDoor;
extern lv_obj_t * ui_ImageSignalStrengthDoor;
void ui_event_SliderSignalStrengthDoor(lv_event_t * e);
extern lv_obj_t * ui_SliderSignalStrengthDoor;
extern lv_obj_t * ui_LabelSignalStrengthValueDoor;
extern lv_obj_t * ui_PanelBatteryDoor;
extern lv_obj_t * ui_ImageBatteryDoor;
void ui_event_SliderBatteryDoor(lv_event_t * e);
extern lv_obj_t * ui_SliderBatteryDoor;
extern lv_obj_t * ui_LabelBatteryDoor;
extern lv_obj_t * ui_PanelCurrentStatusOpenDoor;
extern lv_obj_t * ui_LabelCurrentStatusOpenDoor;
extern lv_obj_t * ui_ImageCurrentStatusOpenDoor;
extern lv_obj_t * ui_PanelCurrentStatusCloseDoor;
extern lv_obj_t * ui_LabelCurrentStatusCloseDoor;
extern lv_obj_t * ui_ImageCurrentStatusCloseDoor;
extern lv_obj_t * ui_PanelLastDoor;
extern lv_obj_t * ui_LabelLastDoor;
extern lv_obj_t * ui_LabelLastValueDoor;
extern lv_obj_t * ui_PanelTimesDoor;
extern lv_obj_t * ui_LabelTimesDoor;
extern lv_obj_t * ui_LabelTimesValueDoor;
extern lv_obj_t * ui_PanelTimePassedDoor;
extern lv_obj_t * ui_ImageTimePassedDoor;
extern lv_obj_t * ui_LabelTimePassedValueDoor;
extern lv_obj_t * ui_PanelTopDoor;
void ui_event_ImageButtonTopDoor(lv_event_t * e);
extern lv_obj_t * ui_ImageButtonTopDoor;
void ui_event_PanelSensorNodeDeleteDoor_1(lv_event_t * e);
void ui_event_PanelSensorNodeDeleteDoor_2(lv_event_t * e);
extern lv_obj_t * ui_PanelSensorNodeDeleteDoor;
void ui_event_ImageDeleteDoor(lv_event_t * e);
extern lv_obj_t * ui_ImageDeleteDoor;


LV_IMG_DECLARE(ui__temporary_image);
LV_IMG_DECLARE(ui_img_signal_empty_png);    // assets/Signal_Empty.png
LV_IMG_DECLARE(ui_img_signal_full_png);    // assets/Signal_Full.png
LV_IMG_DECLARE(ui_img_battery_empty_png);    // assets/Battery_Empty.png
LV_IMG_DECLARE(ui_img_battery_full_png);    // assets/Battery_Full.png
LV_IMG_DECLARE(ui_img_door_open_png);    // assets/Door_Open.png
LV_IMG_DECLARE(ui_img_door_close_png);    // assets/Door_Close.png
LV_IMG_DECLARE(ui_img_last_seen_png);    // assets/Last_Seen.png
LV_IMG_DECLARE(ui_img_set_top_png);    // assets/Set_Top.png
LV_IMG_DECLARE(ui_img_cancel_set_top_png);    // assets/Cancel_Set_Top.png
LV_IMG_DECLARE(ui_img_delete_png);    // assets/Delete.png


LV_FONT_DECLARE(ui_font_Font12);
LV_FONT_DECLARE(ui_font_Font16);


#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
