// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_DOOR_EVENTS_H
#define _UI_DOOR_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void PinToTopDoor(lv_event_t * e);
void UnpinFromTopDoor(lv_event_t * e);
void DeleteObjectDoor(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
