// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

#include "ui_water_leak.h"
#include "../sort.h"

///////////////////// VARIABLES ////////////////////


lv_obj_t * ui_PanelSensorWaterLeak;
void ui_event_PanelSensorNodeWaterLeak_1(lv_event_t * e);
void ui_event_PanelSensorNodeWaterLeak_2(lv_event_t * e);
lv_obj_t * ui_PanelSensorNodeWaterLeak;
lv_obj_t * ui_PanelChartWaterLeak;
lv_obj_t * ui_ChartDisplayWaterLeak;
lv_obj_t * ui_LabelTypeWaterLeak;
lv_obj_t * ui_LabelFportWaterLeak;
lv_obj_t * ui_LabelDevEUIWaterLeak;
lv_obj_t * ui_LabelNameWaterLeak;
lv_obj_t * ui_PanelCurrentStatusLeakingWaterLeak;
lv_obj_t * ui_LabelCurrentStatusLeakingWaterLeak;
lv_obj_t * ui_ImageCurrentStatusLeakingWaterLeak;
lv_obj_t * ui_PanelCurrentStatusNormalWaterLeak;
lv_obj_t * ui_LabelCurrentStatusNormalWaterLeak;
lv_obj_t * ui_ImageCurrentStatusNormalWaterLeak;
lv_obj_t * ui_PanelSignalStrengthWaterLeak;
lv_obj_t * ui_ImageSignalStrengthWaterLeak;
void ui_event_SliderSignalStrengthWaterLeak(lv_event_t * e);
lv_obj_t * ui_SliderSignalStrengthWaterLeak;
lv_obj_t * ui_LabelSignalStrengthValueWaterLeak;
lv_obj_t * ui_PanelBatteryWaterLeak;
lv_obj_t * ui_ImageBatteryWaterLeak;
void ui_event_SliderBatteryWaterLeak(lv_event_t * e);
lv_obj_t * ui_SliderBatteryWaterLeak;
lv_obj_t * ui_LabelBatteryWaterLeak;
lv_obj_t * ui_PanelLastWaterLeak;
lv_obj_t * ui_LabelLastWaterLeak;
lv_obj_t * ui_LabelLastValueWaterLeak;
lv_obj_t * ui_PanelTimesWaterLeak;
lv_obj_t * ui_LabelTimesWaterLeak;
lv_obj_t * ui_LabelTimesValueWaterLeak;
lv_obj_t * ui_PanelTimePassedWaterLeak;
lv_obj_t * ui_ImageTimePassedWaterLeak;
lv_obj_t * ui_LabelTimePassedValueWaterLeak;
lv_obj_t * ui_PanelTopWaterLeak;
void ui_event_ImageButtonTopWaterLeak(lv_event_t * e);
lv_obj_t * ui_ImageButtonTopWaterLeak;
void ui_event_PanelSensorNodeDeleteWaterLeak_1(lv_event_t * e);
void ui_event_PanelSensorNodeDeleteWaterLeak_2(lv_event_t * e);
lv_obj_t * ui_PanelSensorNodeDeleteWaterLeak;
void ui_event_ImageDeleteWaterLeak(lv_event_t * e);
lv_obj_t * ui_ImageDeleteWaterLeak;

///////////////////// FUNCTIONS ////////////////////
void ui_event_PanelSensorNodeWaterLeak_1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        // _ui_flag_modify(ui_PanelSensorNodeWaterLeak, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify( ((lv_obj_t *)(e->user_data)), LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_PanelSensorNodeWaterLeak_2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        // _ui_flag_modify(ui_PanelSensorNodeDeleteWaterLeak, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify( ((lv_obj_t *)(e->user_data)), LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_SliderSignalStrengthWaterLeak(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_LabelSignalStrengthValueWaterLeak, target, "Rssi: ", "");
    }
}
void ui_event_SliderBatteryWaterLeak(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_LabelBatteryWaterLeak, target, "", "mV");
    }
}
void ui_event_ImageButtonTopWaterLeak(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        // PinToTopWaterLeak(e);
        reposArray1(arr_get(), ((lv_obj_t *)(e->user_data)));
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        // UnpinFromTopWaterLeak(e);
        reposArray2(arr_get(), ((lv_obj_t *)(e->user_data)));
    }
}
void ui_event_PanelSensorNodeDeleteWaterLeak_1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        // _ui_flag_modify(ui_PanelSensorNodeWaterLeak, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify( ((lv_obj_t *)(e->user_data)), LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_PanelSensorNodeDeleteWaterLeak_2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        // _ui_flag_modify(ui_PanelSensorNodeDeleteWaterLeak, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify( ((lv_obj_t *)(e->user_data)), LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_ImageDeleteWaterLeak(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        DeleteObjectWaterLeak(e);
    }
}
