// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_WATER_LEAK_H
#define _UI_WATER_LEAK_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_water_leak_events.h"


extern lv_obj_t * ui_PanelSensorWaterLeak;
void ui_event_PanelSensorNodeWaterLeak_1(lv_event_t * e);
void ui_event_PanelSensorNodeWaterLeak_2(lv_event_t * e);
extern lv_obj_t * ui_PanelSensorNodeWaterLeak;
extern lv_obj_t * ui_PanelChartWaterLeak;
extern lv_obj_t * ui_ChartDisplayWaterLeak;
extern lv_obj_t * ui_LabelTypeWaterLeak;
extern lv_obj_t * ui_LabelFportWaterLeak;
extern lv_obj_t * ui_LabelDevEUIWaterLeak;
extern lv_obj_t * ui_LabelNameWaterLeak;
extern lv_obj_t * ui_PanelCurrentStatusLeakingWaterLeak;
extern lv_obj_t * ui_LabelCurrentStatusLeakingWaterLeak;
extern lv_obj_t * ui_ImageCurrentStatusLeakingWaterLeak;
extern lv_obj_t * ui_PanelCurrentStatusNormalWaterLeak;
extern lv_obj_t * ui_LabelCurrentStatusNormalWaterLeak;
extern lv_obj_t * ui_ImageCurrentStatusNormalWaterLeak;
extern lv_obj_t * ui_PanelSignalStrengthWaterLeak;
extern lv_obj_t * ui_ImageSignalStrengthWaterLeak;
void ui_event_SliderSignalStrengthWaterLeak(lv_event_t * e);
extern lv_obj_t * ui_SliderSignalStrengthWaterLeak;
extern lv_obj_t * ui_LabelSignalStrengthValueWaterLeak;
extern lv_obj_t * ui_PanelBatteryWaterLeak;
extern lv_obj_t * ui_ImageBatteryWaterLeak;
void ui_event_SliderBatteryWaterLeak(lv_event_t * e);
extern lv_obj_t * ui_SliderBatteryWaterLeak;
extern lv_obj_t * ui_LabelBatteryWaterLeak;
extern lv_obj_t * ui_PanelLastWaterLeak;
extern lv_obj_t * ui_LabelLastWaterLeak;
extern lv_obj_t * ui_LabelLastValueWaterLeak;
extern lv_obj_t * ui_PanelTimesWaterLeak;
extern lv_obj_t * ui_LabelTimesWaterLeak;
extern lv_obj_t * ui_LabelTimesValueWaterLeak;
extern lv_obj_t * ui_PanelTimePassedWaterLeak;
extern lv_obj_t * ui_ImageTimePassedWaterLeak;
extern lv_obj_t * ui_LabelTimePassedValueWaterLeak;
extern lv_obj_t * ui_PanelTopWaterLeak;
void ui_event_ImageButtonTopWaterLeak(lv_event_t * e);
extern lv_obj_t * ui_ImageButtonTopWaterLeak;
void ui_event_PanelSensorNodeDeleteWaterLeak_1(lv_event_t * e);
void ui_event_PanelSensorNodeDeleteWaterLeak_2(lv_event_t * e);
extern lv_obj_t * ui_PanelSensorNodeDeleteWaterLeak;
void ui_event_ImageDeleteWaterLeak(lv_event_t * e);
extern lv_obj_t * ui_ImageDeleteWaterLeak;



LV_IMG_DECLARE(ui__temporary_image);
LV_IMG_DECLARE(ui_img_leaking_png);    // assets/Leaking.png
LV_IMG_DECLARE(ui_img_normal_png);    // assets/Normal.png
LV_IMG_DECLARE(ui_img_signal_empty_png);    // assets/Signal_Empty.png
LV_IMG_DECLARE(ui_img_signal_full_png);    // assets/Signal_Full.png
LV_IMG_DECLARE(ui_img_battery_empty_png);    // assets/Battery_Empty.png
LV_IMG_DECLARE(ui_img_battery_full_png);    // assets/Battery_Full.png
LV_IMG_DECLARE(ui_img_last_seen_png);    // assets/Last_Seen.png
LV_IMG_DECLARE(ui_img_set_top_png);    // assets/Set_Top.png
LV_IMG_DECLARE(ui_img_cancel_set_top_png);    // assets/Cancel_Set_Top.png
LV_IMG_DECLARE(ui_img_delete_png);    // assets/Delete.png



LV_FONT_DECLARE(ui_font_Font12);
LV_FONT_DECLARE(ui_font_Font16);



#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
