// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui_tem_hum.h"
#include "../../sort.h"
#include "ui.h"

panel_with_type create_tem_hum(uint8_t index, lv_obj_t *parent)
{
    ui_PanelSensorTemHum = lv_obj_create(parent);  
    lv_obj_set_width(ui_PanelSensorTemHum, 156);
    lv_obj_set_height(ui_PanelSensorTemHum, 160);
    lv_obj_set_x(ui_PanelSensorTemHum, -249);
    lv_obj_set_y(ui_PanelSensorTemHum, -90);
    lv_obj_set_align(ui_PanelSensorTemHum, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSensorTemHum, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSensorTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSensorTemHum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSensorTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSensorTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSensorNodeTemHum = lv_obj_create(ui_PanelSensorTemHum);
    lv_obj_set_width(ui_PanelSensorNodeTemHum, 156);
    lv_obj_set_height(ui_PanelSensorNodeTemHum, 160);
    lv_obj_set_align(ui_PanelSensorNodeTemHum, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSensorNodeTemHum, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSensorNodeTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSensorNodeTemHum, lv_color_hex(0x162137), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSensorNodeTemHum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSensorNodeTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelChartTemHum = lv_obj_create(ui_PanelSensorNodeTemHum);
    lv_obj_set_width(ui_PanelChartTemHum, 156);
    lv_obj_set_height(ui_PanelChartTemHum, 50);
    lv_obj_set_x(ui_PanelChartTemHum, 0);
    lv_obj_set_y(ui_PanelChartTemHum, -56);
    lv_obj_set_align(ui_PanelChartTemHum, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelChartTemHum, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelChartTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelChartTemHum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelChartTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelChartTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChartDisplayTemHum = lv_chart_create(ui_PanelChartTemHum);
    lv_obj_set_width(ui_ChartDisplayTemHum, 156);
    lv_obj_set_height(ui_ChartDisplayTemHum, 50);
    lv_obj_set_align(ui_ChartDisplayTemHum, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ChartDisplayTemHum, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_chart_set_type(ui_ChartDisplayTemHum, LV_CHART_TYPE_NONE);
    lv_chart_set_range(ui_ChartDisplayTemHum, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_chart_set_div_line_count(ui_ChartDisplayTemHum, 0, 0);
    lv_chart_set_axis_tick(ui_ChartDisplayTemHum, LV_CHART_AXIS_PRIMARY_X, 0, 0, 0, 0, false, 50);
    lv_chart_set_axis_tick(ui_ChartDisplayTemHum, LV_CHART_AXIS_PRIMARY_Y, 0, 0, 0, 0, false, 100);
    lv_chart_set_axis_tick(ui_ChartDisplayTemHum, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);
    lv_chart_series_t * ui_ChartDisplayTemHum_series_1 = lv_chart_add_series(ui_ChartDisplayTemHum, lv_color_hex(0xFFFFFF),
                                                                       LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_ChartDisplayTemHum_series_1_array[] = { 0, 10, 20, 50, 80, 90, 40, 20, 40, 0 };
    lv_chart_set_ext_y_array(ui_ChartDisplayTemHum, ui_ChartDisplayTemHum_series_1, ui_ChartDisplayTemHum_series_1_array);
    lv_obj_set_style_radius(ui_ChartDisplayTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ChartDisplayTemHum, lv_color_hex(0x6F7BCE), LV_PART_MAIN | LV_STATE_DEFAULT); // 0x86ACD4
    lv_obj_set_style_bg_opa(ui_ChartDisplayTemHum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ChartDisplayTemHum, lv_color_hex(0x0B0E32), LV_PART_MAIN | LV_STATE_DEFAULT); // 0x353A83
    lv_obj_set_style_bg_main_stop(ui_ChartDisplayTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_ChartDisplayTemHum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ChartDisplayTemHum, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_ChartDisplayTemHum, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ChartDisplayTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_line_color(ui_ChartDisplayTemHum, lv_color_hex(0x2121E2), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_ChartDisplayTemHum, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(ui_ChartDisplayTemHum, 2, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_set_style_line_width(ui_ChartDisplayTemHum, 2, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_LabelTypeTemHum = lv_label_create(ui_ChartDisplayTemHum);
    lv_obj_set_width(ui_LabelTypeTemHum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTypeTemHum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTypeTemHum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTypeTemHum, "Tem & Hum");
    lv_obj_set_style_text_color(ui_LabelTypeTemHum, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTypeTemHum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTypeTemHum, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDevEUITemHum = lv_label_create(ui_PanelSensorNodeTemHum);
    lv_obj_set_width(ui_LabelDevEUITemHum, 80);   /// 1 
    lv_obj_set_height(ui_LabelDevEUITemHum, 16);    /// 1 
    lv_obj_set_x(ui_LabelDevEUITemHum, -35);//-41
    lv_obj_set_y(ui_LabelDevEUITemHum, -20);
    lv_obj_set_align(ui_LabelDevEUITemHum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDevEUITemHum, "ABCDEF");
    lv_obj_set_style_text_color(ui_LabelDevEUITemHum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDevEUITemHum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDevEUITemHum, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelDevEUITemHum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelDevEUITemHum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LabelDevEUITemHum, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_LabelDevEUITemHum, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelDevEUITemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelDevEUITemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelDevEUITemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelDevEUITemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_LabelDevEUITemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_LabelDevEUITemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNameTemHum = lv_label_create(ui_PanelSensorNodeTemHum);
    lv_obj_set_width(ui_LabelNameTemHum, 66);
    lv_obj_set_height(ui_LabelNameTemHum, 32);
    lv_obj_set_x(ui_LabelNameTemHum, -16);
    lv_obj_set_y(ui_LabelNameTemHum, 55);
    lv_label_set_long_mode(ui_LabelNameTemHum, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_LabelNameTemHum, "0123456789ABCDEF");
    lv_obj_set_style_text_color(ui_LabelNameTemHum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelNameTemHum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNameTemHum, &ui_font_Font12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelNameTemHum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelNameTemHum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LabelNameTemHum, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_LabelNameTemHum, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSignalStrengthTemHum = lv_obj_create(ui_PanelSensorNodeTemHum);
    lv_obj_set_width(ui_PanelSignalStrengthTemHum, 71);
    lv_obj_set_height(ui_PanelSignalStrengthTemHum, 15);
    lv_obj_set_x(ui_PanelSignalStrengthTemHum, 39);
    lv_obj_set_y(ui_PanelSignalStrengthTemHum, -21);
    lv_obj_set_align(ui_PanelSignalStrengthTemHum, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelSignalStrengthTemHum, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_PanelSignalStrengthTemHum, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSignalStrengthTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSignalStrengthTemHum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSignalStrengthTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSignalStrengthTemHum, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelSignalStrengthTemHum, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageSignalStrengthTemHum = lv_img_create(ui_PanelSignalStrengthTemHum);
    lv_img_set_src(ui_ImageSignalStrengthTemHum, &ui_img_signal_empty_png);
    lv_obj_set_width(ui_ImageSignalStrengthTemHum, 25);
    lv_obj_set_height(ui_ImageSignalStrengthTemHum, 16);
    lv_obj_set_x(ui_ImageSignalStrengthTemHum, -23);
    lv_obj_set_y(ui_ImageSignalStrengthTemHum, 0);
    lv_obj_set_align(ui_ImageSignalStrengthTemHum, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageSignalStrengthTemHum, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageSignalStrengthTemHum, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_ImageSignalStrengthTemHum, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);//0x83A2AF
    lv_obj_set_style_img_recolor_opa(ui_ImageSignalStrengthTemHum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderSignalStrengthTemHum = lv_slider_create(ui_PanelSignalStrengthTemHum);
    lv_slider_set_range(ui_SliderSignalStrengthTemHum, -128, 16);// -80 -60
    lv_slider_set_value(ui_SliderSignalStrengthTemHum, -60, LV_ANIM_OFF);//16
    if(lv_slider_get_mode(ui_SliderSignalStrengthTemHum) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_SliderSignalStrengthTemHum, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderSignalStrengthTemHum, 24);
    lv_obj_set_height(ui_SliderSignalStrengthTemHum, 16);
    lv_obj_set_x(ui_SliderSignalStrengthTemHum, -22);
    lv_obj_set_y(ui_SliderSignalStrengthTemHum, 0);
    lv_obj_set_align(ui_SliderSignalStrengthTemHum, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SliderSignalStrengthTemHum, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_radius(ui_SliderSignalStrengthTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderSignalStrengthTemHum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSignalStrengthTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_img_src(ui_SliderSignalStrengthTemHum, &ui_img_signal_empty_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderSignalStrengthTemHum, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderSignalStrengthTemHum, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSignalStrengthTemHum, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SliderSignalStrengthTemHum, &ui_img_signal_full_png,
                                LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderSignalStrengthTemHum, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderSignalStrengthTemHum, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSignalStrengthTemHum, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelSignalStrengthValueTemHum = lv_label_create(ui_PanelSignalStrengthTemHum);
    lv_obj_set_width(ui_LabelSignalStrengthValueTemHum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSignalStrengthValueTemHum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSignalStrengthValueTemHum, 13);
    lv_obj_set_y(ui_LabelSignalStrengthValueTemHum, -1);
    lv_obj_set_align(ui_LabelSignalStrengthValueTemHum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSignalStrengthValueTemHum, "Rssi: -80");
    lv_obj_set_style_text_color(ui_LabelSignalStrengthValueTemHum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSignalStrengthValueTemHum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSignalStrengthValueTemHum, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelBatteryTemHum = lv_obj_create(ui_PanelSensorNodeTemHum);
    lv_obj_set_width(ui_PanelBatteryTemHum, 72);
    lv_obj_set_height(ui_PanelBatteryTemHum, 16);
    lv_obj_set_x(ui_PanelBatteryTemHum, 40);
    lv_obj_set_y(ui_PanelBatteryTemHum, 2);
    lv_obj_set_align(ui_PanelBatteryTemHum, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelBatteryTemHum, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_PanelBatteryTemHum, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelBatteryTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelBatteryTemHum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelBatteryTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelBatteryTemHum, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelBatteryTemHum, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelBatteryTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelBatteryTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelBatteryTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelBatteryTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelBatteryTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelBatteryTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageBatteryTemHum = lv_img_create(ui_PanelBatteryTemHum);
    lv_img_set_src(ui_ImageBatteryTemHum, &ui_img_battery_empty_png);
    lv_obj_set_width(ui_ImageBatteryTemHum, 25);
    lv_obj_set_height(ui_ImageBatteryTemHum, 15);
    lv_obj_set_x(ui_ImageBatteryTemHum, -25);
    lv_obj_set_y(ui_ImageBatteryTemHum, 0);
    lv_obj_set_align(ui_ImageBatteryTemHum, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageBatteryTemHum, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageBatteryTemHum, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SliderBatteryTemHum = lv_slider_create(ui_PanelBatteryTemHum);
    lv_slider_set_range(ui_SliderBatteryTemHum, 2000, 4200);
    lv_slider_set_value(ui_SliderBatteryTemHum, 3700, LV_ANIM_OFF);//2000
    if(lv_slider_get_mode(ui_SliderBatteryTemHum) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderBatteryTemHum,
                                                                                                        0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderBatteryTemHum, 25);//44
    lv_obj_set_height(ui_SliderBatteryTemHum, 15);
    lv_obj_set_x(ui_SliderBatteryTemHum, -25);
    lv_obj_set_y(ui_SliderBatteryTemHum, 0);
    lv_obj_set_align(ui_SliderBatteryTemHum, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SliderBatteryTemHum, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_radius(ui_SliderBatteryTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderBatteryTemHum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderBatteryTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_img_src(ui_SliderBatteryTemHum, &ui_img_battery_empty_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_img_opa(ui_SliderBatteryTemHum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderBatteryTemHum, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderBatteryTemHum, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderBatteryTemHum, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SliderBatteryTemHum, &ui_img_battery_full_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderBatteryTemHum, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderBatteryTemHum, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderBatteryTemHum, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelBatteryTemHum = lv_label_create(ui_PanelBatteryTemHum);
    lv_obj_set_width(ui_LabelBatteryTemHum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBatteryTemHum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBatteryTemHum, 13);
    lv_obj_set_y(ui_LabelBatteryTemHum, 0);
    lv_obj_set_align(ui_LabelBatteryTemHum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBatteryTemHum, "3700mV");
    lv_obj_set_style_text_color(ui_LabelBatteryTemHum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBatteryTemHum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBatteryTemHum, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTemTemHum = lv_obj_create(ui_PanelSensorNodeTemHum);
    lv_obj_set_width(ui_PanelTemTemHum, 50);
    lv_obj_set_height(ui_PanelTemTemHum, 27);
    lv_obj_set_x(ui_PanelTemTemHum, -51);//-54 -48 -50
    lv_obj_set_y(ui_PanelTemTemHum, 45);
    lv_obj_set_align(ui_PanelTemTemHum, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelTemTemHum, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_PanelTemTemHum, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelTemTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelTemTemHum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTemTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelTemTemHum, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelTemTemHum, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTemTemHum = lv_label_create(ui_PanelTemTemHum);
    lv_obj_set_width(ui_LabelTemTemHum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTemTemHum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTemTemHum, 0);
    lv_obj_set_y(ui_LabelTemTemHum, -8);
    lv_obj_set_align(ui_LabelTemTemHum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTemTemHum, "Tem");
    lv_obj_set_style_text_color(ui_LabelTemTemHum, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTemTemHum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTemTemHum, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTemValueTemHum = lv_label_create(ui_PanelTemTemHum);
    lv_obj_set_width(ui_LabelTemValueTemHum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTemValueTemHum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTemValueTemHum, 0);
    lv_obj_set_y(ui_LabelTemValueTemHum, 7);
    lv_obj_set_align(ui_LabelTemValueTemHum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTemValueTemHum, "00.00℃");
    lv_obj_set_style_text_color(ui_LabelTemValueTemHum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTemValueTemHum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTemValueTemHum, &ui_font_Font12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelHumTemHum = lv_obj_create(ui_PanelSensorNodeTemHum);
    lv_obj_set_width(ui_PanelHumTemHum, 65);
    lv_obj_set_height(ui_PanelHumTemHum, 28);
    lv_obj_set_x(ui_PanelHumTemHum, 5);//7
    lv_obj_set_y(ui_PanelHumTemHum, 43);
    lv_obj_set_align(ui_PanelHumTemHum, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelHumTemHum, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_PanelHumTemHum, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelHumTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelHumTemHum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelHumTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelHumTemHum, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelHumTemHum, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelHumTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelHumTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelHumTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelHumTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelHumTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelHumTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHumTemHum = lv_label_create(ui_PanelHumTemHum);
    lv_obj_set_width(ui_LabelHumTemHum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHumTemHum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHumTemHum, 0);
    lv_obj_set_y(ui_LabelHumTemHum, -8);
    lv_obj_set_align(ui_LabelHumTemHum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHumTemHum, "Hum");
    lv_obj_set_style_text_color(ui_LabelHumTemHum, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHumTemHum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHumTemHum, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHumValueTemHum = lv_label_create(ui_PanelHumTemHum);
    lv_obj_set_width(ui_LabelHumValueTemHum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHumValueTemHum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHumValueTemHum, 0);
    lv_obj_set_y(ui_LabelHumValueTemHum, 7);
    lv_obj_set_align(ui_LabelHumValueTemHum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHumValueTemHum, "00.0%RH");
    lv_obj_set_style_text_color(ui_LabelHumValueTemHum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHumValueTemHum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHumValueTemHum, &ui_font_Font12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelExtTemHum = lv_obj_create(ui_PanelSensorNodeTemHum);
    lv_obj_set_width(ui_PanelExtTemHum, 50);
    lv_obj_set_height(ui_PanelExtTemHum, 28);
    lv_obj_set_x(ui_PanelExtTemHum, 52);
    lv_obj_set_y(ui_PanelExtTemHum, 27);
    lv_obj_set_align(ui_PanelExtTemHum, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelExtTemHum, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_PanelExtTemHum, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelExtTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelExtTemHum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelExtTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelExtTemHum, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelExtTemHum, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelExtTemHum = lv_label_create(ui_PanelExtTemHum);
    lv_obj_set_width(ui_LabelExtTemHum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelExtTemHum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelExtTemHum, 0);
    lv_obj_set_y(ui_LabelExtTemHum, -8);
    lv_obj_set_align(ui_LabelExtTemHum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelExtTemHum, "Ext");
    lv_obj_set_style_text_color(ui_LabelExtTemHum, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelExtTemHum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelExtTemHum, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelExtValueTemHum = lv_label_create(ui_PanelExtTemHum);
    lv_obj_set_width(ui_LabelExtValueTemHum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelExtValueTemHum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelExtValueTemHum, 0);
    lv_obj_set_y(ui_LabelExtValueTemHum, 7);
    lv_obj_set_align(ui_LabelExtValueTemHum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelExtValueTemHum, "00.00℃");
    lv_obj_set_style_text_color(ui_LabelExtValueTemHum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelExtValueTemHum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelExtValueTemHum, &ui_font_Font12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTimePassedTemHum = lv_obj_create(ui_PanelSensorNodeTemHum);
    lv_obj_set_width(ui_PanelTimePassedTemHum, 128);
    lv_obj_set_height(ui_PanelTimePassedTemHum, 20);
    lv_obj_set_x(ui_PanelTimePassedTemHum, -14);
    lv_obj_set_y(ui_PanelTimePassedTemHum, 70);
    lv_obj_set_align(ui_PanelTimePassedTemHum, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelTimePassedTemHum, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_PanelTimePassedTemHum, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelTimePassedTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelTimePassedTemHum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTimePassedTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelTimePassedTemHum, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelTimePassedTemHum, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelTimePassedTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelTimePassedTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelTimePassedTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelTimePassedTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageTimePassedTemHum = lv_img_create(ui_PanelTimePassedTemHum);
    lv_img_set_src(ui_ImageTimePassedTemHum, &ui_img_last_seen_png);
    lv_obj_set_width(ui_ImageTimePassedTemHum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageTimePassedTemHum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageTimePassedTemHum, 1);
    lv_obj_set_y(ui_ImageTimePassedTemHum, 0);
    lv_obj_add_flag(ui_ImageTimePassedTemHum, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageTimePassedTemHum, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ImageTimePassedTemHum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ImageTimePassedTemHum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ImageTimePassedTemHum, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ImageTimePassedTemHum, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTimePassedValueTemHum = lv_label_create(ui_PanelTimePassedTemHum);
    lv_obj_set_width(ui_LabelTimePassedValueTemHum, 103);
    lv_obj_set_height(ui_LabelTimePassedValueTemHum, 16);
    lv_obj_set_x(ui_LabelTimePassedValueTemHum, 22);
    lv_obj_set_y(ui_LabelTimePassedValueTemHum, 1);
    lv_label_set_text(ui_LabelTimePassedValueTemHum, "00: 00: 00: 00");
    lv_obj_set_style_text_color(ui_LabelTimePassedValueTemHum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTimePassedValueTemHum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTimePassedValueTemHum, &ui_font_Font12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelTimePassedValueTemHum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelTimePassedValueTemHum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LabelTimePassedValueTemHum, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_LabelTimePassedValueTemHum, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTopTemHum = lv_obj_create(ui_PanelSensorNodeTemHum);
    lv_obj_set_width(ui_PanelTopTemHum, LV_SIZE_CONTENT);   
    lv_obj_set_height(ui_PanelTopTemHum, LV_SIZE_CONTENT);    
    lv_obj_set_x(ui_PanelTopTemHum, 65);
    lv_obj_set_y(ui_PanelTopTemHum, 67);
    lv_obj_set_align(ui_PanelTopTemHum, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelTopTemHum, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelTopTemHum, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelTopTemHum, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelTopTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelTopTemHum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTopTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelTopTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelTopTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelTopTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelTopTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelTopTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelTopTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelTopTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageButtonTopTemHum = lv_imgbtn_create(ui_PanelTopTemHum);
    lv_imgbtn_set_src(ui_ImageButtonTopTemHum, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_set_top_png, NULL);
    lv_imgbtn_set_src(ui_ImageButtonTopTemHum, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_cancel_set_top_png, NULL);
    lv_imgbtn_set_src(ui_ImageButtonTopTemHum, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImageButtonTopTemHum, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_set_top_png, NULL);
    lv_imgbtn_set_src(ui_ImageButtonTopTemHum, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_cancel_set_top_png, NULL);
    lv_imgbtn_set_src(ui_ImageButtonTopTemHum, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImageButtonTopTemHum, 25);
    lv_obj_set_height(ui_ImageButtonTopTemHum, 25);
    lv_obj_set_x(ui_ImageButtonTopTemHum, 0);
    lv_obj_set_y(ui_ImageButtonTopTemHum, 1);
    lv_obj_add_flag(ui_ImageButtonTopTemHum, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_border_color(ui_ImageButtonTopTemHum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ImageButtonTopTemHum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ImageButtonTopTemHum, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ImageButtonTopTemHum, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_ImageButtonTopTemHum, lv_color_hex(0x4BD5CB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ImageButtonTopTemHum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSensorNodeDeleteTemHum = lv_obj_create(ui_PanelSensorTemHum);
    lv_obj_set_width(ui_PanelSensorNodeDeleteTemHum, 156);
    lv_obj_set_height(ui_PanelSensorNodeDeleteTemHum, 160);
    lv_obj_set_align(ui_PanelSensorNodeDeleteTemHum, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelSensorNodeDeleteTemHum, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelSensorNodeDeleteTemHum, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSensorNodeDeleteTemHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSensorNodeDeleteTemHum, lv_color_hex(0x162137), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSensorNodeDeleteTemHum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSensorNodeDeleteTemHum, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelSensorNodeDeleteTemHum, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageDeleteTemHum = lv_img_create(ui_PanelSensorNodeDeleteTemHum);
    lv_img_set_src(ui_ImageDeleteTemHum, &ui_img_delete_png);
    lv_obj_set_width(ui_ImageDeleteTemHum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageDeleteTemHum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageDeleteTemHum, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageDeleteTemHum, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageDeleteTemHum, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_transform_zoom(ui_ImageDeleteTemHum, 288, LV_PART_MAIN | LV_STATE_PRESSED);
    // lv_obj_set_style_transform_pivot_x(ui_ImageDeleteTemHum, 16, LV_PART_MAIN | LV_STATE_PRESSED);
    // lv_obj_set_style_transform_pivot_y(ui_ImageDeleteTemHum, 16, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_add_event_cb(ui_SliderSignalStrengthTemHum, ui_event_SliderSignalStrengthTemHum, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderBatteryTemHum, ui_event_SliderBatteryTemHum, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImageButtonTopTemHum, ui_event_ImageButtonTopTemHum, LV_EVENT_ALL, ui_PanelSensorTemHum);
    lv_obj_add_event_cb(ui_PanelSensorNodeTemHum, ui_event_PanelSensorNodeTemHum_1, LV_EVENT_ALL, ui_PanelSensorNodeTemHum);
    lv_obj_add_event_cb(ui_PanelSensorNodeTemHum, ui_event_PanelSensorNodeTemHum_2, LV_EVENT_ALL, ui_PanelSensorNodeDeleteTemHum);
    lv_obj_add_event_cb(ui_ImageDeleteTemHum, ui_event_ImageDeleteTemHum, LV_EVENT_ALL, ui_PanelSensorTemHum);
    lv_obj_add_event_cb(ui_PanelSensorNodeDeleteTemHum, ui_event_PanelSensorNodeDeleteTemHum_1, LV_EVENT_ALL, ui_PanelSensorNodeTemHum);
    lv_obj_add_event_cb(ui_PanelSensorNodeDeleteTemHum, ui_event_PanelSensorNodeDeleteTemHum_2, LV_EVENT_ALL, ui_PanelSensorNodeDeleteTemHum);

    panel_with_type union_sensor;

    union_sensor.panel_union.tem_hum.ui_PanelSensorTemHum = ui_PanelSensorTemHum;
    union_sensor.panel_union.tem_hum.ui_PanelSensorNodeTemHum = ui_PanelSensorNodeTemHum;
    union_sensor.panel_union.tem_hum.ui_PanelChartTemHum = ui_PanelChartTemHum;
    union_sensor.panel_union.tem_hum.ui_ChartDisplayTemHum = ui_ChartDisplayTemHum;
    union_sensor.panel_union.tem_hum.ui_LabelTypeTemHum = ui_LabelTypeTemHum;
    union_sensor.panel_union.tem_hum.ui_LabelDevEUITemHum = ui_LabelDevEUITemHum;
    union_sensor.panel_union.tem_hum.ui_LabelNameTemHum = ui_LabelNameTemHum;
    union_sensor.panel_union.tem_hum.ui_PanelSignalStrengthTemHum = ui_PanelSignalStrengthTemHum;
    union_sensor.panel_union.tem_hum.ui_SliderSignalStrengthTemHum = ui_SliderSignalStrengthTemHum;
    union_sensor.panel_union.tem_hum.ui_LabelSignalStrengthValueTemHum = ui_LabelSignalStrengthValueTemHum;
    union_sensor.panel_union.tem_hum.ui_PanelBatteryTemHum = ui_PanelBatteryTemHum;
    union_sensor.panel_union.tem_hum.ui_SliderBatteryTemHum = ui_SliderBatteryTemHum;
    union_sensor.panel_union.tem_hum.ui_LabelBatteryTemHum = ui_LabelBatteryTemHum;
    union_sensor.panel_union.tem_hum.ui_PanelTemTemHum = ui_PanelTemTemHum;
    union_sensor.panel_union.tem_hum.ui_LabelTemTemHum = ui_LabelTemTemHum;
    union_sensor.panel_union.tem_hum.ui_LabelTemValueTemHum = ui_LabelTemValueTemHum;
    union_sensor.panel_union.tem_hum.ui_PanelHumTemHum = ui_PanelHumTemHum;
    union_sensor.panel_union.tem_hum.ui_LabelHumTemHum = ui_LabelHumTemHum;
    union_sensor.panel_union.tem_hum.ui_LabelHumValueTemHum = ui_LabelHumValueTemHum;
    union_sensor.panel_union.tem_hum.ui_PanelExtTemHum = ui_PanelExtTemHum;
    union_sensor.panel_union.tem_hum.ui_LabelExtTemHum = ui_LabelExtTemHum;
    union_sensor.panel_union.tem_hum.ui_LabelExtValueTemHum = ui_LabelExtValueTemHum;
    union_sensor.panel_union.tem_hum.ui_PanelTimePassedTemHum = ui_PanelTimePassedTemHum;
    union_sensor.panel_union.tem_hum.ui_ImageTimePassedTemHum = ui_ImageTimePassedTemHum;
    union_sensor.panel_union.tem_hum.ui_LabelTimePassedValueTemHum = ui_LabelTimePassedValueTemHum;
    union_sensor.panel_union.tem_hum.ui_PanelTopTemHum = ui_PanelTopTemHum;
    union_sensor.panel_union.tem_hum.ui_ImageButtonTopTemHum = ui_ImageButtonTopTemHum;
    union_sensor.panel_union.tem_hum.ui_PanelSensorNodeDeleteTemHum = ui_PanelSensorNodeDeleteTemHum;
    union_sensor.panel_union.tem_hum.ui_ImageDeleteTemHum = ui_ImageDeleteTemHum;

    union_sensor.panel_type = 1;

    lv_obj_set_x(union_sensor.panel_union.tem_hum.ui_PanelSensorTemHum, x_by_index(index));
    lv_obj_set_y(union_sensor.panel_union.tem_hum.ui_PanelSensorTemHum, y_by_index(index));
    
    return union_sensor;
}
